camunda/camunda-platform-helm

charts/zeebe-operate-helm/templates/ingress.yaml
charts/zeebe-operate-helm/values.yaml

`networking.k8s.io/v1beta1` is used from `1.14` to `1.18`.
`networking.k8s.io/v1` is used to `1.19+`
reference: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
A new ingressClassName field has been added to the Ingress spec that is used to reference the IngressClass that should be used to implement this Ingress.
reference: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress

Fixing ingress version and adding new class parameter

---

charts/zeebe-cluster-helm/README.md
charts/zeebe-cluster-helm/templates/gateway-service.yaml
charts/zeebe-cluster-helm/values.yaml

Adding value to parameterize the type of service to be created for the Cluster Gateway.
This will allow us to use the LoadBalancer type in the Gateway service to execute zbctl commands from outside the kubernetes cluster running on some cloud provider.

Adding value to parameterize the type of service to be created for the Cluster Gateway

---

charts/zeebe-operate-helm/templates/configmap.yaml
charts/zeebe-operate-helm/values.yaml

Parameterized full global elasticsearch URL. This setting will allow the use of URLs with "https".
If the value is not informed, the default is not to add this field to ConfigMap because the default value of the default values file is an empty string.

Parameterize Operate Elasticsearch global full URL

---

charts/zeebe-operate-helm/README.md
charts/zeebe-operate-helm/templates/configmap.yaml
charts/zeebe-operate-helm/values.yaml

- Adding possibility to change the port Operate uses to connect to Zeebe cluster gateway.
- Fixing Zeebe Cluster configuration parameters in README. Adding `global.` and new parameter `global.zeebePort`

Parameterizing Zeebe cluster port

---

charts/zeebe-operate-helm/templates/deployment.yaml

Resources are included in the default values but have not actually been used in the deployment.

Make Operate resources configurable

---

charts/zeebe-cluster-helm/templates/statefulset.yaml

Sets the default encoding to UTF-8, in the current release 1.3.0 the locale is not set which can cause data corruption.
Related to https://github.com/camunda-cloud/zeebe/pull/8580

fix: set utf8 locale for zeebe

---

charts/ccsm-helm/Chart.yaml
charts/ccsm-helm/charts/operate/.helmignore
charts/ccsm-helm/charts/operate/Chart.yaml
charts/ccsm-helm/charts/operate/README.md
charts/ccsm-helm/charts/operate/templates/NOTES.txt
charts/ccsm-helm/charts/operate/templates/_helpers.tpl
charts/ccsm-helm/charts/operate/templates/configmap.yaml
charts/ccsm-helm/charts/operate/templates/deployment.yaml
charts/ccsm-helm/charts/operate/templates/ingress.yaml
charts/ccsm-helm/charts/operate/templates/service.yaml
charts/ccsm-helm/charts/operate/templates/serviceaccount.yaml
charts/ccsm-helm/charts/operate/templates/tests/test-connection.yaml
charts/ccsm-helm/charts/operate/values.yaml
charts/ccsm-helm/charts/zeebe/Chart.yaml
charts/ccsm-helm/charts/zeebe/templates/NOTES.txt
charts/ccsm-helm/charts/zeebe/templates/_helpers.tpl
charts/ccsm-helm/charts/zeebe/templates/gateway-deployment.yaml
charts/ccsm-helm/charts/zeebe/templates/statefulset.yaml
charts/ccsm-helm/charts/zeebe/templates/tests/test-connection.yaml
charts/ccsm-helm/charts/zeebe/values.yaml
charts/ccsm-helm/templates/NOTES.txt
charts/ccsm-helm/values.yaml

* Copies the old zeebe-operate-helm chart into the ccsm chart.
* Renames the chart to operate instead of zeebe-operate-helm
* Fixes some properties in zeebe and operate charts, in regards to the new sub chart
* Fix an elastic issue (disable security to omit warning)
* Create new NOTEST.txt for the ccsm helm - this file shows after installation what has been installed and how to use it
* Tested manually, via deploying into kubernetes, starting some instances and verifying in operate
* increase ccsm chart version
related to #124 
Missing: 
* Readme update
* Values file documentation

Add operate sub chart

---

charts/ccsm-helm/charts/zeebe-gateway/templates/configmap.yaml
charts/ccsm-helm/charts/zeebe/templates/configmap.yaml
charts/ccsm-helm/charts/zeebe/templates/statefulset.yaml

Reworks the zeebe config maps which are deployed with the services/applications.
* Remove the startup scripts from the gateway config map
* Replace most of the code from the zeebe startup script with kubernetes [dependent environment variables ](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/)
* inspired by https://github.com/camunda-community-hub/camunda-cloud-operator/blob/main/operator/controllers/zeebe_controller.go 
* **Why:** To have everything in one place and for better maintainability most of the env vars are set in the statefulset manifest. 
* Initial contact points are calculated with helm template range (inspired by https://github.com/helm/helm/issues/1055)
I tried it out and the following is calculated correctly:
```
$ k …
```

Rework config map's

---

charts/ccsm-helm/charts/zeebe/templates/configmap.yaml

The configmap was unused and make the configuration not really easy. All zeebe configurations can be done via env vars.

refactor: remove unused configmap

---

charts/ccsm-helm/charts/zeebe/templates/service-monitor.yaml

Service monitor uses the wrong template for label selector

fix: use correct labels

---

charts/ccsm-helm/README.md
charts/ccsm-helm/charts/operate/templates/deployment.yaml
charts/ccsm-helm/charts/operate/values.yaml
charts/ccsm-helm/charts/tasklist/templates/deployment.yaml
charts/ccsm-helm/charts/tasklist/values.yaml
charts/ccsm-helm/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/ccsm-helm/charts/zeebe/templates/statefulset.yaml
charts/ccsm-helm/values.yaml

Previously the subcharts reused a global variables which caused issues on setting different image repositories. For each subchart now an own image.repository variable is used. The global tag is still possible, use case to set a version only once. But it is possible to overwrite the global setting with a subchart specific image tag.
So it would be possible to use a different operate version than zeebe version, if necessary.
fixes https://github.com/camunda-community-hub/camunda-cloud-helm/issues/161

Add possibility to overwrite images correctly

---

charts/ccsm-helm/README.md
charts/ccsm-helm/templates/curator-configmap.yaml
charts/ccsm-helm/templates/curator-cronjob.yaml
charts/ccsm-helm/values.yaml

* Adds curator templates for cronjob and configmap.
* Disabled by default
* Zeebe index can be deleted by time
* Tasklist index can be deleted by time
* Operate index can be deleted by time
* Zeebe indexes can be deleted by size (have to be enabled separately, useful for our benchmarks)
Everything can be configured by the following values:
```yaml
retentionPolicy:
enabled: false
schedule: "0 0 * * *"
zeebeIndexTTL: 1
zeebeIndexMaxSize:
operateIndexTTL: 30
tasklistIndexTTL: 30
```
Tested via `helm install --dry-run test . --set retentionPolicy.enabled=true --set retentionPolicy.zeebeIndexMaxSize=10`
Output:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
name: ccsm-curator-config
labels:
app: camunda-cloud-self-managed
app.kubernetes.io/name: ccsm-helm
helm.sh/chart: ccsm-helm-0.0.10 …
```

Add retention policy

---

charts/ccsm-helm/templates/NOTES.txt

Takslist and Operate should not be part of the release notes if not enabled, this PR adds a extra condition to the notes template to hide it them.
When enabled (default):
```
NOTES:
______     ______     __    __     __  __     __   __     _____     ______        ______     __         ______     __  __     _____
/\  ___\   /\  __ \   /\ "-./  \   /\ \/\ \   /\ "-.\ \   /\  __-.  /\  __ \      /\  ___\   /\ \       /\  __ \   /\ \/\ \   /\  __-.
\ \ \____  \ \  __ \  \ \ \-./\ \  \ \ \_\ \  \ \ \-.  \  \ \ \/\ \ \ \  __ \     \ \ \____  \ \ \____  \ \ \/\ \  \ \ \_\ \  \ \ \/\ \
\ \_____\  \ \_\ \_\  \ \_\ \ \_\  \ \_____\  \ \_\\"\_\  \ \____-  \ \_\ \_\     \ \_____\  \ \_____\  \ \_____\  \ \_____\  \ \____-
\/_____/   \/_/\/_/   \/_/  \/_/   \/_____/   \/_/ \/_/   \/____/   \/_/\/_/ …
```

Hide services details if disabled

---

charts/zeebe-cluster-helm/Chart.yaml
charts/zeebe-cluster-helm/templates/NOTES.txt
charts/zeebe-full-helm/Chart.yaml
charts/zeebe-full-helm/templates/NOTES.txt
charts/zeebe-operate-helm/Chart.yaml
charts/zeebe-operate-helm/templates/NOTES.txt
charts/zeebe-tasklist-helm/Chart.yaml
charts/zeebe-tasklist-helm/templates/NOTES.txt

Deprecates the zeebe-* charts
Add note on:
* zeebe-full
* zeebe-cluster
* zeebe-operate
* zeebe-tasklist
Marks them depreacted in the chart.yaml

Deprecate charts

---

charts/ccsm-helm/test/golden/curator-configmap.golden.yaml
charts/ccsm-helm/test/golden/curator-cronjob.golden.yaml
charts/ccsm-helm/test/golden/goldenfiles.go
charts/ccsm-helm/test/golden/service-monitor.golden.yaml
charts/ccsm-helm/test/operate/golden/configmap-elastic-url.golden.yaml
charts/ccsm-helm/test/operate/golden/configmap.golden.yaml
charts/ccsm-helm/test/operate/golden/deployment.golden.yaml
charts/ccsm-helm/test/operate/golden/ingress-all-enabled.golden.yaml
charts/ccsm-helm/test/operate/golden/ingress.golden.yaml
charts/ccsm-helm/test/operate/golden/service.golden.yaml
charts/ccsm-helm/test/operate/golden/serviceaccount.golden.yaml
charts/ccsm-helm/test/tasklist/golden/configmap.golden.yaml
charts/ccsm-helm/test/tasklist/golden/deployment.golden.yaml
charts/ccsm-helm/test/tasklist/golden/service.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/configmap.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-service.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-serviceaccount.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
charts/ccsm-helm/test/zeebe/golden/configmap-log4j2.golden.yaml
charts/ccsm-helm/test/zeebe/golden/configmap.golden.yaml
charts/ccsm-helm/test/zeebe/golden/poddisruptionbudget.golden.yaml
charts/ccsm-helm/test/zeebe/golden/service.golden.yaml
charts/ccsm-helm/test/zeebe/golden/serviceaccount.golden.yaml
charts/ccsm-helm/test/zeebe/golden/statefulset-containersecuritycontext.golden.yaml
charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml

The chart version does change regularly, we should ignore them on golden files to not always need to re-generate them.
Related https://medium.com/@jarifibrahim/golden-files-why-you-should-use-them-47087ec994bf

Ignore version in golden files

---

charts/ccsm-helm/charts/operate/Chart.yaml
charts/ccsm-helm/charts/tasklist/Chart.yaml
charts/ccsm-helm/charts/zeebe-gateway/Chart.yaml
charts/ccsm-helm/charts/zeebe/Chart.yaml
charts/ccsm-helm/templates/_helpers.tpl
charts/ccsm-helm/test/golden/curator-configmap.golden.yaml
charts/ccsm-helm/test/golden/curator-cronjob.golden.yaml
charts/ccsm-helm/test/golden/service-monitor.golden.yaml
charts/ccsm-helm/test/operate/golden/configmap-elastic-url.golden.yaml
charts/ccsm-helm/test/operate/golden/configmap.golden.yaml
charts/ccsm-helm/test/operate/golden/deployment.golden.yaml
charts/ccsm-helm/test/operate/golden/ingress-all-enabled.golden.yaml
charts/ccsm-helm/test/operate/golden/ingress.golden.yaml
charts/ccsm-helm/test/operate/golden/service.golden.yaml
charts/ccsm-helm/test/operate/golden/serviceaccount.golden.yaml
charts/ccsm-helm/test/tasklist/golden/configmap.golden.yaml
charts/ccsm-helm/test/tasklist/golden/deployment.golden.yaml
charts/ccsm-helm/test/tasklist/golden/service.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/configmap.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-service.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-serviceaccount.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
charts/ccsm-helm/test/zeebe/golden/configmap-log4j2.golden.yaml
charts/ccsm-helm/test/zeebe/golden/configmap.golden.yaml
charts/ccsm-helm/test/zeebe/golden/poddisruptionbudget.golden.yaml
charts/ccsm-helm/test/zeebe/golden/service.golden.yaml
charts/ccsm-helm/test/zeebe/golden/serviceaccount.golden.yaml
charts/ccsm-helm/test/zeebe/golden/statefulset-containersecuritycontext.golden.yaml
charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml

Instead of setting the appversion in each subchart, we use the image tag as version label. Add quotes to the appVersion as described in docs. 
> appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
https://helm.sh/docs/topics/charts/

Use image tag as app version

---

charts/ccsm-helm/README.md
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml
charts/ccsm-helm/values.yaml

* Per default the java max ram percentage is set to the same value, so we removed the max ram percentage
* In order to make sure that the gateway exits on out of memory, we set related java option and add documentation around the javaOpts variable
closes https://github.com/camunda/camunda-cloud-helm/issues/155

Iterate over java opts

---

charts/ccsm-helm/README.md
charts/ccsm-helm/charts/zeebe-gateway/templates/gateway-service.yaml
charts/ccsm-helm/test/zeebe-gateway/golden/gateway-service.golden.yaml
charts/ccsm-helm/test/zeebe-gateway/service_test.go
charts/ccsm-helm/values.yaml

**What?**
I have added the ability for zeebe-gateway service to have its own custom annotations.
**Why?**
Having ONLY common annotations is not enough. For example if we want to expose each service with a custom domain name

Added ability to Provide Custome Service Annotations for zeebe-gateway

---

charts/ccsm-helm/test/integration/integration_test.go
charts/ccsm-helm/test/integration/it-test-process.bpmn

Did some refactoring on the IT tests, like introducing new separate methods for awaiting pod readiness etc.
Furthermore enhanced the IT test such that we cover more services. 
What the IT now contains:
* Deploy a workflow
* Create a process instance
* Await elastic readiness
* [Use a http client to login on operate and request the process definition](https://camunda.slack.com/archives/C9B5270DA/p1646216140017879)
* Verify the result
We use the retry functionality to make sure to reduce the chance for flakiness, it is similar to our awaitility usage in zeebe test code. 
Next step would be to also introduce the tasklist query api.
related to #214

IT test enhancement

---

.github/workflows/go-it.yaml

Adds a condition to the integration tests github action. This should avoid executing the IT for external contributors.
First I wanted to check just the existence of a secret but this is not possible in conditions, see https://github.com/actions/runner/issues/520
But there is a workaround, which is posted here https://github.com/actions/runner/issues/520#issuecomment-907770967
We could also check the github actor like it is done for dependabot, but this would mean that we have to know who is allowed to run the IT tests. https://github.community/t/how-to-stop-github-actions-workflow-to-trigger-when-the-pull-request-is-from-dependabot-preview/116486 This is the reason why I went the way of checking whether the secret exists.
closes https://github.com/camunda/camunda-cloud-helm/issues/237

Add Condition for IT gha

---

charts/ccsm-helm/README.md
charts/ccsm-helm/charts/operate/templates/service.yaml
charts/ccsm-helm/test/operate/golden/service.golden.yaml
charts/ccsm-helm/test/operate/service_test.go
charts/ccsm-helm/values.yaml

**What?**
I have added the ability for operate service to have its own custom annotations.
**Why?**
Having ONLY common annotations is not enough. For example if we want to expose each service with a custom domain name

feat: Added missing annotations for zeebe operate service

---

.github/workflows/go-it.yaml

In order to replace our hacky way of access the gke we should use a more safer and supported way with the github actions provided by google 
In order to that I followed this guide https://github.com/google-github-actions/auth#setting-up-workload-identity-federation to setup the needed workload-identity-federation. 
Afterwards we can use the https://github.com/google-github-actions/auth to authenticate with google cloud. This is necessary to get our gke credentials via https://github.com/google-github-actions/get-gke-credentials
The last github action already sets up kubectl and the needed environment variables, which completely replaces our earlier setup.
We can now run it tests, without the secret checks as well, since we don't need any secrets anymore.
closes …

Use google github actions

---

charts/ccsm-helm/README.md
charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml
charts/ccsm-helm/values.yaml

In order to not schedule pods on the same node, for stability but also performance reasons we add anti-affinity rules, similar to the ones we have in our SaaS offering.
related to https://github.com/camunda/camunda-platform-helm/issues/223

Add Zeebe broker anti-affinity

---

.github/workflows/go-it.yaml

> If external contributor create a PR gcloud auth fails with:
> 
> ```
> Error: google-github-actions/auth failed with: gitHub Actions did not inject $ACTIONS_ID_TOKEN_REQUEST_TOKEN or $ACTIONS_ID_TOKEN_REQUEST_URL into this job. This most likely means the GitHub Actions workflow permissions are incorrect, or this job is being run from a fork. For more information, please see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
> ```
This happens since it needs write permission, but for forks github only allows read.
We can exclude PR's which come from forks see https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363/2 
closes https://github.com/camunda/camunda-platform-helm/issues/243

Add condition to it job

---

charts/ccsm-helm/charts/zeebe/templates/statefulset.yaml
charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml

Kubernetes clusters can override the clusterDomain, which defaults to `cluster.local`. For clusters using a non-default clusterDomain the value of `ZEEBE_BROKER_NETWORK_ADVERTISEDHOST` and `ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS` are incorrect.
A default `resolv.conf` for a Pod contains following `search`:
```bash
search $NAMESPACE.svc.$CLUSTER_DOMAIN svc.$CLUSTER_DOMAIN $CLUSTER_DOMAIN
```
Hence the `$CLUSTER_DOMAIN` part can be omitted from the mentioned environment variables.

Use relative DNS for clusters with non-default clusterDomain

---

charts/ccsm-helm/charts/identity/templates/deployment.yaml
charts/ccsm-helm/test/identity/golden/deployment.golden.yaml
charts/ccsm-helm/test/integration/integration_test.go

Integrate in the current IT test identity, to verify whether the services are coming up and we can log in to identity/keycloak. This is later also necessary to access operate and tasklist.
Details:
*  In order to log in we need to port-forward to identity (:8080) and keycloak (:18080)
* We need to get the log in URL from identity (GET /auth/login to resolve url with session code)
* Login with session URL and demo:demo user
* After log in we get a JWT, which we verify on a identity resource
Since all of this can be quite flaky, due to the properties of distributed systems (many dependency's and fragile environment) we retry the log in.
Dear reviewers:
@oleschoenburg just check whether you understand what is happening. I will later do some more refactoring to split the functions in separate …

Add identity IT

---

charts/ccsm-helm/Chart.yaml
charts/ccsm-helm/charts/identity/Chart.yaml
charts/ccsm-helm/charts/operate/Chart.yaml
charts/ccsm-helm/charts/tasklist/Chart.yaml
charts/ccsm-helm/charts/zeebe-gateway/Chart.yaml
charts/ccsm-helm/charts/zeebe/Chart.yaml
charts/ccsm-helm/templates/NOTES.txt

Merging this PR will cause the last release and mark the chart as deprecated.
Furthermore it adds a note to the release notes that the chart is deprecated and camunda-platform should be used instead
:warning: Shouldn't be merged before #261

Deprecating ccsm

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/values.yaml

Allows the user to configure the first identity user and overwrite the name and password. 
Note: In the release helm notes I decided to not print the actual set values for security reasons, so we will only print the default: demo/demo values.

feat: make first user configurable

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/test/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml
charts/camunda-platform/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform/values.yaml

Allows configuring the config map defaultMode for all services, which is useful to run the charts in OpenShift.
Please be aware that the golden files have been changed since on Helm template the octal values are converted to decimal values. ([0744 == 484](https://www.rapidtables.com/convert/number/octal-to-decimal.html?x=0744))
closes https://github.com/camunda/camunda-platform-helm/issues/184

Make config map default mode configurable

---

Makefile
charts/camunda-platform/README.md
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/test/integration/integration_test.go
charts/camunda-platform/test/integration/it-values.yaml
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/values.yaml

Add new variable configuration to the values file to configure the initContainers for the Zeebe gateway. This allows for example to add interceptors as jar files to the lib folder.
closes #177

Add initContainer cfg to gateway

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/identity/templates/optimize-secret.yaml
charts/camunda-platform/charts/optimize/.helmignore
charts/camunda-platform/charts/optimize/Chart.yaml
charts/camunda-platform/charts/optimize/README.md
charts/camunda-platform/charts/optimize/templates/_helpers.tpl
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/ingress.yaml
charts/camunda-platform/charts/optimize/templates/service.yaml
charts/camunda-platform/charts/optimize/templates/serviceaccount.yaml
charts/camunda-platform/charts/optimize/templates/tests/test-connection.yaml
charts/camunda-platform/templates/NOTES.txt
charts/camunda-platform/test/curator_test.go
charts/camunda-platform/test/global_deployment_test.go
charts/camunda-platform/test/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/optimize/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/optimize/golden/ingress.golden.yaml
charts/camunda-platform/test/optimize/golden/service.golden.yaml
charts/camunda-platform/test/optimize/golden/serviceaccount.golden.yaml
charts/camunda-platform/test/optimize/goldenfiles_test.go
charts/camunda-platform/test/optimize/ingress_test.go
charts/camunda-platform/test/optimize/service_test.go
charts/camunda-platform/test/servicemonitor_test.go
charts/camunda-platform/values.yaml

* Add a new sub-chart for optimize (most resources were copied from Tasklist/Operate)
* Add default values to the values.yaml file
* Integrate Optimize with Identity (add configuration on both sides)
* Disable optimize if identity authentication is disabled
* Add template tests
After installing we see:
Doing the necessary port-forwards we can login
* We have to solve the issue with the partition count, which is necessary for Optimize #286 
* Per default optimize will now only import for one partition
* We will add the values documented to the README #284 
* We will enhance our e2e/integration test - login to optimize #283 
I know it looks like an big PR, but most of the lines are due to tests and golden files, which you can skip. :)
@oleschoenburg @npepinpe whoever has more time please …

Add optimize to helm charts

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/test/identity/golden/deployment.golden.yaml

Fixes a bug that setting `global.identity.auth.publicIssuerUrl` does not set the redirect url in Identity

Add publicIssuerUrl to identity chart

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/README.md
charts/camunda-platform/test/global_deployment_test.go
charts/camunda-platform/values.yaml

Based on discussion we disable optimize now via `optimize.enabled`. For more information see comment https://github.com/camunda/camunda-platform-helm/issues/289#issuecomment-1108493461
Add some more tests and a note how to disable identity. 
closes #289

Disable optimize separately 

---

charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

Sets the partition count in optimize sub chart correctly. For simplicity and flexibility, we added a new property to the Optimize sub chart, see comment https://github.com/camunda/camunda-platform-helm/issues/286#issuecomment-1108503752
closes #286

Set partitionCount in optimize

---

charts/camunda-platform/README.md
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

Go with the same as Operate currently uses, which is a kind of importer and webapp resources combined. Makes sense since we have just one deployment for now.
See https://github.com/camunda/camunda-platform-helm/issues/298#issuecomment-1110836354
closes #298

Update default Optimize resources

---

charts/camunda-platform/README.md
charts/camunda-platform/values.yaml

Hi,
I was trying to add
```
extraVolumeMounts:
- mountPath: "/etc/zeebe"
name: zeebe-ssl
readOnly: true
extraVolumes:
- name: zeebe-ssl
secret:
secretName: zeebe-ssl
```
to my YAML but both are defined as empty objects and thus not mergeable:
_coalesce.go:199: warning: cannot overwrite table with non table for extraVolumeMounts (map[])
coalesce.go:199: warning: cannot overwrite table with non table for extraVolumes (map[])_

fix: use correct type

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-service.yaml
charts/camunda-platform/test/zeebe-gateway/service_test.go
charts/camunda-platform/values.yaml

Allow configuration of loadBalancerIP and loadBalancerSourceRanges
which are useful in case of service.type: LoadBalancer

feat: allow more configuration of LoadBalancer

---

kind/camunda-platform-core-kind-values.yaml

Elasticsearch version 7.16.1 is not supported by Optimize.
I know that Optimize is disabled with these values, but maybe if people use this configuration as a starting point, it may be good to use a supported elasticsearch version. 
Current version of Optimize supports following Elasticsearch versions:
7.10.0+
7.11.0+
7.12.0+
7.13.0+
7.14.0+
7.15.0+
7.16.2+
7.17.0+
Your current Elasticsearch version is: 7.16.1

fix: elasticserach version 7.17.3

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform/test/zeebe/statefulset_test.go
charts/camunda-platform/values.yaml

This PR allows configuring `imagePullSecrets` separately for subcharts.
The value of `global.image.pullSecrets` will be used for all subcharts which has the default value of an empy list `[]`.
If the subchart configured `image.pullSecrets` it will overwrite the global value.
Fixes: #302

 Allow configuring imagePullSecrets separately for subcharts

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/values.yaml

Adds the possibility to configure pod annotations on all subcharts.
Added for:
* Operate
* Optimize
* Tasklist
* Identity
Already available in Zeebe and Zeebe Gateway.
closes #327

Add Pod annotations to all sub charts

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/zeebe-gateway/templates/ingress.yaml
charts/camunda-platform/test/zeebe-gateway/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/zeebe-gateway/golden/ingress.golden.yaml
charts/camunda-platform/test/zeebe-gateway/ingress_test.go
charts/camunda-platform/values.yaml

**Description**
This PR adds a new ingress template to the Zeebe gateway chart. It's configurable much like the ingresses for Operate, Tasklist, and Identity. It only exposes the gRPC port of the Zeebe gateway.
Testing is limited to golden files for now, as the current integration tests in general do not use any ingress. I would propose to investigate this separately, e.g. use the built-in ingress controller from GKE for our tests (though that makes the test less portable, of course).
**Related issues**
closes #343

Add ingress template to the Zeebe gateway chart

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/optimize/templates/ingress.yaml
charts/camunda-platform/test/optimize/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/values.yaml

Fixes the issue that Optimize uses http in the redirect url instead of https.
Background here is that the redirect URL is determined from the request and with tls terminating before the ingress it always used http.

Optimize TLS termination on ingress

---

charts/camunda-platform/README.md

The example for `extraInitContainers` in the README did not work for me. My suggestion to update them is based on 
this configuration, which I tested in a real installation: https://github.com/camunda-community-hub/in-engine-job-worker/blob/main/helm-chart-values.yaml

docs(extraInitContainers): fix example

---

openshift/values-patch.yaml

This PR disables the test resources for Elasticsearch when using the OpenShift patch values, as these will not be post-rendered. As they're only test values, this should be acceptable for a production deployment.

Disable test resources in Elasticsearch deployment for OpenShift patch

---

Makefile
README.md
charts/camunda-platform/test/integration/integration_suite.go
charts/camunda-platform/values.yaml

Fixes: #379
Zeebe and Posgtes already use the `app.kubernetes.io/instance` label, so no action is needed for them.

Changed: Enable labels for Elasticsearch PVC

---

charts/camunda-platform/charts/tasklist/templates/ingress.yaml
charts/camunda-platform/test/tasklist/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/tasklist/golden/ingress.golden.yaml
charts/camunda-platform/test/tasklist/ingress_test.go
charts/camunda-platform/values.yaml

For whatever reason, tasklist does not allow you to configure TLS on the ingress like the rest of the camunda components.  These changes address the issue by simply following the same pattern as all of the other camunda ingress templates.

Add TLS configuration to tasklist ingress

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/zeebe/statefulset_test.go

added imagePullPolicy to tasklist, operate, optimize and identity and added tests
#396 
added global imagePullPolicy to templates to match zeebe and zeebegateway
added tests to all for testing override using global pullPolicy
for the same update/change.

fix: unify imagePullPolicy across components

---

charts/camunda-platform/charts/identity/Chart.yaml
charts/camunda-platform/charts/operate/Chart.yaml
charts/camunda-platform/charts/optimize/Chart.yaml
charts/camunda-platform/charts/tasklist/Chart.yaml
charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
charts/camunda-platform/charts/zeebe/Chart.yaml

Fixes: #288
Unify sub-charts icons to use Camunda's logo because:
- The components themselves don't use their logos as a fav icon when run locally.
- In Camunda SaaS also, the components don't use their logos.
- Since we are using an umbrella chart and the sub-chart are not independent charts. 
The wrong icons were used for sub-charts.

Fix: unify sub-charts icons

---

.github/workflows/charttesting.yml
.github/workflows/go-it.yaml
.github/workflows/go.yml
.github/workflows/lint.yaml
.github/workflows/release.yaml
charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/ingress.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/ingress_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/zeebe/statefulset_test.go
charts/camunda-platform/values.yaml

Fixes: camunda/distribution/issues/5
Allow to Camunda Platform 8 components to work on a single domain and multi sub-paths.
N/A

Support single domain setup

---

charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/identity/secret_test.go
charts/camunda-platform/test/integration/integration_suite.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/zeebe/statefulset_test.go

Fixes: #386
A fix to use the correct order of expected and actual parameters in the tests.

fix(test): correct the order of expected and actual parameters

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/zeebe/statefulset_test.go
charts/camunda-platform/values.yaml

Fixes: #374
Allow configuring `securityContext` for pod and container in all charts.

feat: configure securityContext for pod and container

---

charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/test/global_deployment_test.go

Fixes: #419
Add an if condition to disable Identity vars in Optimize when the auth is disabled.

fix: remove identity/optimize vars when auth is disabled

---

charts/camunda-platform/README.md

In the readme the configuration parameter for extra ports is missing the **s** in **extraPorts**.
Getting started with the helm chart is easier, e.g. when setting up a custom exporter.
https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/charts/zeebe/templates/service.yaml 
e.g.
```
service:
extraPorts:
- port: 5701
name: hazelcast
```
- Changed parameter in readme.md from extraPort to **extraPorts**.

docs: use correct parameter for extraPorts

---

charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/test/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml

Fixes: #404
Add the required vars related to Identity JWT tokens source for Operate, Optimize, and Tasklist.
- #417

Set Identity JWT tokens vars for Operate, Optimize, and Tasklist

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/service.yaml
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/optimize/golden/service.golden.yaml
charts/camunda-platform/values.yaml

related to OPT-6499
https://jira.camunda.com/browse/OPT-6499
Adds the default management port 8092 for Optimize to enable users to reach the new hot backup API.

feat(optimize): add management port to reach backup API

---

charts/camunda-platform/templates/ingress.yaml
charts/camunda-platform/test/ingress_test.go

Currently there is no way to deploy the combined Ingress with any of the Camunda Platform disabled.
So this PR allows excluding components in combined the Ingress.
If the component is not enabled or the contextPath is not set, the component endpoint in the Ingress will not be present.

feat: allow to exclude components in combined the ingress

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/Chart.yaml
charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/charts/identity/templates/constraints.tpl
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/templates/NOTES.txt
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/identity/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

Currently, Camunda Platform Identlty depends on Keycloak, shipped as a dependency Helm chart.
This change allows using an existing Keycloak but setting the URL for it.
- Allow to disable Keycloak chart and set external Keycloak URL.
- Add [Bitnami common chart](https://github.com/bitnami/charts/tree/main/bitnami/common/) as a dependency because we were using it as an indirect dependency via Keycloak.
- Add constraints since Keycloak chart and the external Keycloak URL are mutually exclusive.

feat: allow using external/existing keycloak

---

charts/camunda-platform/test/ingress_test.go
charts/camunda-platform/values.yaml

Simplify the Ingress step for both combined and separated [Ingress](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup/).
Adding:
- `KEYCLOAK_PROXY_ADDRESS_FORWARDING` to simplify the Ingress setup.
- `keycloak.ingress` for visibility.

chore: add keycloak defaults

---

charts/camunda-platform/templates/NOTES.txt

#380 
This PR checks if any of the apps are enabled to display the `Connecting to Web apps` message in the release notes

check if any app is enabled to display template message

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/charts/identity/templates/constraints.tpl
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/ingress.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/ingress_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/values.yaml

Keycloak has 2 patterns, private (container-to-container auth) and public (end-user auth).
This change allows:
- Customizing the Identity Keycloak chart URL (which deprecates the host customization via "global.identity.keycloak.fullname").
- Using the existing Keycloak with more fine-grain vars.
- Using the existing Keycloak in the external access via Ingress.
Use the existing Keycloak vars in the combined ingress.
Added a test to ensure the Keycloak access worked as expected.
Also fix a bug related to #458 

refactor: allow more flexible keycloak config

---

.github/workflows/go-it-os.yaml
.github/workflows/go-it.yaml
charts/camunda-platform/test/integration/setup.go

Using a clear namespaces name for integration tests so it's easy to debug failed tests.
Set the integration test namespace using pr num, short commit hash, and a random number.

chore(ci): use clear namespace name for integration tests

---

charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/charts/identity/templates/keycloak-service.yaml
charts/camunda-platform/templates/ingress.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/identity/service_test.go
charts/camunda-platform/test/ingress_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go

If the Keycloak custom or external service is in another space, the Ingress will fail because the host is used instead of the service name. And since the Ingress is actually namespaced, so we need to setup a service with `ExternalName` type to deal with this use case.
A new service for custom Keycloak access has been added with the type `ExternalName` which will be used as a bridge to Keycloak. Which also used to customize Keycloak URL options.

fix: use service for keycloak instead of host

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/ingress.yaml
charts/camunda-platform/test/ingress_test.go
charts/camunda-platform/values.yaml

It fixes #462
Also, it partially fixes #465, which allows setting the context path so the user can use Keycloak v19.x.x even Camunda Platform charts are not using the newer version yet. 
Allow setting context path for Keycloak, which should work with `v16.x.x` and `v19.x.x`.

feat: support custom keycloak context path

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/curator-cronjob.yaml
charts/camunda-platform/test/global_deployment_test.go
charts/camunda-platform/test/golden/curator-configmap.golden.yaml
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go
charts/camunda-platform/test/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/zeebe/statefulset_test.go
charts/camunda-platform/values.yaml

Currently, it's hard to just change the registry for all components, and it needs to override each component image repo name.
Support customizing container image registry for all components globally and also allow to set registry per component.

feat: support customizing container image registry

---

.github/workflows/chart-release.yaml
.github/workflows/chart-update-image-tag.yaml
.github/workflows/chart-validate.yaml
.github/workflows/go-it-os.yaml
.github/workflows/go-it.yaml
.github/workflows/go.yml
CONTRIBUTING.md
Makefile
RELEASE.md
charts/camunda-platform/README.md

Currently, make targes don't follow the same pattern also, there are target names too short of understanding what they are doing without digging into the Make file.
Tidy up and unify make targets.

chore: unify make targets

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/README.md
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/curator-cronjob.yaml
charts/camunda-platform/test/golden/curator-configmap.golden.yaml
charts/camunda-platform/test/golden/goldenfiles.go
charts/camunda-platform/test/golden/keycloak-statefulset.golden.yaml
charts/camunda-platform/test/ingress_test.go
charts/camunda-platform/test/keycloak_statefulset_test.go
charts/camunda-platform/values.yaml

Fixes: #448
Copy the login page theme from Identity to Keycloak.
The implementation ensures that the Identity image version is the same as in the Identity deployment and the theme to Keycloak.

feat: use identity theme in keycloak login page

---

charts/camunda-platform/README.md
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/curator-cronjob.yaml
charts/camunda-platform/values.yaml

Simplify the `camundaPlatform.image` template by applying SOLID principles for better readability and maintainability.
So instead of having a single template that handles 2 cases, now we have 2 templates, an abstraction that works with any input and an implementation that works with known paths like `.Values.global.image` and `.Values.image`.

refactor(internal): simplify camundaPlatform.image template

---

.github/workflows/test-integration.yaml
Makefile
charts/camunda-platform/test/integration/integration_suite.go
charts/camunda-platform/test/integration/integration_test.go
charts/camunda-platform/test/integration/openshift_test.go
charts/camunda-platform/test/integration/setup.go
go.mod
go.sum

Fixes: #395
- **Tests**: Fix the retry issue where the Pods' names were used, and the test fails if the pods were removed afterward (using labels instead).
- **Tests**: Impelment `waitUntilPodAvailable` that supports backoff retry instead of [terratest/k8s/WaitUntilPodAvailable](https://pkg.go.dev/github.com/gruntwork-io/terratest@v0.40.3/modules/k8s#WaitUntilPodAvailable) which was humming the cluster with a fixed retry (also it makes a lot of noise in the logs).
- **Tests**: By default, delete the test namespace unless explicitly it needs to be kept.
- **CI**: Ensure the test namespace is deleted even if the CI job is canceled.  
- **CI**: Use the distro team GKE cluster for integration tests.
- **CI**: Fix wrong match in the matrix where `-testify.m` matches regex not fixed name.
These …

ci: enhance k8s/gke integration tests

---

charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/test/optimize/golden/deployment.golden.yaml

-
The environment variable `CAMUNDA_OPTIMIZE_API_JWTSETURI` should actually be `SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI`

chore(optimize): correct spring uri env var name

---

charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/test/identity/deployment_test.go
charts/camunda-platform/test/operate/deployment_test.go
charts/camunda-platform/test/optimize/deployment_test.go
charts/camunda-platform/test/tasklist/deployment_test.go

Fixes: SUPPORT-15345
Use the use external Keycloak host directly in the Keycloak URL and only use the ExternalName service in the Ingress, which could be customized later if needed.
Using the host directly avoids any need to deal with TLS certificates.

refactor: use external keycloak host directly

---

Makefile
charts/camunda-platform/charts/identity/Chart.yaml

Fixes: #511
Use the Camunda Helm repo index instead of the Bitnami Helm repo index because Bitnami truncates the index every 6 months (more details bitnami/charts#10833)
The Camunda Helm repo index was updated by [1b3d2da](https://github.com/camunda/camunda-platform-helm/commit/1b3d2daa3a42eb32f9200eea112ba6111223aec8)

fix: use keycloak 7.1.6 from camunda repo index

---

.github/workflows/chart-update-image-tag.yaml

This PR fixes triggering "pull_request" workflows when the PR is created by the peter-evans/create-pull-request action.
That is because pull requests created by the action using the default GITHUB_TOKEN cannot trigger other workflows.
More details:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
Use GitHub app to auth instead ssh key.

fix(ci): use gh app to auth bot pr

---

.github/workflows/chart-release.yaml
.github/workflows/chart-validate.yaml
.github/workflows/test-integration-openshift.yaml
.github/workflows/test-integration.yaml

Set `concurrency=1` by setting `cancel-in-progress` to avoid running multiple integration tests on the K8s CI cluster.

chore(ci): set concurrency=1 by cancel-in-progress

---

charts/camunda-platform/charts/zeebe-gateway/templates/gateway-poddisruptionbudget.yaml
charts/camunda-platform/charts/zeebe/templates/poddisruptionbudget.yaml
charts/camunda-platform/templates/curator-cronjob.yaml
charts/camunda-platform/test/golden/curator-cronjob.golden.yaml
charts/camunda-platform/test/integration/it-values.yaml
charts/camunda-platform/test/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
charts/camunda-platform/test/zeebe-gateway/poddisruptionbudget_test.go
charts/camunda-platform/test/zeebe/golden/poddisruptionbudget.golden.yaml
charts/camunda-platform/test/zeebe/poddisruptionbudget_test.go

https://github.com/camunda/camunda-platform-helm/issues/498
Trying to fix outdated API-versions in:
- `PodDisruptionBudgets` from `policy/v1beta1` to `policy/v1`
-  `CronJobs` from `policy/v1beta1` to `policy/v1`

Kubernetes API: upgrade from policy/v1beta1 to policy/v1

---

.github/workflows/test-integration-kubernetes.yaml

Test Camunda Platform 8 Helm chart with Keycloak v19 in Venom pipeline.

chore(ci): test keycloak v19 with venom

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/identity/templates/service.yaml
charts/camunda-platform/test/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/identity/golden/service.golden.yaml
charts/camunda-platform/values.yaml
test/integration/venom/preflight/testsuites/preflight.yaml

Follow up on #504
Expose the Identity metrics port, which's used in the health checks.

feat: expose identity metrics port

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/web-modeler/templates/deployment-restapi.yaml
charts/camunda-platform/charts/web-modeler/templates/deployment-webapp.yaml
charts/camunda-platform/test/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/web-modeler/deployment_webapp_test.go
charts/camunda-platform/values.yaml

https://github.com/camunda/web-modeler/issues/3716
Add support for volume mounts for the Web Modeler's `restapi` and `webapp` components. For the `websockets` component, there's no use case for volumes.

feat(web-modeler): add support for volume mounts

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/web-modeler/templates/deployment-restapi.yaml
charts/camunda-platform/charts/web-modeler/templates/deployment-webapp.yaml
charts/camunda-platform/charts/web-modeler/templates/deployment-websockets.yaml
charts/camunda-platform/test/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/web-modeler/deployment_test.go
charts/camunda-platform/test/web-modeler/deployment_webapp_test.go
charts/camunda-platform/test/web-modeler/deployment_websockets_test.go
charts/camunda-platform/test/web-modeler/golden/deployment-webapp.golden.yaml
charts/camunda-platform/values.yaml
test/integration/scenarios/chart-with-web-modeler/values-web-modeler-enabled.yaml

Closes https://github.com/camunda/web-modeler/issues/3180.
Relates to #392.
Add support for startup, readiness, and liveness probes for the Web Modeler deployments.

feat(web-modeler): add support for startup/readiness/liveness probes

---

charts/camunda-platform/charts/web-modeler/templates/deployment-webapp.yaml
charts/camunda-platform/test/web-modeler/deployment_webapp_test.go
charts/camunda-platform/test/web-modeler/golden/deployment-webapp.golden.yaml

Closes https://github.com/camunda/web-modeler/issues/3876
Currently, some values are hardcoded (like the Keycloak realm), so that the Web Modeler wouldn't work with a custom Keycloak configuration. This PR fixes this problem.

fix(web-modeler): pick up custom Keycloak config correctly

---

charts/camunda-platform/charts/web-modeler/templates/deployment-restapi.yaml
charts/camunda-platform/test/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/web-modeler/golden/configmap-shared.golden.yaml
charts/camunda-platform/test/web-modeler/golden/deployment-restapi.golden.yaml
charts/camunda-platform/test/web-modeler/golden/deployment-webapp.golden.yaml
charts/camunda-platform/test/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform/test/web-modeler/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/web-modeler/golden/ingress.golden.yaml
charts/camunda-platform/test/web-modeler/golden/secret-shared.golden.yaml
charts/camunda-platform/test/web-modeler/golden/service-restapi.golden.yaml
charts/camunda-platform/test/web-modeler/golden/service-webapp.golden.yaml
charts/camunda-platform/test/web-modeler/golden/service-websockets.golden.yaml
charts/camunda-platform/test/web-modeler/golden/serviceaccount.golden.yaml
charts/camunda-platform/values.yaml

Updates Web Modeler to the latest beta version.
- Version update to `0.6.0-beta`.
- Workaround for `RESTAPI_OAUTH2_TOKEN_ISSUER_BACKEND_URL` is removed. The problem with the default ports has been fixed in Web Modeler itself (see https://github.com/camunda/web-modeler/issues/3993).

chore(web-modeler): update to version 0.6.0-beta

---

charts/camunda-platform/README.md
charts/camunda-platform/templates/NOTES.txt
charts/camunda-platform/templates/connectors/_helpers.tpl
charts/camunda-platform/templates/connectors/deployment.yaml
charts/camunda-platform/templates/connectors/service.yaml
charts/camunda-platform/templates/connectors/serviceaccount.yaml
charts/camunda-platform/values.yaml
kind/camunda-platform-core-kind-values.yaml
test/integration/scenarios/chart-with-custom-values/values-custom.yaml
test/integration/scenarios/chart-with-web-modeler/values-web-modeler-enabled.yaml

Same as https://github.com/camunda/camunda-platform-helm/pull/501, but minimal version without security.
The following k8s configs work without helm charts:
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: connectors
spec:
selector:
matchLabels:
app: connectors
template:
metadata:
labels:
app: connectors
spec:
containers:
- name: connectors
image: camunda/connectors-bundle:0.16.0
imagePullPolicy: IfNotPresent
resources:
limits:
memory: "1024Mi"
cpu: "500m"
ports:
- containerPort: 8080
env:
- name: ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS
value: 127.0.0.1:26500
- name: ZEEBE_CLIENT_SECURITY_PLAINTEXT
value: "true"
- name: CAMUNDA_CONNECTOR_POLLING_ENABLED
value: "false"
- name: CAMUNDA_CONNECTOR_WEBHOOK_ENABLED
value: "false"
- name: SPRING_MAIN_WEB-APPLICATION-TYPE
value: none
```
--- …

[Helm Charts] Connectors MVP - without keycloak

---

charts/camunda-platform/README.md
charts/camunda-platform/test/integration/scenarios/chart-with-web-modeler/values-web-modeler-enabled.yaml
charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml
charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/camunda-platform/values.yaml

Enable `readinessProbe` for all components which is the default for the next release, Camunda Platform 8.2. 

refactor: enable readinessProbe by default for all components

---

charts/camunda-platform/README.md

With the 8.2 release, Web Modeler will no longer be "beta".
Closes https://github.com/camunda/web-modeler/issues/4308.
Remove the warning about the beta status of Web Modeler from the README file.

chore(docs): remove beta status of Web Modeler

---

charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml

https://github.com/camunda/operate/issues/4336
Adding new `CAMUNDA_OPERATE_IDENTITY_REDIRECT_ROOT_URL`  that will be consumed by [operate](https://github.com/camunda/operate) application and used as a redirect host value for identity.

fix: add `CAMUNDA_OPERATE_IDENTITY_REDIRECT_ROOT_URL` var

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/connectors/deployment.yaml
charts/camunda-platform/templates/ingress.yaml
charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform/test/unit/connectors/deployment_test.go
charts/camunda-platform/test/unit/identity/deployment_test.go
charts/camunda-platform/test/unit/operate/deployment_test.go
charts/camunda-platform/test/unit/optimize/deployment_test.go
charts/camunda-platform/test/unit/tasklist/deployment_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go
charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/unit/zeebe/statefulset_test.go

#628
Add the `contextPath` to startup/readiness/liveness probes and add a unit test for that.

fix: add contextPath to startup/readiness/liveness probes

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform/test/unit/identity/deployment_test.go
charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go
charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml

Follow-up for: #629
Add contextPath to components URL that will fix the failing readiness when contextPath is enabled

fix(follow-up): add contextPath to startup/readiness/liveness probes

---

charts/camunda-platform/README.md
charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go
charts/camunda-platform/values.yaml

Enable users to configure the websockets app to log to an external file that is mounted into the pod.
Part of https://github.com/camunda/cawemo-laravel-websockets/issues/217.
Add support for volume mounts to the Web Modeler `websockets` deployment (similar to what is already supported for the `restapi` and `webapp` deployments).

feat(web-modeler): add support for volume mounts to websockets deployment

---

.github/workflows/test-integration-kubernetes.yaml
.github/workflows/test-integration-openshift.yaml
charts/camunda-platform/test/integration/scenarios/lib/testsuite-deploy-taskfile.yaml
charts/camunda-platform/test/integration/testsuites/base/job.yaml
charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml

Sometimes the CP8 deployment pods fail because we are using GKE spot instances which leads the test to fail.
Loop the Venom integration tests 3 times instead of rerunning the whole job from scratch.

test: introduce retry within the integration tests

---

charts/camunda-platform/README.md

This PR is related to support-16963. Users were confused about which environment variable is actually being used inside containers when they manually specify their own environment variables inside the values.yaml file, because when they run `kubectl describe pod/<podName>`, or `kubectl get -o yaml pod <podName>`, they see duplicate entries of the environment variables. Such as...
```
env:
- name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
value: "none"
- name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
value: "identity"
```
We learned that the latest declared entry is actually used inside the pod, and can be verified by using:
```
kubectl exec pod/<podName> -- env
```
This change includes some doc updates that will hopefully guide users when they configure `env` or debug the behavior …

docs: includes note about adding environment variables using env option

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/templates/NOTES.txt
charts/camunda-platform/templates/tests/integration-test-secret.yaml
charts/camunda-platform/test/unit/identity/deployment_test.go
charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

Fixes: #645
Should be merged before: #728
- Support disabling the creation of Identity firstUser. 
- Support using a custom secret for Identity firstUser. 

feat: customize Identity firstUser creation

---

charts/camunda-platform/README.md
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/test/unit/identity/deployment_test.go
charts/camunda-platform/values.yaml

Fixes: #727
Enables podLabels in Identity as already done for Operate or Tasklist

feat: add podLabels to Identity

---

charts/camunda-platform/README.md
charts/camunda-platform/test/unit/global_deployment_test.go
charts/camunda-platform/test/unit/golden/curator-cronjob.golden.yaml
charts/camunda-platform/values.yaml
charts/camunda-platform/values/values-latest.yaml
charts/camunda-platform/values/values-v8.1.yaml

Old bitnami curator image has been renamed to elasticsearch-curator-archived.
See related article I wrote https://medium.com/@zelldon91/looks-like-bitnami-elasticsearch-curator-is-gone-db1fa2260a97 and slack https://camunda.slack.com/archives/CSQ2E3BT4/p1687786110402069
Curator image can now be found here https://hub.docker.com/r/bitnami/elasticsearch-curator-archived/tags
Replaces the old/outdated image with the new one.

Use new curator image

---

charts/camunda-platform/templates/connectors/deployment.yaml
charts/camunda-platform/test/unit/connectors/deployment_test.go

Related to https://camunda.slack.com/archives/C02JLRNQQ05/p1687897649481629
closes #757 
By default, the Operate Client is enabled in the connectors-bundle. This PR will change the deployment to disable the operate client if the inbound connector is disabled.
This is not the only way to solve the original issue.
It would also be possible to configure the connection to Operate just like in the other configuration options.
It should be checked whether the Operate connector relies on the Operate client used.

refactor: in connector disable operate client if inbound is disabled

---

.github/workflows/test-integration-main.yaml

Part of: distribution/issues/87
Support multi OpenShift clusters and switch to the new CI cluster with OpenShift v4.13.

ci: support multi openshift clusters

---

kind/camunda-platform-core-kind-values.yaml

minimumMasterNodes is ignored in Elasticsearch versions >= 7 according to https://github.com/elastic/helm-charts/blob/main/elasticsearch/README.md#configuration
Remove minimumMasterNodes from camunda-platform-core-kind-values.yaml

fix(repo): remove minimumMasterNodes in KIND

---

charts/camunda-platform/test/unit/connectors/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/connectors/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/identity/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/identity/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/operate/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/operate/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/optimize/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/optimize/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress.golden.yaml
charts/camunda-platform/values.yaml

As @Ben-Sheppard  noted in #889 the default proxy-buffer-size can sometimes cause issues in our web components. This has led to some issues internally as well as a few support tickets and ask-distribution questions. @jonathanlukas @plungu  thank you for your efforts on those.
This PR adds a default proxy-buffer-size to our default annotations as an attempt to warn users that if they want to use their own ingress, hopefully they will make sure to set this annotation. And if they happen to use ingress-nginx, it'll hopefully work out of the box.

fix: added reasonable default proxy-buffer-size

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/templates/connectors/deployment.yaml
charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
charts/camunda-platform/test/unit/connectors/deployment_test.go
charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/identity/deployment_test.go
charts/camunda-platform/test/unit/operate/deployment_test.go
charts/camunda-platform/test/unit/optimize/deployment_test.go
charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/tasklist/deployment_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_test.go
charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/unit/zeebe/statefulset_test.go

Fixing the problem with command values that get rendered as one string. 
Fixes https://github.com/camunda/camunda-platform-helm/issues/799.
Instead of plain value of the command value: with `toYaml` & `nindent` the correct array gets rendered in the resources.

fix: correct command value

---

.github/workflows/test-integration-main.yaml
charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade.yaml

Fixes: #913
Add a new job to test the upgrade in full setup to ensure that the Camunda chart is always upgradable.

ci: test chart upgrade by default in the ci pipeline

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/RELEASE-NOTES.md
charts/camunda-platform/charts/identity/Chart.yaml
charts/camunda-platform/charts/operate/Chart.yaml
charts/camunda-platform/charts/optimize/Chart.yaml
charts/camunda-platform/charts/tasklist/Chart.yaml
charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
charts/camunda-platform/charts/zeebe/Chart.yaml

Note:  v8.2.14 has been skipped in [camunda-platform](https://github.com/camunda/camunda-platform).

Release Camunda Platform Helm Chart v8.2.15

---

.github/workflows/test-integration-main.yaml
charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
charts/camunda-platform/test/integration/scenarios/chart-with-custom-values/Taskfile.yaml
charts/camunda-platform/test/integration/scenarios/chart-with-default-values/Taskfile.yaml
charts/camunda-platform/test/integration/scenarios/chart-with-web-modeler/Taskfile.yaml
charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade.yaml
charts/camunda-platform/test/integration/scenarios/vars/common.env
charts/camunda-platform/test/integration/scenarios/vars/openshift.env

Part of: #913
Use the use the latest released chart in the upgrade pipeline.

ci: use the latest released  chart in the upgrade

---

charts/camunda-platform/charts/identity/Chart.yaml
charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml
charts/camunda-platform/values.yaml

Closes #849 
This PR contains a couple of smaller changes (and one larger one!), these are:
1. Upgrade the base Keycloak chart to one that supports Keycloak 22.0.1 (in prep for 8.3)
2. Updates the defaulted Keycloak version from 19.0.3 -> 22.0.1
3. Sets the `keycloak.proxy` value to `edge` (this is required to allow the Keycloak UI to load
I have tested this locally the best I can, these tests cover mainly:
1. I can deploy a clean cluster with Keycloak 22, access applications, and deploy a model
2. I can upgrade a cluster from Keycloak 19 -> 22, access applications (no model deployment testing here)

feat: upgrade to ship Keycloak v22

---

charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform/values.yaml

closes #926 
Replace old deprecated Zeebe configs for disk usage with the new ones. The new config is documented in https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/disk-space/

fix: use new disk usage configs for zeebe

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/charts/operate/templates/deployment.yaml
charts/camunda-platform/charts/optimize/templates/deployment.yaml
charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform/templates/connectors/deployment.yaml
charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/test/unit/connectors/deployment_test.go
charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml
charts/camunda-platform/test/unit/identity/deployment_test.go
charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/operate/deployment_test.go
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/optimize/deployment_test.go
charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/tasklist/deployment_test.go
charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/web-modeler/deployment_test.go
charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform/test/unit/zeebe/statefulset_test.go
charts/camunda-platform/values.yaml

This change takes the read-only root filesystem changes from my values.yaml configuration and pushes them into the templates of the helm chart.
More work needs to be done on this PR, like setting the UID's to match the parent image. And testing.
[readonly_minimal.yaml.txt](https://github.com/camunda/camunda-platform-helm/files/12500753/readonly_minimal.yaml.txt)

feat(security): read-only root filesystems for all containers

---

charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/operate/deployment.yaml
charts/camunda-platform/templates/optimize/deployment.yaml
charts/camunda-platform/templates/tasklist/deployment.yaml
charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml

#961 
Depends on:
Configures the identity base url on the zeebe gateway needed for the gateway to retrieve authorized tenants.

fix: configure identity base url

---

charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/templates/_helpers.tpl
charts/camunda-platform/templates/connectors/deployment.yaml
charts/camunda-platform/templates/console/deployment.yaml
charts/camunda-platform/templates/operate/deployment.yaml
charts/camunda-platform/templates/optimize/deployment.yaml
charts/camunda-platform/templates/tasklist/deployment.yaml
charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
charts/camunda-platform/test/unit/connectors/deployment_test.go
charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml

Fixes: #978
Allow the Keycloak URL to be fully customizable to work with external KC with a different context path.
Use `CAMUNDA_OPERATE_CLIENT_KEYCLOAK-TOKEN-URL` var in Connectors to customize the KC URL since it's not possible to set the context using `CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL` and `CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM` (the context is hard coded in [camunda-operate-client-java](https://github.com/camunda-community-hub/camunda-operate-client-java/blob/fa38603174de3d5f18414d25386ccc5444cad52d/src/main/java/io/camunda/operate/auth/SelfManagedAuthentication.java#L71) used in Connectors code base).
Also, a couple of internal renaming for consistency.
**After opening the …

fix: use correct keycloak var for connectors

---

charts/camunda-platform/values.yaml
charts/camunda-platform/values/values-latest.yaml

In the newest values.yaml, for 8.3 we have elasticsearch image tag set to 8.7.1, but we only support 8.8.x
https://github.com/camunda/camunda-platform-helm/blob/9c31ca4c9948d858ed844ffaaa0f7f93990989c4/charts/camunda-platform/values.yaml#L2960
https://docs.camunda.io/docs/reference/supported-environments/#camunda-8-self-managed
update elastic search image to 8.8.2 (the most recent supported version)
I'm pretty sure I updated this everywhere, but please double check me.

update elastic image to 8.8.2

---

charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml
charts/camunda-platform/values/values-latest.yaml

Optimize now releases under the 8.3.x image tag rather than the 3.11.x image tag.  I believe they are using 3.11.1 for compatibility reasons for the time being, but I suspect they will want to drop support for the 3.11.x numbering scheme at some point.
This PR will change the optimize versions with 8.3.x for values.yaml and values-latest.yaml.  This change also configures renovate for camunda/optimize.

fix: optimize to use consistent versioning with other 8.3 components

---

charts/camunda-platform/templates/zeebe/statefulset.yaml

A recent change has broken pvcStorageClassName in 8.3.1 as the if clause is checking for storageClassName instead of pvcStorageClassName.

fix zeebe pvcStorageClassName 

---

charts/camunda-platform/templates/optimize/deployment.yaml

#953 and #1036
Previously optimize migration container couldnt use volume mounts defined for the optimize container. 
PR adds support to mount the extraVolumeMounts from optimize to the migration container.

refactor: add volume mounts for optimize migration init container

---

charts/camunda-platform/README.md
charts/camunda-platform/templates/zeebe/configmap.yaml
charts/camunda-platform/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
charts/camunda-platform/test/unit/zeebe/golden/configmap.golden.yaml

Fixes: #1011
Allow mounting Zeebe exporters dir as an extra volume:
```
zeebe:
...
extraVolumes
- name: exporters-zeebe
emptyDir: {}
extraVolumeMounts:
- name: exporters-zeebe
mountPath: /usr/local/zeebe/exporters
```

fix: allow existing zeebe exporters dir

---

charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

I found that the default log level of Operate was DEBUG which I consider way too verbose. This changes it to INFO.

improve(operate): set default log level to INFO

---

charts/camunda-platform/templates/tasklist/deployment.yaml
charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml

https://github.com/camunda/tasklist/issues/3894
Similar to https://github.com/camunda-cloud/camunda-operator/pull/2255
**Mount tasklist-configmap volume on a new path (required for replacement of jib maven plugin by Dockerfile))**
In Tasklist, we are aiming to replace [jib-maven-plugin](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin) that we use to build Docker images by plain Dockerfile
jib-maven-plugin comes with some predefined paths for the classpath (like `/app/resources/` ...)
for this reason the `tasklist-configmap-webapp` (containing application.yaml to be used in SaaS) was mounted on the container at this path
With Dockerfile, we use a generated sh script (similar to what Operate is using) as an entrypoint. It is using a different classpath (uses docker …

refactor: mount tasklist-configmap volume on a new path

---

charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml

The problem with our prometheus deployment is now resolved, and it should now be safe to re-enable the tests. For more details about what was wrong in our deployment, look here: https://github.com/camunda/distribution/pull/100
Related to https://github.com/camunda/camunda-platform-helm/issues/733
Just uncommenting a test that was previously disabled.

ci: re-enable service monitor tests

---

charts/camunda-platform/templates/camunda/constraints.tpl
charts/camunda-platform/test/unit/camunda/global_deployment_test.go

…ntity
closes https://github.com/camunda/camunda-platform-helm/issues/1103
> Optimize can only run in C8SM mode with Identity. So we need to exit installation early if Optimize is enabled and Identity is disabled.
Helm chart should not attempt installation if Optimize is enabled but Identity is disabled. This change will add an error message 
```
Error Optimize may only be used if Identity is enabled. Please set 'identity.enabled' to true or set 'optimize.enabled' to false
```
Example execution
```
helm template --values base-values.yaml \
--set zeebe-gateway.enabled=false \
--set optimize.enabled=true \
--set webModeler.enabled=false \
--set global.identity.auth.enabled=false \
--set identity.enabled=false charts/camunda-platform  \
--debug 
install.go:194: [debug] Original chart …
```

refactor: show error message for optimize requirements

---

charts/camunda-platform/charts/tasklist/templates/deployment.yaml
charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml

backports https://github.com/camunda/camunda-platform-helm/pull/1101 to 8.2

refactor: mount tasklist-configmap volume on a new path [Backport to 8.1] (#1101)

---

kind/camunda-platform-core-kind-values.yaml

closes #1148 
While the core values.yaml technically runs, most of the options do not actually exist with the new bitnami helm chart version (since we upgraded to elasticsearch 8).  This PR fixes that.
Functionally equivalent values.yaml to the old kind/core values.yaml .

chore: update kind values.yaml with new elasticsearch values

---

.github/workflows/chart-update-readme.yaml
.github/workflows/renovate-post-upgrade.yaml

updated names on github workflows to work with GH_APP_ID_DISTRO_CI 

chore: renamed secrets for github auth token

---

charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go
charts/camunda-platform/test/unit/web-modeler/golden/configmap-shared.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/secret-shared.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/service-restapi.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/service-webapp.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/service-websockets.golden.yaml
charts/camunda-platform/test/unit/web-modeler/golden/serviceaccount.golden.yaml
charts/camunda-platform/values.yaml

Relates to https://github.com/camunda/web-modeler/issues/7077
Removes some unused environment variables after Web Modeler implemented custom OIDC support and adjusts the naming to use the newer scheme.
**Note:** These changes are backwards compatible. Using the old environment variables still works with newer versions of Web Modeler.

chore(web-modeler): adjust env variables for OIDC configuration scheme

---

.github/workflows/add-to-project.yml

https://github.com/camunda/distribution/issues/161
replace PAT tokens with GH app tokens generated in GHA. 

chore: added GH app token in add-to-project workflow

---

charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform/values.yaml

When installing the platform via helm using local charts for unrelated reasons I noticed an issue with getting Web Modeler to use Microsoft as the auth provider. 
The Identity component for a first iteration will not have a UI when using something other than Keycloak, therefore the Identity component will not be created and currently leads to an error when resolving the `webModeler.identityBaseUrl` helper.
This PR includes some defensive logic to only set the Identity specific value for Web Modeler when required.

fix: resolve issues with web modeler deployment when using OIDC

---

charts/camunda-platform/templates/camunda/_helpers.tpl

Add zeebe broker to the info and fix identity and optimize port.
Related to: https://github.com/camunda/camunda-platform-helm/issues/1223

refactor(console): add zeebe broker to the release configmap

---

charts/camunda-platform/templates/zeebe/configmap.yaml

fixes #1247
a missing newline ;-)
I did the same change manually in an actual installation and the brokers started correctly.

fix(multi-region failback): add missing newline in start script

---

.github/workflows/dispatch-integration-backport.yaml
.github/workflows/dispatch-integration.yaml

This is to allow manually triggering the GHA integration test workflow without needing a PR. also helps with workflows that use pull_request instead of pull_request_target.

test: adds dispatch workflow to manually trigger a gha workflow

---

.github/workflows/dispatch-integration-backport.yaml
.github/workflows/dispatch-integration.yaml
.github/workflows/test-integration-main.yaml

Turns out openshift tests are failing because of username/passwords referencing secrets that don't exist.

test: fixes username / password for openshift tests

---

charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml

closes #1250 
Set the correct names for the Identity configuration environment variables so that they can be correctly picked up by the Zeebe Gateway.
* Replace `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL` with `CAMUNDA_IDENTITY_BASE_URL`.
* Replace `CAMUNDA_IDENTITY_ISSUERBACKENDURL` with `CAMUNDA_IDENTITY_ISSUER_BACKEND_URL`
* Update the `deployment.golden.yaml` with the corresponding env var changes.

fix(zeebe-gateway): set correct identity conf env vars for zeebe

---

.github/workflows/test-integration-cleanup-template.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/1348
Added a new GHA workflow that allows to deletion of the Helm deployment namespace based on the GHA run ID which is already used as a label for the namespace.

ci: add test-integration-cleanup-template.yaml

---

charts/camunda-platform/VERSION-MATRIX.md

one-time update for version matrix
in response to #1357 
but it does not close this issue

fix: update version matrix after latest bugfix releases

---

charts/camunda-platform/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml

Openshift test are failing due to console being enabled.
Setting console to disabled. 

test: set console to false for openshift test

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml

Related to https://github.com/camunda/camunda-platform-helm/issues/1281
Updated deprecated `ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT` (contactPoint) with `ZEEBE_GATEWAY_CLUSTER_INITIALCONTACTPOINTS` (initicalContactPoints) in Zeebe Gateway.

fix: update to use initialContactPoints for Zeebe Gateway

---

charts/camunda-platform/templates/optimize/deployment.yaml

https://github.com/camunda/camunda-platform-helm/issues/1100
C7 error messages in C8 is pretty confusing.  After this PR, you'll at least get a C8 error message about Optimize not having an issuer url (in situations where you deploy with identity disabled, no oidc configuration, AND optimize enabled).
The `SPRING_ACTIVE_PROFILES` is not set to `ccsm` if identity is disabled. This has a consequence of optimize booting into C7 mode. The purpose of this PR is not to get optimize working with identity disabled, it's just to clear up confusion around a confusing error message and possibly prevent issues with persistent data in a situation where optimize booting into C7 mode tries to "migrate" the data backwards. …

fix: moves ccsm spring profile outside of conditional

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/RELEASE-NOTES.md
charts/camunda-platform/charts/identity/Chart.yaml

Release Camunda Platform Helm Chart v8.3.8

---

charts/camunda-platform/charts/identity/templates/deployment.yaml
charts/camunda-platform/values.yaml

After the merge of https://github.com/camunda-cloud/identity/pull/2632 the env vars need to be updated to reflect the improved method of mapping rule initialization in Identity.
In this PR we remove the `initialUserId` variable and introduce `initialClaimName` and `initialClaimValue`

chore: refactor initialUserId to be initialClaimName and initialClaimValue to match Identity code

---

.github/config/yamllint.yaml
charts/camunda-platform/templates/camunda/_helpers.tpl
charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml

Console has issues because of a change I made recently  in hopes of fixing a linting error :sadpanda:
This PR will undo that change.
in the console configmap, sometimes the url part will remove the preceding whitespace like this:
```
url:https://optimize.jlscode.com
```
instead of 
```
url: https://optimize.jlscode.com
```
And the reason we tried to remove that whitespace was because it threw a linting error.
Part of this PR is removing the trailing-whitespace linting rule since it'll fail.  
I considered doing some special logic in helm to include the whitespace conditionally, however, that would look uglier than just having the whitespace unnecessarily.

fix(console): whitespace issue in configmap

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/RELEASE-NOTES.md
charts/camunda-platform/charts/identity/Chart.yaml
charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml

Release Camunda Platform Helm Chart v8.3.10

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/README.md
charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

Task: https://github.com/camunda/distribution/issues/229
Upgrade Elasticsearch from 8.9 to 8.12 to have the latest ES app and latest chart.

refactor: upgrade elasticsearch from 8.9 to 8.12

---

charts/camunda-platform/templates/curator-cronjob.yaml
charts/camunda-platform/test/unit/golden/curator-cronjob.golden.yaml
charts/camunda-platform/values.yaml

Related to https://github.com/camunda/camunda-platform-helm/issues/1224 and https://github.com/camunda/camunda-platform-helm/issues/354
Adding the ability to define resources and limitations to the curator-cronjob for 8.2

feat: Add resource and limits to curator-cronjob for 8.2

---

charts/camunda-platform/templates/operate/configmap.yaml
charts/camunda-platform/templates/operate/deployment.yaml
charts/camunda-platform/templates/optimize/configmap.yaml
charts/camunda-platform/templates/optimize/deployment.yaml
charts/camunda-platform/templates/tasklist/configmap.yaml
charts/camunda-platform/templates/tasklist/deployment.yaml
charts/camunda-platform/templates/zeebe/configmap.yaml
charts/camunda-platform/templates/zeebe/statefulset.yaml
charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/configmap.golden.yaml
charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

epic: https://github.com/camunda/distribution/issues/179
related Issues:
-  Support use for external elasticsearch: https://github.com/camunda/distribution/issues/179
- Support use of amazon opensearch: https://github.com/camunda/distribution/issues/51
-  Product hube issue: https://github.com/camunda/product-hub/issues/1946
I am merging my external elasticsearch and opensearch changes into the overriding config PR.

external es and os changes

---

.github/workflows/test-integration-template.yaml
.github/workflows/test-integration.yaml

Delete the GitHub environment after the pipeline is done.

ci: delete github environment after the pipeline is done

---

charts/camunda-platform/templates/NOTES.txt
charts/camunda-platform/templates/camunda/_helpers.tpl
charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml

closes #1520 
References to `grpc://` protocol are replaced with `http://` or `https://`

fix: references to grpc:// protocol removed

---

.github/workflows/test-integration-template.yaml
.github/workflows/test-integration.yaml

We learned recently that integration tests were not getting ran due to necessary permissions not being applied on the github actions job:
https://github.com/camunda/camunda-platform-helm/actions/runs/8543837528/workflow
> The workflow is not valid. .github/workflows/test-integration.yaml (Line: 18, Col: 3): Error calling workflow 'camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@0170911a741cdfddf3a814a98d0631215159c8cc'. The nested job 'clean' is requesting 'deployments: write', but is only allowed 'deployments: none'.
PR that dropped the permission
https://github.com/camunda/camunda-platform-helm/pull/1523

fix: re-adds necessary permissions GH deployments: write

---

.github/workflows/test-integration-template.yaml
charts/camunda-platform/templates/camunda/_helpers.tpl
charts/camunda-platform/templates/camunda/constraints.tpl
charts/camunda-platform/templates/connectors/_helpers.tpl
charts/camunda-platform/templates/console/_helpers.tpl
charts/camunda-platform/templates/identity/constraints.tpl
charts/camunda-platform/templates/web-modeler/constraints.tpl
charts/camunda-platform/templates/zeebe-gateway/constraints.tpl
charts/camunda-platform/templates/zeebe/z_compatibility_helpers.tpl

Task: https://github.com/camunda/distribution/issues/232
Ensure that 8.5 keys refactoring is backward compatible also disable the force check for the refactored keys for the 8.6 cycle.
**Note:** There are 2 areas that are not related to `keys` refactoring that should be migrated manually by the user before the upgrade process:
* Identity label as shown here: https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/upgrade/#identity
* Keycloak default values should be reviewed if the user makes a copy of the whole values file instead of relying on the default values (which is a common practice I saw many of our customers do), we have no control over this since that change happened in the upstream Keyloak chart and must to be done anyway.
Please make sure to follow …

refactor(follow-up): ensure that 8.5 keys refactoring is backward compatible

---

charts/camunda-platform/templates/zeebe/z_compatibility_helpers.tpl
charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
charts/camunda-platform/test/unit/console/golden/ingress-all-enabled.golden.yaml
charts/camunda-platform/test/unit/console/golden/ingress.golden.yaml
charts/camunda-platform/test/unit/console/golden/service.golden.yaml
charts/camunda-platform/test/unit/console/golden/serviceaccount.golden.yaml

https://github.com/camunda/camunda-platform-helm/issues/1633
Anyone with an older version of helm cli are encountering errors during installation. 
`Error: INSTALLATION FAILED: template: camunda-platform/templates/zeebe/z_compatibility_helpers.tpl:68:52: executing "camunda-platform/templates/zeebe/z_compatibility_helpers.tpl" at <eq .Values.global.elasticsearch.url nil>: error calling eq: uncomparable type map[string]interface {}: map[host:{{ .Release.Name }}-elasticsearch port:9200 protocol:http]`

fix: mismatch errors during installation z_compatibility_helpers.tpl

---

charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml

Dynamically sets the heap space size of Web Modeler's `restapi` instead of using an absolute value. Mirrors the changes made in https://github.com/camunda/web-modeler/pull/8952.

chore(web-modeler): dynamically set heap space size

---

.github/workflows/chart-release-snapshot.yaml
README.md
charts/camunda-platform/README.md
docs/readme.md
docs/release.md

Fixes: https://github.com/camunda/camunda-platform-helm/issues/1683
Release Camunda Helm chart snapshot to GitHub package registry as an OCI.

ci: release chart snapshot from main branch

---

charts/camunda-platform/templates/console/deployment.yaml
charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
charts/camunda-platform/values.yaml

Related to https://github.com/camunda/camunda-platform-helm/issues/1625
KEYCLOAK_REALM is hard corded in the console deployment.yaml 
Added dynamic configuration via values.yaml

fix: keycloak realm in console component is hardcoded

---

charts/camunda-platform/templates/zeebe/configmap.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/1697
Set empty map in Zeebe config when exporters are disabled to avoid interpreting it as a string.

fix: set zeebe exporters empty map when disabled

---

charts/camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl

Fix: https://github.com/camunda/camunda-platform-helm/issues/1734
The old format of the key `global.elasticsearch.url` was a string that could be: `defined` (`url: xyz`), `empty` (`url: ""`), or `null` (`url:`) so using `not` and `empty` is redundant and it goes to the `else` clue.
In this PR the if condition is updated and else section is removed.

fix: handle type of es url correctly

---

charts/camunda-platform/Chart.yaml
charts/camunda-platform/RELEASE-NOTES.md
charts/camunda-platform/charts/identity/Chart.yaml

Release Camunda Platform Helm Chart v8.3.12

---

charts/camunda-platform/values.yaml

https://github.com/camunda/camunda-platform-helm/issues/1809
Remove warnings for zeebe and connectors. 

fix: remove empty string to get rid of warnings for zeebe and connectors

---

kind/camunda-platform-core-kind-values.yaml

This is a fix for the kind file. I am also disabling keycloak since identity is disabled.
Related: https://github.com/camunda/camunda-platform-helm/issues/1832

fix: kind values.yaml file disable keycloak

---

charts/camunda-platform/templates/identity/postgresql-secret.yaml
charts/camunda-platform/test/unit/identity/secret_test.go

In #1707 , I removed a postgresql secret because I thought the secret would be created by the postgresql helm chart.
This is true, but only for the scenario where `identityPostgresql.enabled` is true.  For situations where you use an externalDatabase, you need to have the postgresql secret because that secret is referenced from the `IDENTITY_DATABASE_PASSWORD` environment variable.
This PR also adds a unit test for the problem in #1707 to ensure that re-adding this secret does not re-add the issue that I previously fixed.
Related to 
closes https://github.com/camunda/camunda-platform-helm/issues/1846
The postgresql secret is re-added, the test I removed is re-added, and I created a new unit test to cover scenario related to #1707 
Please make sure to follow our [Contributing …

fix: re-added the postgresql secret

---

.github/actions/workflow-vars/action.yml

Avoid confusion about the chart version since we only change the version during the release process as the "version" field in "Chart.yaml" file doesn't reflect the changes since the latest release.

ci: use 0.0.0-ci-snapshot as a version for ci workflows

---

charts/camunda-platform/values.yaml

Related to: https://github.com/camunda/camunda-platform-helm/issues/1849
Replicating the same livenessProbe endpoint that is used in Saas since we are now using a non-existing endpoint.

fix: update livenessProbe endpoint of zeebe

---

charts/camunda-platform/templates/zeebe/configmap.yaml

Related support issue: https://github.com/camunda/camunda-platform-helm/issues/1863
A fix for the zeebe configmap when Elasticsearch is disabled and OpenSearch is enabled.

fix: Disabling Elasticsearch and enabling OpenSearch causes incorrect syntax in zeebe configmap

---

charts/camunda-platform/values.yaml

Backport of this [fix](https://github.com/camunda/camunda-platform-helm/pull/1858) to 8.4

update livenessProbe endpoint of zeebe

---

charts/camunda-platform/charts/identity/templates/_helpers.tpl
charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml

related: https://github.com/camunda/camunda-platform-helm/issues/1442
This fix is to backport the change made for identity so the pod won't fail on install.

fix: backport identity changes

---

.github/workflows/test-integration-cleanup-template.yaml

Related to: https://github.com/camunda/distribution/issues/216
Within the CI, instead of deleting the namespace immediately, we now wait 24 hours before deletion.

ci: delete namespace with a completed deployment only after 24 hours

---

.github/workflows/test-integration-template.yaml

Allow running Helm integration tests without using GitHub Secrets (see https://github.com/camunda/camunda/issues/18211 ) and instead is compatible with https://confluence.camunda.com/display/HAN/CI+Secrets+Self-Service

ci: allow using Vault instead of GitHub Secrets

---

charts/camunda-platform-8.2/templates/web-modeler/deployment-websockets.yaml
charts/camunda-platform-8.2/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform-8.3/templates/web-modeler/deployment-websockets.yaml
charts/camunda-platform-8.3/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform-8.4/templates/web-modeler/deployment-websockets.yaml
charts/camunda-platform-8.4/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform-latest/templates/web-modeler/deployment-websockets.yaml
charts/camunda-platform-latest/test/unit/web-modeler/golden/deployment-websockets.golden.yaml

Removes unnecessary environment variables after switching the underlying websockets library, see https://github.com/camunda/cawemo-laravel-websockets/issues/375
Merge only after Web Modeler's `8.6.0-alpha2`/`8.5.2`/`8.4.6`/ `8.3.8`/`8.2.15` releases.

chore(web-modeler): remove unnecessary environment variables

---

.github/workflows/chart-release-snapshot.yaml
.github/workflows/chart-release.yaml
charts/camunda-platform-latest/Chart.yaml
charts/camunda-platform-latest/RELEASE-NOTES.md
charts/camunda-platform-latest/values-latest.yaml
scripts/generate-version-matrix.sh
version-matrix/README.md
version-matrix/camunda-8.5/README.md

Release Camunda Platform Helm Chart v10.1.1

---

.github/actions/workflow-vars/action.yml
.github/workflows/dispatch-integration-backport.yaml
.github/workflows/dispatch-integration.yaml
.github/workflows/test-integration-template.yaml
.github/workflows/test-integration.yaml
.github/workflows/test-regression.yaml
charts/camunda-platform-latest/values.yaml
docs/gha-workflows.md

related: https://github.com/camunda/distribution/issues/216
The persistent flag is now being removed in favour of deployment-ttl
You can now modify how long a deployment lasts after the integration tests have ran. It takes advantage of the k8s-cleaner operator that is already present in both CI clusters.
Example deployment-ttl values:
360s: 360 seconds
10m: 10 minutes
24h: 24 hours
7d: 7 days
2w: 2 weeks

ci: mange integration tests clean-up via ttl

---

test/integration/testsuites/base/files/variables-default.yaml
test/integration/testsuites/base/files/variables-ingress-combined.yaml

Updating `preflightVars.baseURLs` used by integration tests with Tasklist and Operate management port `9600`
This makes this job passing https://github.com/camunda/camunda/actions/runs/9598610686/job/26470345249?pr=18780

ci: update preflightVars.baseURLs vars for Tasklist and Operate

---

README.md

Sometimes end users try to install Camunda from this GitHub repo which is not meant for that (the final Helm chart artifacts should be used).
Add a note about this GitHub repo.

chore: add a note about camunda helm github repo

---

.github/workflows/test-integration-template.yaml

The new inputs print is breaking this workflow https://github.com/camunda/camunda/actions/runs/9656735771/job/26637842094 . The workflow uses `vault-secret-mapping` input which is a [multiline input including pipes](https://github.com/camunda/camunda/blob/28d412a02ec7ead43961fd674889cae31838180e/.github/workflows/camunda-helm-integration.yml#L28-L32), so it does not properly work with `toJSON` method.

chore: fix workflow inputs print

---

.github/workflows/chart-release-snapshot.yaml
docs/release.md

Because now we use the directory-based structure and all chart versions in the same branch, we rename the snapshot docker tag to match the new style.

chore: use new tag name for snapshots

---

charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-preflight.yaml
charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-preflight.yaml
charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-preflight.yaml
charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-preflight.yaml
charts/camunda-platform-latest/test/integration/testsuites/vars/files/testsuite-preflight.yaml

In the tests, we used the health endpoint for readiness even though there is already a dedicated endpoint for readiness.
So updating the tests to use the correct probe in test. 

chore: update zeebe gatway readiness probe tests

---

.github/workflows/repo-pr-status.yaml

Add workflow to check PR checks status.
This check will be used in gh rules to determine that all checks passed.

chore: add workflow to check pr checks status

---

.github/renovate.json5

Task: https://github.com/camunda/distribution/issues/233
Add groups to Renovatebot config.
Currently, we have a lot of noise (e.g. PRs and Git commits) coming from Renovatebot because we don't group. 

chore: add groups to renovate config

---

.github/renovate.json5
charts/camunda-platform-8.2/values-latest.yaml
charts/camunda-platform-8.2/values.yaml
charts/camunda-platform-8.3/values-latest.yaml
charts/camunda-platform-8.3/values.yaml
charts/camunda-platform-8.4/values-latest.yaml
charts/camunda-platform-8.4/values.yaml
charts/camunda-platform-alpha/values-latest.yaml
charts/camunda-platform-alpha/values.yaml
charts/camunda-platform-latest/values-latest.yaml
charts/camunda-platform-latest/values.yaml
charts/web-modeler-postgresql/values.yaml

Task: https://github.com/camunda/distribution/issues/233
Update dep names to follow the same convention we have for other deps.

chore: update dep names

---

.github/workflows/pr-conventions.yaml

related: https://github.com/camunda/camunda-platform-helm/issues/1581
Enforcing PR conventions

ci: adding workflow for pr conventions

---

.github/actions/workflow-vars/action.yml
.github/workflows/test-integration-rosa.yaml

- Alerts are not triggered
- When performing test upgrade on main, the fetch command fails due to the current already on main (this error wasn't triggered before due to the fact that integration tests were always launched from PRs).
See
https://github.com/camunda/camunda-platform-helm/actions/runs/9802466140/job/27068549929
This fix implements the same logic as we have in
https://github.com/camunda/camunda-tf-eks-module/blob/85f9a6913e3a14c0c0ce966e9dc434762e1448b2/.github/workflows/tests.yml#L184

fix(ci): failure alerts are not triggered on ROSA schedule integration

---

.github/config/test-integration-matrix.yaml
.github/workflows/test-integration-template.yaml

The GHA expression substitution doesn't work as expected when loaded from a file (it was introduced in https://github.com/camunda/camunda-platform-helm/pull/2118)

chore: fix gha expressions substitution in ci workflow

---

.github/workflows/test-integration-rosa-template.yaml

pinned version didn't work with a behaviour change at RedHat.
RedHat changed the download server and the curl command didn't follow redirects.
Not what your Renovate schedule is, so I thought I would proactively create the PR to not have you run into OpenShift cluster creation issues.
Just digest updates from tf-rosa repo to not have the cluster creation fail for OpenShift tests.

chore: update rosa actions

---

charts/camunda-platform-8.2/charts/operate/templates/deployment.yaml
charts/camunda-platform-8.2/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform-8.3/templates/operate/deployment.yaml
charts/camunda-platform-8.3/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform-8.4/templates/operate/deployment.yaml
charts/camunda-platform-8.4/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform-alpha/templates/operate/deployment.yaml
charts/camunda-platform-alpha/test/unit/operate/deployment_test.go
charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
charts/camunda-platform-latest/templates/operate/deployment.yaml
charts/camunda-platform-latest/test/unit/operate/deployment_test.go
charts/camunda-platform-latest/test/unit/operate/golden/deployment.golden.yaml

related issue: https://github.com/camunda/camunda-platform-helm/issues/2142
I added a recreate strategy to all operate deployments, instead of rolling update. 

fix: added recreate strategy to all Operate deployments

---

charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
charts/camunda-platform-alpha/templates/tasklist/configmap.yaml
charts/camunda-platform-latest/templates/camunda/_helpers.tpl
charts/camunda-platform-latest/templates/tasklist/configmap.yaml

closes https://github.com/camunda/camunda-platform-helm/issues/2151 
closes https://github.com/camunda/tasklist/issues/4997
- Define a new template `camundaPlatform.zeebeGatewayRESTURL` that takes into account `.Values.zeebeGateway.contextPath`
- Use this template in Tasklist configMap to set `zeebe.restAddress` configuration

fix: changed restAddress in Tasklist with helper function

---

charts/camunda-platform-8.2/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
charts/camunda-platform-8.3/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml

closes #2161 
this PR disables console for integration tests for 8.2 and 8.3 charts

test: disable console on unsupported versions

---

charts/camunda-platform-latest/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform-latest/test/unit/web-modeler/deployment_restapi_test.go
charts/camunda-platform-latest/test/unit/web-modeler/golden/deployment-restapi.golden.yaml

Related to https://jira.camunda.com/browse/SUPPORT-21863
When configuring WebModeler.RestAPI to Postgres using IAM Role Base Authentication, it should not require environment variable SPRING_DATASOURCE_PASSWORD and its corresponding secret to be set
1. Do not specify any database password for webModeler.restapi.externalDatabase.password in values.yaml
2. Run helm install
3. webmodeler-restapi pod is unable to start up with a status of CreateContainerConfigError, with the following message: secret "<release_name>-web-modeler-restapi" not found
It enables configuration of WebModeler.RestAPI to Postgres using IAM Role Base Authentication without requiring password secret defined and environment variable from rendering into the Kubernetes resource
Please make sure to follow our [Contributing …

refactor: make web-modeler restapi database password secret optional

---

charts/camunda-platform-alpha/templates/camunda/constraints.tpl
charts/camunda-platform-alpha/test/unit/camunda/constraints_test.go
charts/camunda-platform-latest/templates/camunda/constraints.tpl
charts/camunda-platform-latest/test/unit/camunda/constraints_test.go

closes: https://github.com/camunda/camunda-platform-helm/issues/1755
I added a constraint to make sure that `zeebeGateway.ingress.rest.path` and `zeebeGateway.contextPath` have the same value when the rest endpoint is enabled for zeebe gateway.

fix: add constraint for contextPath and rest path to be the same for zeebe gateway

---

charts/camunda-platform-alpha/templates/operate/_helpers.tpl
charts/camunda-platform-latest/templates/operate/_helpers.tpl

Previously Operate resources used identity image map instead of the one from Operate. That causes that the deployment, and services are labeled with wrong version
Using the right map/object for the labeling.

fix: use correct image object

---

charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-latest/templates/zeebe/statefulset.yaml
charts/camunda-platform-latest/test/unit/zeebe/golden/statefulset.golden.yaml

closes #1754 
This change drops the namespace and svc from the initialcontactpoints and advertised host.
The idea behind this change is that since most kubernetes deployments will do this in their dns resolv.conf 
```
search default.svc.cluster.local svc.cluster.local cluster.local
``` 
That the first and second dns search will result in a failure since the namespace and svc will be duplicated.

fix: drop namespace from zeebe advertisedHost and initialContactPoints

---

charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
charts/camunda-platform-alpha/templates/camunda/constraints.tpl
charts/camunda-platform-alpha/templates/operate/deployment.yaml
charts/camunda-platform-alpha/templates/optimize/deployment.yaml
charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
charts/camunda-platform-latest/templates/camunda/_helpers.tpl
charts/camunda-platform-latest/templates/camunda/constraints.tpl
charts/camunda-platform-latest/templates/operate/deployment.yaml
charts/camunda-platform-latest/templates/optimize/deployment.yaml
charts/camunda-platform-latest/templates/tasklist/deployment.yaml
charts/camunda-platform-latest/templates/zeebe/statefulset.yaml

closes: https://github.com/camunda/camunda-platform-helm/issues/2133
I modified the if statement to allow the user to use existingSecret without needing to specify the password literal in OpenSearch.

fix: existingSecret for OpenSearch password can be used without defining password literal

---

charts/camunda-platform-alpha/templates/operate/configmap.yaml
charts/camunda-platform-alpha/templates/operate/deployment.yaml
charts/camunda-platform-alpha/templates/tasklist/configmap.yaml
charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
charts/camunda-platform-alpha/templates/zeebe-gateway/configmap.yaml
charts/camunda-platform-alpha/templates/zeebe-gateway/deployment.yaml
charts/camunda-platform-alpha/templates/zeebe/configmap.yaml
charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
charts/camunda-platform-alpha/test/unit/operate/golden/configmap.golden.yaml
charts/camunda-platform-alpha/test/unit/tasklist/golden/configmap.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap.golden.yaml

Configuring the new Database properties `camunda.database.*` used in v2 stack.
These properties are added to the configmaps used by:
- operate deployment
- tasklist deployment
- zeebe gateway deployment
- zeebe statefulset
The new properties use the same values as the existing ones (like `camunda.tasklist.elasticsearch` ...) . The old properties are meant to be deprecated and removed in future releases
Relates to https://github.com/camunda/camunda/issues/19076

feat: configure camunda database to be used by v2 API

---

charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
charts/camunda-platform-latest/templates/zeebe/statefulset.yaml
charts/camunda-platform-latest/test/unit/zeebe/golden/statefulset.golden.yaml

closes #2216 
This change will allow us to use short DNS names in zeebe for non-multiregion environments, while using the long DNS names for multiregion environments. This gives us the best of both worlds,
1. zeebe team will get fewer DNS misses
2. Multiregion deployments won't break due to the namespace being missing.

fix: dynamically set advertisedHosts based on multiregion

---

charts/camunda-platform-alpha/templates/operate/deployment.yaml
charts/camunda-platform-latest/templates/operate/deployment.yaml

Small fix that corrects the indentation of the operate migration envs when configuring those to e.g. overwrite the Elasticsearch URL.
Otherwise it will be interpreted as additional init container.
Example:
```
helm template camunda camunda/camunda-platform --set-string 'operate.migration.env[0].name=test' --set-string 'operate.migration.env[0].value=test'
```
will result in the following with `latest` and `alpha`:
```
initContainers:
- name: migration
image: camunda/operate:8.5.5
command: ['/bin/sh', '/usr/local/operate/bin/migrate']
securityContext:
allowPrivilegeEscalation: false
privileged: false
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 1001
seccompProfile:
type: RuntimeDefault
env:
- name: CAMUNDA_OPERATE_ELASTICSEARCH_HOST
value: "camunda-elasticsearch"
- name: …
```

fix: correctly intend operate migration envs

---

charts/camunda-platform-alpha/templates/zeebe/configmap.yaml
charts/camunda-platform-latest/templates/zeebe/configmap.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/2249
Add Zeebe OpenSearch retention to the app config file.

fix: add zeebe opensearch retention to app config file

---

.github/workflows/renovate-post-upgrade.yaml

Renovate doesn't update the README. By setting this var it will define `${CHANGED_CHARTS}`

ci: add Set Vars step to renovate config

---

charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml

closes: https://github.com/camunda/camunda-platform-helm/issues/2169
Disabling console in 8.4

fix: disable console in 8.4

---

charts/camunda-platform-8.4/charts/identity/templates/deployment.yaml
charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-core.yaml

I added a contextPath to 8.4 identity
and also removed console integration tests
related slack thread: https://camunda.slack.com/archives/CRQAL5A1M/p1725614202107509

fix: added contextpath to 8.4 identity

---

.github/renovate.json5

Renovate no longer automerges due to the recent PR which adds commits which auto-commits readme updates https://github.com/camunda/camunda-platform-helm/pull/2108
This commit introduces [gitIgnoredAuthors](https://docs.renovatebot.com/configuration-options/#gitignoredauthors) so that renovate will not flag PRs as non-auto-mergeable.

fix: add bot to ignoredAuthors for renovate to automerge again

---

charts/camunda-platform-8.3/README.md
charts/camunda-platform-8.4/README.md
charts/camunda-platform-alpha/README.md
charts/camunda-platform-latest/README.md

While browsing through the readme, I notice that the following URL 
`https://docs.camunda.io/docs/self-managed/setup/guides/local-kubernetes-cluster/` 
does not exits anymore I updated it to the current one 
`https://docs.camunda.io/docs/self-managed/setup/deploy/local/local-kubernetes-cluster/`

docs: update of outdated url in the local kubernetes  section

---

.github/renovate.json5

Fixes: https://github.com/camunda/camunda-platform-helm/issues/2344
Use Renovatebot's new secrets syntax.
Now, the encrypted secret is saved in the renovatebot cloud service.

chore: use Renovatebot new secrets syntax

---

charts/camunda-platform-8.2/Chart.yaml
charts/camunda-platform-8.2/charts/identity/Chart.yaml
charts/camunda-platform-8.3/Chart.yaml
charts/camunda-platform-8.3/charts/identity/Chart.yaml
charts/camunda-platform-8.4/Chart.yaml
charts/camunda-platform-8.4/charts/identity/Chart.yaml
charts/camunda-platform-alpha/Chart.yaml
charts/camunda-platform-latest/Chart.yaml
charts/web-modeler-postgresql/Chart.yaml
charts/web-modeler-postgresql/README.md
charts/web-modeler-postgresql/charts/common/README.md

Fixes errors show in the renovatebot dashboard https://github.com/camunda/camunda-platform-helm/issues/2314
Using bitnami oci chart repository to avoid redirections in the old repos (related to renovatebot and dependencies update).

refactor: using bitnami oci chart repository

---

charts/camunda-platform-latest/templates/operate/deployment.yaml

Fixing if statement in operate initContainer so the OpenSearch env vars for the password are included
closes: https://github.com/camunda/camunda-platform-helm/issues/2360
support-ticket: https://jira.camunda.com/browse/SUPPORT-23690?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D

fix: Include opensearch env vars in operate initContainer

---

charts/camunda-platform-8.4/charts/identity/templates/deployment.yaml
charts/camunda-platform-latest/templates/identity/deployment.yaml

closes: https://github.com/camunda/camunda-platform-helm/issues/2366
Adding a fix for 8.4, and 8.5 to change the existingSecretKey of the firstUser through the values.yaml

fix: identity firstuser existingsecretkey has no effect

---

charts/camunda-platform-alpha/templates/camunda/constraints.tpl

Related to https://github.com/camunda/camunda-platform-helm/issues/2286
`global.multiregion.installationType` is going away, so if anyone uses this option, they should get a notice that says:
> [camunda][warning]
> DEPRECATION NOTICE: Starting from appVersion 8.7, the Camunda Helm chart will no longer support the global.multiregion.installationType option. This is replaced with a new procudure for managing multi-region installations documented here:
> https://docs.camunda.io/docs/self-managed/operational-guides/multi-region/dual-region-operational-procedure/
> Please unset this option to remove the warning.
if the option is set, print the warning. 

fix: warning added to NOTES about installationType

---

charts/camunda-platform-alpha/templates/console/deployment.yaml

Closes #2373 
OIDC with Console is currently broken as there are still references to KEYCLOAK variables within console, and there are some hardcoded scopes / audiences that need to be set to their configured values.

fix: rearranged env vars necessary for oidc to work with console

---

charts/camunda-platform-alpha/templates/zeebe-gateway/configmap.yaml
charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap.golden.yaml

#2385 
This PR contains a change that supplies the baseUrl to the identity sdk. in previous versions, this was done for the sake of multitenancy so that other components could make a request to identity to ask "what resources does this user have access to?" but this is now a requirement in 8.6-alpha builds especially in situations where OIDC is enabled.  

fix: identity baseUrl supplied regardless of multitenancy

---

charts/camunda-platform-alpha/templates/identity/configmap.yaml
charts/camunda-platform-alpha/test/unit/identity/golden/configmap.golden.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/2339
Because the `Web Modeler Admin` role was missing so Identity wasn't able to assign any role to the Identity's first user.
The role was assigned to the user in PR no. https://github.com/camunda/camunda-platform-helm/pull/2326, but the role wasn't added.

fix: define Web Modeler Admin role in identity

---

.github/renovate.json5

Related to: https://github.com/camunda/camunda-platform-helm/issues/2404
Disable minor version update for `camunda-platform-latest` so the Camunda apps in the latest don't get a bump when the new minor version is released.

chore: disable minor version update for camunda-platform-latest

---

.github/renovate.json5

The recent renovate changes on main made it so that the 8.2 to 8.4 versions of the helm values.yaml will now upgrade to minor versions higher than what they're supposed to be. we got a number of PRs today such as 
https://github.com/camunda/camunda-platform-helm/pull/2419
How @drodriguez-305 and I tested this was with a forked camunda-platform-helm repository, with disabled private repository access, and then running the following command:
```
docker run -e LOG_LEVEL=debug -e RENOVATE_TOKEN=YOUR_PAT -it --rm -v $(pwd):/usr/src/app -w /usr/src/app renovate/renovate:38-full renovate jessesimpson36/camunda-platform-helm
```
Running it locally reduced our dependency on Mend which for some reason was very slow.  And I was able to see that the open PRs that was previously opened by renovate …

fix: disable renovate minor version bumps on 8.2-8.4

---

.github/renovate.json5

In renovate we encountered a problem where console and web modeler are doing minor upgrades unnecessarily. the cause this time was that the period does not match dashes in regexes in renovate.  This PR introduces dashes as part of the packageName query.
Renovate tweaks

fix: renovate web-modeler and console  no longer does faulty minor upgrades

---

.github/workflows/chart-release-snapshot.yaml
.github/workflows/chart-release.yaml
.github/workflows/chart-validate-template.yaml
.github/workflows/examples/test-helm-chart.yaml
.github/workflows/test-integration-rosa-template.yaml
.github/workflows/test-integration-template.yaml
.github/workflows/test-unit-template.yml
.github/workflows/test-version-latest.yaml
docs/gha-workflows.md

Related: #2404
Rename `camunda-platform-latest` internally, as we will have all released versions with the version suffix.

chore: rename camunda-platform-latest internally

---

charts/camunda-platform-8.6/values-latest.yaml

values-latest.yaml has not been updated renovate. the next time this changes renovate should update it automatically.
Correct `image.tags` for components

chore: update values-latest for 8.6

---

charts/camunda-platform-8.6/templates/zeebe-gateway/ingress-rest.yaml
charts/camunda-platform-8.6/test/unit/zeebe-gateway/golden/ingress-rest-all-enabled.golden.yaml
charts/camunda-platform-8.6/test/unit/zeebe-gateway/golden/ingress-rest.golden.yaml
charts/camunda-platform-alpha/templates/zeebe-gateway/ingress-rest.yaml
charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/ingress-rest-all-enabled.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/ingress-rest.golden.yaml

This [change](https://github.com/camunda/camunda-platform-helm/pull/2355/files#diff-51987be73eba2f7dd5f520408e9bd555a3526b38eb4a92814354911f73936683R22) introduced a bug where the ingress path was incorrectly set to include the readiness probe path `/actuator/health/readiness`. This resulted in the readiness probe path being exposed as an endpoint in the ingress, which inadvertently breaks the intended REST API access.
This PR reverts the previous change in ingress-rest.yaml to ensure that only the main service path (`ingress.rest.path`, e.g., `/zeebe`) is exposed via the ingress, without appending the readiness probe path.

fix: zeebe gateway incorrect rest ingress path 

---

charts/camunda-platform-alpha/templates/zeebe/configmap.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap.golden.yaml

For now we shouldn't set a prefix to indices, especially not the same as we use for the ES exporter.
Right now we don't support a global prefix everywhere, Operate will not able to find data.
This needs https://github.com/camunda/camunda/issues/23807
Removing the setting of a prefix for the Camunda Exporter

fix: do not set prefix

---

charts/camunda-platform-alpha/templates/core/statefulset.yaml

Related to: https://github.com/camunda/camunda-platform-helm/issues/2525
Disable core client secret en var if identity is disabled.

fix(core): disable core client secret if identity is disabled

---

charts/camunda-platform-alpha/templates/camunda/constraints.tpl
charts/camunda-platform-alpha/templates/core/statefulset.yaml
charts/camunda-platform-alpha/test/unit/core/configmap_test.go
charts/camunda-platform-alpha/values.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/2380
In Camunda 8.7 release, the Multi-Region setup doesn't need Helm config anymore via `global.multiregion.installationType`.

refactor: remove support for global.multiregion.installationType

---

.github/workflows/test-integration-template.yaml

Related to: https://github.com/camunda/distribution/issues/317
This PR addresses the issue where failed workflow runs in the integration test workflow did not have a mechanism to automatically retry. The lack of a retry mechanism caused delays when jobs failed due to transient errors, requiring manual intervention.
This PR introduces a retry mechanism to the test job in the GitHub Actions workflow. The key change is the addition of the rerun-failed-run action. The action is configured to trigger when the test job fails, and it will automatically retry the job up to a specified limit (2 attempts).
- Retry Logic: The retry limit is controlled using the `github.run_attempt` context, ensuring that retries happen only if the job has not yet exceeded the maximum retry count.
- Error Matching: …

fix: add rerun GitHub actions

---

.github/workflows/test-integration-template.yaml

related to: https://github.com/camunda/camunda-platform-helm/pull/2603
add github-workflow-rerun-enabled flag to enable/disable rerun github actions

ci: add github-workflow-rerun-enabled flag for rerun github actions

---

charts/camunda-platform-alpha/templates/core/configmap.yaml

When identity auth is disabled the only profile that's set is auth. This means it doesn't start the other components.

fix: add missing components when identity disabled.

---

charts/camunda-platform-8.6/templates/camunda/_helpers.tpl
charts/camunda-platform-alpha/templates/camunda/_helpers.tpl

Console configmap will not read the url if not set in the helpers when there is no ingress. This quickfix will resolve the default static localhost for webModeler. 

fix: add default webModler url when ingress is disabled

---

charts/camunda-platform-alpha/templates/core/configmap.yaml
charts/camunda-platform-alpha/test/unit/core/golden/configmap-authorizations.golden.yaml
charts/camunda-platform-alpha/test/unit/core/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-alpha/test/unit/core/golden/configmap.golden.yaml

With https://github.com/camunda/camunda/issues/25373, a single a parameter `camunda.security.authorizations.enabled` is used to enable authorizations. Backward compatibility will be maintained for the legacy parameters `camunda.operate.identity.resourcePermissionsEnabled` and `camunda.tasklist.identity.resourcePermissionsEnabled`

refactor: unify authorization configuration

---

.tool-versions

Gomplate repeatedly causes failures in the release chores CI in our release process due to v4 returning 404 Not Found from ASDF. v3 still lets you download the right version.
https://github.com/camunda/camunda-platform-helm/actions/runs/12197638945/job/34027709164?pr=2560
> /home/runner/.asdf/installs/gomplate/4.2.0/bin/gomplate: line 1: Not: command not found
make[1]: *** [Makefile:210: release.generate-version-matrix-unreleased] Error 127

fix: downgrade gomplate over Not Found errors in v4

---

charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml

In the context of [Manage and Run](https://github.com/camunda/product-hub/issues/1063)  we need to provide the `connectorsExternalURL` so that **Console** can consume this URL to create visuals.
- new `connectorsExternalURL` variable
- new **Connectors** Release template component

feat(connectors): add connectorsExternalURL and use it in a new Connectors Release Template component

---

charts/camunda-platform-8.3/values-latest.yaml
charts/camunda-platform-8.4/values-latest.yaml
charts/camunda-platform-8.5/values-latest.yaml
charts/camunda-platform-8.6/values-latest.yaml
charts/camunda-platform-alpha/values-latest.yaml

Bump tags in value-latest of console and operate, as they are not correct (see [HC version matrix](https://helm.camunda.io/camunda-platform/version-matrix/camunda-8.6/#helm-chart-1104)) 
It was reported [internally in slack](https://camunda.slack.com/archives/C03UR0V2R2M/p1733472707272259) & we have a [support ticket](https://camunda.slack.com/archives/C084RV21ZKJ).

chore(deps): correct value-latest of console and operate tag

---

charts/camunda-platform-8.5/templates/tasklist/configmap.yaml
charts/camunda-platform-8.5/test/unit/tasklist/golden/configmap.golden.yaml
charts/camunda-platform-8.6/templates/tasklist/configmap.yaml
charts/camunda-platform-8.6/test/unit/tasklist/golden/configmap.golden.yaml

closes #2523 
The user task access restrictions are a boolean, but are defined as a string. To fix this, the quote pipe has been removed.

fix: tasklist auth config

---

charts/camunda-platform-8.6/templates/camunda/ingress.yaml
charts/camunda-platform-8.6/templates/connectors/ingress.yaml
charts/camunda-platform-8.6/templates/console/ingress.yaml
charts/camunda-platform-8.6/templates/execution-identity/ingress.yaml
charts/camunda-platform-8.6/templates/identity/ingress.yaml
charts/camunda-platform-8.6/templates/operate/ingress.yaml
charts/camunda-platform-8.6/templates/optimize/ingress.yaml
charts/camunda-platform-8.6/templates/tasklist/ingress.yaml
charts/camunda-platform-8.6/templates/web-modeler/ingress.yaml
charts/camunda-platform-8.6/templates/zeebe-gateway/ingress-grpc.yaml
charts/camunda-platform-8.6/templates/zeebe-gateway/ingress-rest.yaml
charts/camunda-platform-alpha/templates/camunda/ingress-grpc.yaml
charts/camunda-platform-alpha/templates/camunda/ingress-http.yaml

Previous PR https://github.com/camunda/camunda-platform-helm/pull/2646 fixed the OpenShift route but for the GRPC an error regarding the class condition of grpc is causing this route not to be created.
This PR use the right className (https://github.com/camunda/camunda-platform-helm/pull/2678/files#diff-48ce3b026110eded528072962fcddbf15b3106b0d500843496a323d17def1ffe)

fix(zeebe-grpc-ingress): class check for openshift was not checked

---

charts/camunda-platform-8.6/templates/identity/configmap.yaml
charts/camunda-platform-8.6/test/unit/identity/golden/configmap.golden.yaml

related https://github.com/camunda/camunda/issues/25904
Using `IDENTITY_CLIENT_SECRET` envVar in case `CAMUNDA_IDENTITY_CLIENT_SECRET` not set.

fix: envVar-identity-client-secret-not-passed

---

charts/camunda-platform-8.5/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-8.5/templates/web-modeler/configmap-webapp.yaml
charts/camunda-platform-8.6/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-8.6/templates/web-modeler/configmap-webapp.yaml
charts/camunda-platform-alpha/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-alpha/templates/web-modeler/configmap-webapp.yaml

-- no issue exists --
Removes `pusher-app-id` and `pusher-app-key` from `configmap-restapi.yaml` and `configmap-webapp.yaml`. Both values are defined in `configmap-shared.yaml` and read from there by all three Web Modeler components.

refactor: remove unused web-modeler config map entries

---

charts/camunda-platform-alpha/templates/core/statefulset.yaml

We had the container `command` key duplicated in the core sts.

fix(alpha): move core sts command to correct location

---

charts/camunda-platform-alpha/templates/identity/configmap.yaml
charts/camunda-platform-alpha/values.schema.json

Task: https://github.com/camunda/camunda-platform-helm/issues/2525
Move the Identity admin client to presets as `environment` is initialized first, then the `presets.

fix(alpha): move identity admin client to presets

---

.github/workflows/chart-validate-template.yaml

closes #2735 
upgrades python version used by our linting / chart-testing scripts

chore: upgrade python version since 3.7 is no longer supported

---

charts/camunda-platform-8.5/templates/identity/configmap.yaml
charts/camunda-platform-8.6/templates/identity/configmap.yaml
charts/camunda-platform-alpha/templates/identity/configmap.yaml

closes: https://github.com/camunda/camunda-platform-helm/issues/2727
I am fixing the `client-secret` section in identity configmap. it should render when a string literal is provided and should not render when a k8s secret is provided.

fix: client-secret should only be present when string literal provided for oidc

---

charts/camunda-platform-8.3/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml

I made a mistake with https://github.com/camunda/camunda-platform-helm/pull/2742
where web modeler will not run due to improperly set up secret name in test values.yaml

fix: use integration-test-credentials for web modeler secret

---

.github/workflows/chart-release-candidate.yaml

fix: adding back override to release-candidate workflow

---

.github/workflows/prepare-chart-release-candidate.yaml

This workflow is for pre-release prep for the release-candidate images

ci: prepare chart release candidate

---

docs/architecture/multiregion.md

fix: Update multiregion.md

---

.github/renovate.json5

Our renovate configuration had a problem which was causing it to not process any packageRules for gomplate, because the packageName is actually `hairyhenderson/gomplate` and not just `gomplate`. Furthermore, the v has to be inside the named regex named "currentVersion" for it to be recognized as necessary for the new version.
Here's my evidence of it working:
https://github.com/jessesimpson36/renovate-gomplate-test/pull/3

fix: gomplate now upgrades with the v

---

charts/camunda-platform-8.6/templates/optimize/deployment.yaml
charts/camunda-platform-alpha/templates/optimize/deployment.yaml

Related to: https://github.com/camunda/camunda-platform-helm/issues/2709
modified the optimize deployment to render the optimized env vars in the migration init container. 
```
{{- with .Values.optimize.env }}
{{- tpl (toYaml .) $ | nindent 12 }}
{{- end }}
{{- with .Values.optimize.migration.env }}
{{- tpl (toYaml .) $ | nindent 12 }}
{{- end }}
```

fix: added support for optimize env vars for migration initcontainer

---

charts/camunda-platform-8.6/templates/identity/_helpers.tpl
charts/camunda-platform-alpha-8.8/templates/identity/_helpers.tpl
charts/camunda-platform-alpha-8.8/values.schema.json
charts/camunda-platform-alpha/templates/identity/_helpers.tpl

The helper does currently not respect the property `auth.secretKeys.userPasswordKey`, but references it indirectly as the defaults match.
If one changes the secret key, identity will not be able to resolve the password secret.
This is a simple adjustment that should not cause a breaking change.

fix: apply password key from subchart

---

charts/camunda-platform-alpha-8.8/templates/identity/configmap.yaml
charts/camunda-platform-alpha-8.8/test/unit/identity/golden/configmap.golden.yaml
charts/camunda-platform-alpha/templates/identity/deployment.yaml
charts/camunda-platform-alpha/test/unit/identity/golden/deployment.golden.yaml

closes #2888 
The zeebe role is now required by web modeler to deploy a model. This PR introduces this role for the first user for 8.7 and 8.8

fix: add zeebe role

---

.github/workflows/chart-release.yaml

Bring back private release of alphas.
Adding this change to release branch first. Then will copy changes to main.

ci: bring back private alpha release

---

.github/workflows/test-integration-template.yaml

related to https://github.com/camunda/camunda-platform-helm/issues/2953#issuecomment-2672469332
Use 8.7-snapshot for alpha upgrade test (instead of snapshot with is 8.8)

chore: use 8.7-snapshort in 8.7-alpha gha

---

charts/camunda-platform-alpha-8.8/templates/connectors/configmap.yaml
charts/camunda-platform-alpha-8.8/test/unit/connectors/golden/configmap.golden.yaml

It adds the config needed for connectors to authenticate via basic credentials in case the helm chart is run with basic `authentication.method: basic` see https://github.com/camunda/camunda/issues/28664.

feat: configure basic auth for connectors

---

charts/camunda-platform-alpha-8.8/Chart.yaml
charts/camunda-platform-alpha-8.8/values.schema.json
charts/camunda-platform-alpha/Chart.yaml

The pre-release annotation in artifacthub will avoid placing the latest label ontop of alpha chart builds. We are adding this into Chart.yaml so that it will propogate into the index.yaml in `gh-pages` during the chart-releaser step of our release process.
A new annotation for the alpha charts

docs: add prerelease annotation to alpha charts

---

charts/camunda-platform-8.3/templates/zeebe/configmap.yaml
charts/camunda-platform-8.4/templates/zeebe/configmap.yaml
charts/camunda-platform-8.5/templates/operate/configmap.yaml
charts/camunda-platform-8.5/templates/tasklist/configmap.yaml
charts/camunda-platform-8.5/templates/zeebe/configmap.yaml
charts/camunda-platform-8.5/test/unit/operate/golden/configmap.golden.yaml
charts/camunda-platform-8.6/templates/operate/configmap.yaml
charts/camunda-platform-8.6/templates/tasklist/configmap.yaml
charts/camunda-platform-8.6/templates/zeebe/configmap.yaml
charts/camunda-platform-8.6/test/unit/operate/golden/configmap.golden.yaml
charts/camunda-platform-alpha/templates/console/configmap.yaml
charts/camunda-platform-alpha/templates/operate/configmap.yaml
charts/camunda-platform-alpha/templates/tasklist/configmap.yaml
charts/camunda-platform-alpha/templates/zeebe/configmap.yaml
charts/camunda-platform-alpha/test/unit/operate/golden/configmap.golden.yaml

Task: https://github.com/camunda/camunda-platform-helm/issues/3070
Remove all extra spaces in the app configs so that they are rendered as YAML in ConfigMap instead of a quoted string.

fix: ensure app configs rendered correctly in ConfigMap

---

.github/workflows/chart-release-pr.yml

issue: https://github.com/camunda/camunda-platform-helm/issues/2918
We currently have 3 releases with the following name:
"chore(release): Camunda Platform Helm Chart 11.2.2 - Camunda 8.6"
In our release process, each release-candidate-8.* PR that opens triggers the release PR for ALL charts rather than just the chart that it was intended for.
This PR adds the "path" option into release-please which will restrict release-please to only release the artifacts on that subpath, and not others. the default is "."  I get the chart path from extracting the number from branch name "release-candidate-8.x"

ci: only generate releases for the helm chart being released by the candidate branch

---

.github/workflows/chart-release-pr.yml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/2918
Switch to release-please CLI to use the `--path` where it runs the release PR for a single version instead of all chart versions.
It wasn't possible to use the GHA due to this bug:
https://github.com/googleapis/release-please-action/issues/741

ci: run release-please for a single version

---

charts/camunda-platform-alpha-8.8/test/integration/testsuites/vars/files/testsuite-preflight.yaml
charts/camunda-platform-alpha-8.8/values.schema.json

In my previous PR #3151 , I missed some of the tests that should be disabled.
Disabled the venom tests for each disabled component in 8.8.

test: disable preflight 8.8 tests for disabled components

---

.github/workflows/test-version-alpha.yaml
charts/camunda-platform-alpha-8.8/test/unit/camunda/documentstore_configmap_test.go
charts/camunda-platform-alpha-8.8/values.schema.json
charts/camunda-platform-alpha/test/unit/camunda/documentstore_configmap_test.go
charts/camunda-platform-alpha/test/unit/connectors/configmap_test.go
charts/camunda-platform-alpha/test/unit/connectors/deployment_test.go
charts/camunda-platform-alpha/test/unit/connectors/types.go

The local option was removed and can therefore also be removed from the unit test.
related to https://github.com/camunda/camunda-platform-helm/pull/3013

fix: remove local storage unit test for doc handling

---

charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-core.yaml

This reverts commit 56528b98320e3a5823f9ff184a251401d110bc46.
reverting disabling of 8.7 test (aim was to disable 8.8) 

fix: revert "test: disable tests for disabled components (#3151)"

---

charts/camunda-platform-alpha/test/unit/camunda/documentstore_configmap_test.go

Trying to make the unit tests more generic and easier to read - I did the following refactorings:
1. Created 3 functions that could be used by all configmap unit tests actually --> they could be moved into a go package and reused in other configmap tests:
*  renderTemplate(): renders configmap template (used in all tests before)
* verifyConfigMap(): compares expected vs. set (used in all tests before)
* runTestCases(): runs all testCases (see point 2.)
2. Created a testCase structure instead of single test functions. This makes it very visible to see what values (in values.yaml) I set and which values (in this case envVars) I expect to set. The struct looks like:
2.1. name of the `testCase`
2.2. all `values` that we are setting in the values.yaml.
2.3 all `expected` values (in this case …

test: unit test document hanlding

---

charts/camunda-platform-8.2/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform-8.2/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform-8.3/templates/camunda/_helpers.tpl
charts/camunda-platform-8.3/templates/optimize/deployment.yaml
charts/camunda-platform-8.3/templates/web-modeler/_helpers.tpl
charts/camunda-platform-8.3/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform-8.3/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform-8.4/templates/camunda/_helpers.tpl
charts/camunda-platform-8.4/templates/web-modeler/_helpers.tpl
charts/camunda-platform-8.4/templates/web-modeler/deployment-restapi.yaml
charts/camunda-platform-8.4/templates/web-modeler/deployment-webapp.yaml
charts/camunda-platform-8.5/templates/camunda/_helpers.tpl
charts/camunda-platform-8.5/templates/web-modeler/_helpers.tpl
charts/camunda-platform-8.5/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-8.5/templates/web-modeler/configmap-webapp.yaml
charts/camunda-platform-8.6/templates/camunda/_helpers.tpl
charts/camunda-platform-8.6/templates/web-modeler/_helpers.tpl
charts/camunda-platform-8.6/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-8.6/templates/web-modeler/configmap-webapp.yaml
charts/camunda-platform-alpha-8.8/templates/camunda/_helpers.tpl
charts/camunda-platform-alpha-8.8/templates/web-modeler/_helpers.tpl
charts/camunda-platform-alpha-8.8/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-alpha-8.8/templates/web-modeler/configmap-webapp.yaml
charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
charts/camunda-platform-alpha/templates/web-modeler/_helpers.tpl
charts/camunda-platform-alpha/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-alpha/templates/web-modeler/configmap-webapp.yaml

closes: https://github.com/camunda/camunda-platform-helm/issues/3083

fix: changing helper function for identityURL

---

charts/camunda-platform-alpha/test/unit/console/configmap_test.go
charts/camunda-platform-alpha/test/unit/testhelpers/testhelpers.go

Now that we moved the generic testhelper function in its own package (https://github.com/camunda/camunda-platform-helm/pull/3170) we can leverage these functions also in other tests.
This PR refactors console configmap unit test to also use the new structure (clear values vs. expected) related to: https://github.com/camunda/camunda-platform-helm/pull/3142
With this the function `verifyConfigmap` in `testhelpers.go` is extended and also supports the application.yaml set configuration. Therefore I created a new function `getConfigMapFieldValue` to iterate over the keys and retrieving the value from the unmarshalled configMap.

test: support application.yaml config in generic unit test

---

scripts/verify-components-version.sh

fix #3095 
```sh
➜  camunda-platform-helm git:(fix/make-target-error) make release.verify-components-version
"camunda" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "kusionstack" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Unable to get an update from the "loft-sh" chart repository (https://charts.loft.sh):
Get "https://charts.loft.sh/index.yaml": dial tcp: lookup charts.loft.sh: no such host
...Successfully got an update from …
```

fix make verify-components-version error

---

charts/camunda-platform-8.5/test/unit/console/configmap_test.go
charts/camunda-platform-8.5/test/unit/testhelpers/testhelpers.go
charts/camunda-platform-8.6/test/unit/console/configmap_test.go
charts/camunda-platform-8.6/test/unit/testhelpers/testhelpers.go

Backports the refactoring of the unit test for consoles configmap back to 8.5 and 8.6, see [backport for 8.8](https://github.com/camunda/camunda-platform-helm/pull/3179)

ci: backport console confmap unit test to 8.5 and 8.6

---

charts/camunda-platform-alpha/templates/web-modeler/_helpers.tpl
charts/camunda-platform-alpha/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-alpha/test/unit/web-modeler/configmap_restapi_test.go
charts/camunda-platform-alpha/test/unit/web-modeler/types.go
charts/camunda-platform-alpha/values.yaml

Closes https://github.com/camunda/web-modeler/issues/13860
Configure the default cluster that is available in Web Modeler for deployments with the authentication type `CLIENT_CREDENTIALS` if Entra ID is used as identity provider.
This is necessary because the default authentication method – which would just pass on the user token to the cluster – does not work with Entra ID (see details in https://github.com/camunda/web-modeler/issues/13265).

fix: use client credentials authentication for default cluster in Web Modeler if Entra ID is used

---

.github/workflows/chart-release-pr.yml

Related to: https://github.com/camunda/team-distribution/issues/360
A tiny enhancement for the release workflow to show the release PR opened by the release-please workflow.
It makes it easier for the release manager to go directly to the release PR without any search.
How it looks like in the workflow summary:

cd: show release PR opened by release-please workflow

---

.github/config/release-please/release-please-config.json

Task: https://github.com/camunda/team-distribution/issues/462
Always bump patch version as the charts got their own version starting from camunda 8.4 release.

cd: use release-please always-bump-patch for 8.3

---

.github/workflows/test-integration-template.yaml

after switching our helm chart to using camunda-platform-8.8 in addition to camunda-platform-alpha via symlink, some users reported that the symlink is not working as intended when running "helm dependency update".
https://camunda.slack.com/archives/C03UR0V2R2M/p1743501024241029

fix: by default use 8.8 but without the symlink

---

charts/camunda-platform-8.8/values.yaml

renovate will not properly handle versions of format -alphaX-rcY

fix: bump core and connectors to 8.8.0-alpha3

---

version-matrix/README.md
version-matrix/camunda-8.6/README.md

The 11.3.0 release was missing an entry on helm.camunda.io, this PR adds it.

fix: regenerate 8.6 release matrix

---

.github/renovate.json5

We recently encountered an error where 8.7.0-alpha5 did not automatically upgrade to 8.7.0, and this is because the versioning was not properly set to semver, which would account for the -alpha being a prerelease notation rather than a compatibility notation such as if the image was named 8.7.0-alpine, denoting that the image is based on alpine.

fix: replace alpha tag with 8.8 in renovate

---

charts/camunda-platform-8.6/test/unit/console/deployment_test.go
charts/camunda-platform-8.6/test/unit/console/service_test.go

This PR refactors the unit tests in console on 8.6 into the new style

fix: refactor unit tests in 8.6/test/unit/console to new style

---

charts/camunda-platform-8.5/test/unit/camunda/configmap_test.go
charts/camunda-platform-8.5/test/unit/camunda/constraints_test.go
charts/camunda-platform-8.5/test/unit/camunda/global_deployment_test.go
charts/camunda-platform-8.5/test/unit/camunda/identitykeycloak_constraints_test.go
charts/camunda-platform-8.5/test/unit/camunda/ingress_test.go
charts/camunda-platform-8.5/test/unit/camunda/secret_test.go
charts/camunda-platform-8.5/test/unit/testhelpers/testhelpers.go

The only difference here between 8.6 and 8.5 is that there is not test on the Camunda license in 8.5

fix: backport 8.6 refactoring on test/unit/camunda to 8.5

---

charts/camunda-platform-8.4/test/unit/camunda/configmap_test.go
charts/camunda-platform-8.4/test/unit/camunda/global_deployment_test.go
charts/camunda-platform-8.4/test/unit/camunda/ingress_test.go
charts/camunda-platform-8.4/test/unit/camunda/secret_test.go
charts/camunda-platform-8.4/test/unit/testhelpers/testhelpers.go

- unit tests under camunda in 8.4 have been refactored

fix: task 448 backport and refactor Camunda unit test refactor from 8.6 to 8.4

---

charts/camunda-platform-8.3/test/unit/camunda/global_deployment_test.go
charts/camunda-platform-8.3/test/unit/camunda/ingress_test.go
charts/camunda-platform-8.3/test/unit/camunda/secret_test.go
charts/camunda-platform-8.3/test/unit/testhelpers/testhelpers.go

- unit tests under camunda in 8.3 have been refactored

fix: refactor camunda unit tests on 8.3 to the new style

---

charts/camunda-platform-8.6/test/unit/zeebe-gateway/configmap_test.go
charts/camunda-platform-8.6/test/unit/zeebe-gateway/deployment_test.go
charts/camunda-platform-8.6/test/unit/zeebe-gateway/poddisruptionbudget_test.go
charts/camunda-platform-8.6/test/unit/zeebe-gateway/service_test.go
charts/camunda-platform-8.6/test/unit/zeebe/statefulset_test.go

- Zeebe gateway unit tests have been refactored the new style

fix: refactor unit tests in zeebe-gateway to new style on 8.6

---

charts/camunda-platform-8.6/test/unit/web-modeler/configmap_restapi_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/configmap_shared_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/configmap_webapp_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/deployment_restapi_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/deployment_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/deployment_webapp_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/deployment_websockets_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/secret_restapi_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/secret_shared_test.go
charts/camunda-platform-8.6/test/unit/web-modeler/service_test.go

- Webmodeler unit tests in 8.6 have been refactored to the new style

fix: refactor unit tests in webmodeller of 8.6 to new style

---

charts/camunda-platform-8.5/test/unit/zeebe/configmap_test.go
charts/camunda-platform-8.5/test/unit/zeebe/poddisruptionbudget_test.go
charts/camunda-platform-8.5/test/unit/zeebe/service_test.go
charts/camunda-platform-8.5/test/unit/zeebe/statefulset_test.go

- refactored zeebe unit tests in 8.5 to the new style

fix: refactored unit tests to new style in zeebe 8.5

---

.github/config/yamllint.yaml
charts/camunda-platform-8.3/test/unit/camunda/elasticsearch_statefulset_test.go
charts/camunda-platform-8.3/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
charts/camunda-platform-8.4/test/unit/camunda/elasticsearch_statefulset_test.go
charts/camunda-platform-8.4/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
charts/camunda-platform-8.5/test/unit/camunda/elasticsearch_statefulset_test.go
charts/camunda-platform-8.5/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
charts/camunda-platform-8.6/Chart.yaml
charts/camunda-platform-8.6/test/unit/camunda/elasticsearch_statefulset_test.go
charts/camunda-platform-8.6/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
charts/camunda-platform-8.7/test/unit/camunda/elasticsearch_statefulset_test.go
charts/camunda-platform-8.7/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
charts/camunda-platform-8.8/test/unit/camunda/elasticsearch_statefulset_test.go
charts/camunda-platform-8.8/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml

related to https://github.com/camunda/team-distribution/issues/422
This PR introduces a new golden file for the Elasticsearch subchart in the Helm chart
- Introduced a new test golden file:  
`charts/camunda-platform-*/test/unit/camunda/elasticsearch_statefulset_test.go`
- The test uses the shared `TemplateGoldenTest` structure to render and validate Helm template output.
- Rendered template path:  
`charts/elasticsearch/templates/master/statefulset.yaml`
- Generated golden file output:  
`charts/camunda-platform-*/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml`
- Includes ignored lines for secrets and checksum annotations to avoid noise in diffs.
This test ensures consistent output from the Elasticsearch Helm template and establishes a baseline for future regression …

fix: add elasticsearch golden files

---

.github/workflows/test-chart-version-template.yaml
.github/workflows/test-chart-version.yaml
charts/camunda-platform-8.5/test/unit/console/deployment_test.go
charts/camunda-platform-8.5/test/unit/console/service_test.go

- console unit tests in 8.5 are refactored to the new style

fix: refactored unit tests to new style in console

---

.github/workflows/test-chart-version-template.yaml
.github/workflows/test-chart-version.yaml
charts/camunda-platform-8.5/test/unit/identity/configmap_test.go
charts/camunda-platform-8.5/test/unit/identity/deployment_test.go
charts/camunda-platform-8.5/test/unit/identity/secret_test.go
charts/camunda-platform-8.5/test/unit/identity/service_test.go

- refactored identity unit tests in 8.5 to the new style

fix: refactored unit tests to new style in identity 8.5

---

.github/workflows/test-chart-version-template.yaml
.github/workflows/test-chart-version.yaml
charts/camunda-platform-8.5/test/unit/operate/configmap_test.go
charts/camunda-platform-8.5/test/unit/operate/deployment_test.go
charts/camunda-platform-8.5/test/unit/operate/service_test.go

- refactored operate on 8.5 to the new unit test style

fix: refactored unit tests to new style in operate on 8.5

---

charts/camunda-platform-8.5/test/integration/testsuites/vars/files/variables-default.yaml
charts/camunda-platform-8.6/test/integration/testsuites/vars/files/variables-default.yaml
charts/camunda-platform-8.7/test/integration/testsuites/vars/files/variables-default.yaml

For < 8.5 the zeebe-gateway port for gRPC was properly defined in venom.
In >= 8.5 the port was on the management port (9600) instead of gRPC (26500), due to which for example Venom test will fail in non-domain setups.
Additionally it was defining `http://`, which breaks gRPC as well.
Looks like the tests in this repo always run with domain, so they would never catch it.
A simple fix of the right gRPC port for venom tests with no domain + removal of http

fix: grpc port of zeebe gateway for venom tests

---

charts/camunda-platform-8.8/templates/NOTES.txt
charts/camunda-platform-8.8/templates/camunda/_helpers.tpl
charts/camunda-platform-8.8/test/unit/console/golden/configmap.golden.yaml

fixes: https://github.com/camunda/distribution/issues/348
Zeebe Gateway is no more! Long live Camudna core!

fix: changed name of zeebegateway in console configmap

---

charts/camunda-platform-8.2/charts/zeebe/templates/statefulset.yaml
charts/camunda-platform-8.2/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-8.3/templates/zeebe/statefulset.yaml
charts/camunda-platform-8.3/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-8.4/templates/zeebe/statefulset.yaml
charts/camunda-platform-8.4/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-8.5/templates/zeebe/statefulset.yaml
charts/camunda-platform-8.5/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-8.6/templates/zeebe/statefulset.yaml
charts/camunda-platform-8.6/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-8.7/templates/zeebe/statefulset.yaml
charts/camunda-platform-8.7/test/unit/zeebe/golden/statefulset.golden.yaml
charts/camunda-platform-8.8/templates/core/statefulset.yaml
charts/camunda-platform-8.8/test/unit/core/golden/statefulset.golden.yaml
charts/web-modeler-postgresql/templates/primary/statefulset.yaml
charts/web-modeler-postgresql/templates/read/statefulset.yaml

#2214 
Improving the definition of PVCs.

fix: add apiVersion and kind to PersistentVolumeClaims

---

charts/camunda-platform-8.7/values.yaml
charts/camunda-platform-8.8/values.schema.json
charts/camunda-platform-8.8/values.yaml

This PR fixes an issue that an installation of the 12.0.0 chart gives this warning:
```
coalesce.go:301: warning: destination for camunda-platform.elasticsearch.extraConfig is a table. Ignoring non-table value (# Disable deprecation warnings - https://github.com/camunda/camunda/issues/26285
logger.org.elasticsearch.deprecation: "OFF"
)
```
As the `elasticsearch.extraConfig` should be a table, I would adjust this as shown.

fix: elasticsearch.extraConfig is a table

---

.github/workflows/test-chart-version-template.yaml
.github/workflows/test-chart-version.yaml

Fixed workflow input name as it represents the camunda version, not the chart version.
Also renamed `pr_number` to  `pr-number` for consistency.

ci: fix workflow input name of camunda version

---

charts/camunda-platform-8.8/go.mod
charts/camunda-platform-8.8/templates/web-modeler/_helpers.tpl
charts/camunda-platform-8.8/templates/web-modeler/configmap-restapi.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/configmap_restapi_test.go

Closes https://github.com/camunda/web-modeler/issues/13713
Adjusted the configuration of the default cluster for web-modeler depending on the auth configuration.

feat: add basic auth for web-modeler

---

scripts/generate-version-matrix.sh
scripts/list-chart-images.sh

In a recent PR , we renamed integration-test-ingress to integration-test-ingress-base but this was not updated in our scripts, resulting in some oddities in the release process.

fix: adjust scripts with change from name ingress to ingress-base

---

.github/workflows/chart-release.yaml

this failure: https://github.com/camunda/camunda-platform-helm/actions/runs/14930335394/job/41944667698?pr=3429
`Error: open charts/camunda-platform-[{"version":"8.4","case":"pr","scenarios":"base"}]/Chart.yaml: no such file or directory`
Only append the version to the directory name, not the entire list of objects

fix: adjust chart-release to reflect that matrix is no longer just a list of versions

---

.github/workflows/chart-release.yaml

fix: format of the matrix is {"include":[{"version":"8.4","case":"pr","scenarios":"base"}]}. update jq accordingly

fix: update jq command for new matrix json format

---

charts/camunda-platform-8.6/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl
charts/camunda-platform-8.7/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl

When elasticsearch is disabled and the chart is installed on OpenShift, the following error is given:
```
Error: template: camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl:86:30: executing "camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl" at <.Values.elasticsearch.commonLabels>: wrong type for value; expected map[string]interface {}; got interface {}
```
Here is the values.yaml:
```
global:
compatibility:
openshift:
adaptSecurityContext: force
elasticsearch:
enabled: false
```
I have added an extra if statement to check if elasticsearch is disabled.

fix: openshift elasticsearch disabled error

---

charts/camunda-platform-8.7/templates/connectors/configmap.yaml
charts/camunda-platform-8.7/templates/connectors/deployment.yaml

Related to https://github.com/camunda/camunda-platform-helm/issues/3462
Introduced by https://github.com/camunda/camunda-platform-helm/pull/2855
The gist of this bug is that an extra misplaced {{- end -}} key was placed sooner than it should be. This caused environments where identity was enabled would still try to render OAuth2 environment variables and would sometimes fail because of that.
Corrected a misplaced end key
closes https://github.com/camunda/camunda-platform-helm/issues/3462

fix: corrected a misplaced end key

---

charts/camunda-platform-8.8/templates/core/statefulset.yaml

closes: https://github.com/camunda/camunda-platform-helm/issues/3501
related supported ticket: https://jira.camunda.com/browse/SUPPORT-27120
The environment variables for defining the OpenSearch password is missing in 8.8.
I added them back in from the various components in 8.7.

fix:add missing env vars for opensearch password

---

README.md
charts/camunda-platform-8.5/values-latest.yaml
charts/camunda-platform-8.6/values-latest.yaml
charts/camunda-platform-8.7/values-latest.yaml
charts/camunda-platform-8.8/values-latest.yaml
scripts/generate-version-matrix.sh
scripts/templates/version-matrix/VERSION-MATRIX-RELEASE.md.tpl
version-matrix/camunda-8.4/README.md
version-matrix/camunda-8.5/README.md
version-matrix/camunda-8.6/README.md
version-matrix/camunda-8.7/README.md
version-matrix/camunda-8.8/README.md

Task: https://github.com/camunda/camunda-platform-helm/issues/3197
A couple of enhancements related to the release metadata.
- Added the version matrix badge in the main readme.
- Added the version matrix link to the release page.
- Updated unsupported versions in the version matrix script.
- Fixed an issue in rendering the Helm CLI version.
- Removed the old apps repo link https://github.com/camunda/camunda-platform and changed to https://github.com/camunda/camunda

chore: enhance release metadata

---

charts/camunda-platform-8.8/templates/camunda/ingress-http.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/3490
As Optimize will not be part of the Core group, it should be separated and the context path should be set only if Optimize is enabled.

fix: set context path only if optimize is enabled

---

.github/actions/workflow-vars/action.yml

When the QA test namespace hits Kubernetes’ 63-character limit, it can be cut off right after a hyphen—leaving the name ending in “–” and invalid under RFC 1123.
https://github.com/camunda/camunda-platform-helm/blob/47bd4f91407a550820af74cb32d1f5cf0f4ad08f/.github/actions/workflow-vars/action.yml#L67
Before applying the 63-character head truncation, we now strip any trailing hyphens from the generated `TEST_NAMESPACE`. This ensures the final namespace always ends in an alphanumeric character and passes Kubernetes’ naming requirements.

fix: remove any trailing hyphen for test_namespaces

---

scripts/generate-release-notes.sh

When a commit message contains leading or trailing ", or ends with (...), our YAML snippet ends up like:
`description: "Some message""`
`echo "      description: \"$(echo "$commit_message" | tr -d '"' | sed -E 's/[[:space:]]*\([^)]*\)$//')\""`
- `tr -d '"'` nukes every `"` in the raw commit message (so there are no stray leading/trailing quotes left).
- `sed -E 's/[[:space:]]*\([^)]*\)$//'` removes the trailing parentheses block.
- it wraps the cleaned result in one pair of quotes for valid YAML.

fix: stray-double-quote issue for descriptions in release notes script 

---

charts/camunda-platform-8.7/templates/camunda/constraints.tpl
charts/camunda-platform-8.7/templates/zeebe/statefulset.yaml
charts/camunda-platform-8.7/test/unit/zeebe/configmap_test.go
charts/camunda-platform-8.7/values.yaml

https://github.com/camunda/camunda-platform-helm/issues/2286
This change was accidentally undone by 
https://github.com/camunda/camunda-platform-helm/pull/2790
I took the diff from that PR and re-added it into this new PR. However, with one small difference. I did not re-add the error message when installationType is set explicitly by the user, as that would be a breaking change in a stable release of the Helm chart.  :cry: 
This change does not need to be re-applied to 8.8 since 8.8 was not copied from 8.6 in the way that 8.7 was created by copying it from 8.6.

fix: remove installationType for 8.7

---

.github/workflows/test-chart-version-nightly-template.yaml
charts/camunda-platform-8.6/test/integration/testsuites/vars/files/testsuite-preflight.yaml
charts/camunda-platform-8.8/test/integration/testsuites/vars/files/testsuite-preflight.yaml

Adding functionality to skip elasticsearch in preflight tests for 8.6 and 8.8. This is just a backport. This already exists for 8.7: https://github.com/camunda/camunda-platform-helm/pull/3516

ci: preflight test skip for elasticsearch 8.6 and 8.8

---

version-matrix/README.md
version-matrix/camunda-8.6/README.md

For some reason the version matrix didn't get generated properly.

fix: add 11.4.0 to version matrix. somehow was missed by ci

---

.github/renovate.json5

Renovate was having issues this morning due to the following error:
Failed job: https://developer.mend.io/github/camunda/camunda-platform-helm/-/job/4c3d9133-b524-4152-ba28-dc6cd73022b7
<details>
DEBUG: getDigest(https://{{ .Values.global.identity.image.registry }}, {{ .Values.global.identity.image.repository }}{{ if .Values.global.identity.image.digest }}, undefined)
DEBUG: getManifestResponse(https://{{ .Values.global.identity.image.registry }}, {{ .Values.global.identity.image.repository }}{{ if .Values.global.identity.image.digest }}, latest, head)
ERROR: Request Error: cannot parse url
{
"url": "https://{{ .Values.global.identity.image.registry }}/v2/"
"resolvedUrl": "https://{{ .Values.global.identity.image.registry }}/v2/"
}
WARN: Error obtaining docker token
{
"registryHost": …

fix: disable the keycloak initContainer package from renovate

---

charts/camunda-platform-8.8/README.md
charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-shared.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/golden/secret-shared.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/golden/serviceaccount.golden.yaml
charts/camunda-platform-8.8/values.schema.json
charts/camunda-platform-8.8/values.yaml

bump version in webModeler alpha to alpha5.1

fix: bump version in webModeler alpha to alpha5.1

---

charts/camunda-platform-8.7/templates/zeebe/configmap.yaml
charts/camunda-platform-8.7/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-8.7/test/unit/zeebe/golden/configmap.golden.yaml

Related to https://github.com/camunda/camunda-platform-helm/pull/3529
@jessesimpson36, @Langleu catched that we missed the removal of the following while removing the `global.multiregion.installationType`, see https://github.com/camunda/team-distribution/issues/408#issuecomment-2962838887

fix: cleanup multiregion installationtype

---

.github/actions/generate-chart-matrix/action.yml
.github/workflows/test-integration-template.yaml
charts/camunda-platform-8.4/templates/connectors/deployment.yaml
charts/camunda-platform-8.4/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform-8.5/templates/connectors/deployment.yaml
charts/camunda-platform-8.5/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform-8.6/templates/connectors/deployment.yaml
charts/camunda-platform-8.6/test/unit/camunda/golden/keycloak-statefulset.golden.yaml
charts/camunda-platform-8.6/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform-8.7/templates/connectors/deployment.yaml
charts/camunda-platform-8.7/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform-8.8/templates/connectors/deployment.yaml
charts/camunda-platform-8.8/test/unit/camunda/golden/keycloak-statefulset.golden.yaml
charts/camunda-platform-8.8/test/unit/connectors/golden/deployment.golden.yaml
charts/camunda-platform-8.8/test/unit/core/golden/poddisruptionbudget.golden.yaml

https://github.com/camunda/team-distribution/issues/491
Adds the scheme on probes to the templates for connectors. Defaults to http

fix: add scheme into templates for use by connectors

---

charts/camunda-platform-8.7/templates/connectors/configmap.yaml

Fixes: https://github.com/camunda/camunda-platform-helm/issues/3696
Related to:
- https://github.com/camunda/connectors/pull/4897
- https://github.com/camunda/camunda-platform-helm/pull/3679
Add the needed config to make the Connectors' inbound disabled mode work.
Without this option, Connectors will not start and log an error like:
```
Caused by: java.lang.IllegalStateException: Property 'operate.client.profile' is required
at io.camunda.operate.spring.OperateClientConfiguration.operateAuthentication(OperateClientConfiguration.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.lambda$instantiate$0(SimpleInstantiatio …
```

fix: connectors inbound disabled mode

---

.github/renovate.json5

fixes https://github.com/camunda/camunda-platform-helm/issues/3714
in .github/renovate.json5, we have a hard-coded maximum alpha number that we do not upgrade past. That number is alpha6, and we did not expect to exceed this number because that represents 6 months after a minor release (time for the next minor). But 8.8 is special in that we started releasing 8.8 alpha's prior to the official minor release of 8.7.
I propose that we up this value to alpha9. Historically, we did not have a maximum on the alpha number, but we found that application teams would sometimes publish debug images under camunda/camunda:8.8-alpha99. We wanted to avoid upgrades to such versions, which is also why adding a + to the regex isn't the best solution here.
Please make sure to follow our [Contributing …

fix: resume alpha upgrades by renovate post-alpha6

---

.github/workflows/test-chart-version-nightly.yaml

ci: remove pr trigger from nightly testing

---

.github/workflows/test-chart-version-nightly-template.yaml
.github/workflows/test-chart-version-template.yaml
charts/camunda-platform-8.8/Chart.yaml

A recent change introduced extra metadata into the namespace name https://github.com/camunda/camunda-platform-helm/pull/3675
One change that was made is that in the namespace name, the scenario is added to the namespace.
This part of the change is not okay because it further increases the likelihood of running into the 63 char limit and gives us the annoyingly confusing issue  where the namespace from the upgrade workflows conflict with the setup workflows described by this issue:
https://github.com/camunda/camunda-platform-helm/issues/3558
This PR will drop any extra metadata that #3675 introduced into the namespace name.

fix: remove the metadata in the namespace name

---

.github/workflows/test-chart-version-template.yaml
.github/workflows/test-chart-version.yaml
charts/camunda-platform-8.7/Chart.yaml

I was finding it difficult to work with the local cluster - KIND workflows because there's a lot of jobs that were marked as Cancelled and I didn't know why. The reason why is that they are duplicates, and the original job is running on a different line.
Therefore, I separated the KIND workflows from the matrix that splits up the different test scenarios
I moved where the "Local KIND" tests are being executed so that it would not be within the context of a scenario matrix. It would run its own matrix of just the version.
Tests did not pass for the local KIND workflows due to the following issue: …

fix: deduplicate scenario-independent jobs

---

charts/camunda-platform-8.8/templates/NOTES.txt
charts/camunda-platform-8.8/templates/camunda/ingress-grpc.yaml
charts/camunda-platform-8.8/templates/camunda/ingress-http.yaml

We have [introduced a new loadbalancing gateway service](https://github.com/camunda/camunda-platform-helm/pull/3791), and removed the gRPC/http endpoints from the headless service.
This breaks the ingress definitions, as they still use the old service.
* Update the http and gRPC ingress definitions to use the right service
* Update the chart notes to correctly direct users to the right service

fix: use gateway service in ingress's

---

.github/workflows/test-integration-runner.yaml
.github/workflows/test-integration-template.yaml

QA e2e tests failing
A previous commit did a refactoring where test-integration-template calls a runner integration test workflow. This commit introduced some bugs when connecting to an EKS cluster, as not all of the necessary options were proxied to the runner integration test workflow.
Proxied options to allow users to set the namespace prefix when using EKS cluster

fix: pass through options that were forgotten

---

.github/actions/workflow-vars/action.yml
.github/workflows/test-integration-runner.yaml
.github/workflows/test-integration-template.yaml
charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-mt.yaml
charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-rba.yaml
charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch.yaml
charts/camunda-platform-8.5/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-mt.yaml
charts/camunda-platform-8.5/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-rba.yaml
charts/camunda-platform-8.5/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch.yaml
charts/camunda-platform-8.6/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-mt.yaml
charts/camunda-platform-8.6/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-rba.yaml
charts/camunda-platform-8.6/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch.yaml
charts/camunda-platform-8.6/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-opensearch.yaml
charts/camunda-platform-8.7/test/e2e/package-lock.json
charts/camunda-platform-8.7/test/e2e/package.json
charts/camunda-platform-8.7/test/e2e/playwright.config.ts
charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-mt.yaml
charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-rba.yaml
charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch.yaml
charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-opensearch.yaml
charts/camunda-platform-8.7/test/integration/testsuites/package-lock.json
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-mt.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch-rba.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-elasticsearch.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-opensearch.yaml
scripts/base_playwright_script.sh
scripts/run-e2e-tests.sh
scripts/run-integration-tests.sh
test/integration/scenarios/chart-full-setup/Taskfile.yaml
test/integration/scenarios/lib/chart-upgrade-taskfile.yaml

values.yaml are mapping over from QA repo to this repo.

feat: enable values to be source from this repo rather than push from the QA repo

---

charts/camunda-platform-8.8/templates/identity/_helpers.tpl

I missed an else condition in the identity multitenancy options. If you recognize this one @aabouzaid , it's because theres a very similar block in the orchestration _helpers.tpl you told me to fix. 
Added else condition.

fix: missing else in identity multitenancy configuration

---

charts/camunda-platform-8.7/templates/camunda/configmap-documentstore.yaml
charts/camunda-platform-8.8/templates/common/configmap-documentstore.yaml

closes #3622 
This PR adds an optional env to the document store env configmap so that the aws region is mapped if aws is used.

fix: the region is mapped to the document store env

---

.github/workflows/test-integration-runner.yaml
charts/camunda-platform-8.2/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml
charts/camunda-platform-8.3/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml
charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml
charts/camunda-platform-8.5/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml
charts/camunda-platform-8.6/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml
charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-infra.yaml

in support of this refactor: https://github.com/camunda/infra-core/pull/10148
The TLS certificate secret will be renamed from `NAMESPACE_PREFIX-aws-camunda-cloud-tls` to `aws-camunda-cloud-tls`. 
We benefit from this because it means that our CI can run with the same secret name regardless  of whether we're ran from QA env or Distribution env. But we are still restricted to the urls we can access. So we are still on `*.distribution.aws.camunda.cloud` and QA is still on `*.qa.aws.camunda.cloud`.
renamed where the TLS certificates for AWS are located.

ci: rename prefix-certs namespace to prefix

---

charts/camunda-platform-8.8/test/integration/scenarios/pre-upgrade/delete-camunda-sts.sh

Related to: https://github.com/camunda/camunda-platform-helm/issues/3455
Since we renamed `core` to `orchestration` , the upgrade from alpha 7 will fail as the `matchLabels` key is immutable.
I also found that the ability to run scripts before the different flows (install, install in upgrade, upgrade) is not clear enough, and I will make it more visible in another PR.

ci: delete camunda sts before the upgrade

---

charts/camunda-platform-8.8/templates/orchestration/_helpers.tpl
charts/camunda-platform-8.8/templates/orchestration/configmap.yaml
charts/camunda-platform-8.8/test/unit/common/no_secondary_storage_test.go

Related to #34386 and most recent QA findings
This PR is fixing 2 bugs
- When starting in `noSecondaryStorage` mode we get prompted to disable `global.elasticsearch` and `global.opensearch` but when we do that the [database section](https://github.com/camunda/camunda-platform-helm/blob/376099b5ab30d8bac2d8706e0a7ce0cbb0a5c88f/charts/camunda-platform-8.8/templates/orchestration/configmap.yaml#L253) is disabled entirely which is not what we want. Instead we want to set `camunda.database.type=none`
- When persistent session is enabled, the cluster tries to read configs from the search layer (which isn't relevant since we don't use search layer in `noSecondaryStorage` mode). Also the persistent session is used for webapps (operate and tasklist) which we also disable
```
No qualifying bean
of …
```

fix: disable persistent sessions in noSecondaryStorage mode

---

version-matrix/README.md
version-matrix/camunda-8.6/README.md

The chart version matrix files depends on a chart actually being released. This adds the files after running `make   release.index` and `make release.released`

fix: add 11.9.0 matrix files

---

charts/camunda-platform-8.7/RELEASE-NOTES.md
version-matrix/camunda-8.7/README.md
version-matrix/camunda-8.7/version-matrix.json

When [releasing 12.5.0](https://github.com/camunda/camunda-platform-helm/pull/4005), the release matrix was not updated. This PR adds the updated version matrix with 12.5.0 included.
updated via running: `make release.generate-version-matrix-released`

chore: update version matrix for 12.5.0 release

---

version-matrix/README.md

I learned that I also needed to run `make release.generate-version-matrix-index` to update the readme of the version-matrix. Else the version-matrix is not updated on helm.camunda.io.
Hopefully the last fix related to:
* https://github.com/camunda/camunda-platform-helm/pull/4036/files

chore: fix the readme of 8.7-12.5.0 release

---

.github/workflows/chart-release-artifact-verify.yaml
.github/workflows/chart-release.yaml
scripts/generate-release-notes.sh
scripts/generate-version-matrix.sh
scripts/templates/release-notes/RELEASE-NOTES-FOOTER.md.tpl

Part of: https://github.com/camunda/camunda-platform-helm/issues/3546
Fixes: https://github.com/camunda/camunda-platform-helm/issues/4024
Moving the validation details to a script part of the release assets, and created a GHA workflow that runs nightly to validate the integrity of the released Helm charts.
Note: Currently, the workflow will run only when the `*-cosign-verify.sh` file is in the release assets; otherwise, the verification will be skipped.

ci: validate Helm charts integrity nightly

---

charts/camunda-platform-8.8/templates/orchestration/configmap.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-authorizations.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap.golden.yaml
charts/camunda-platform-8.8/values-digest.yaml

I added the missing config to the orchestration cluster which was causing the orchestraiton cluster to fail and I also updated the values-digest to the latest SNAPSHOT

fix: added missing config to orchestration cluster

---

charts/camunda-platform-8.8/templates/orchestration/_helpers.tpl
charts/camunda-platform-8.8/templates/orchestration/configmap.yaml
charts/camunda-platform-8.8/templates/orchestration/files/_application-unified.yaml
charts/camunda-platform-8.8/templates/orchestration/identity-migration-configmap.yaml
charts/camunda-platform-8.8/templates/orchestration/statefulset.yaml
charts/camunda-platform-8.8/test/unit/common/golden/core-service-monitor.golden.yaml
charts/camunda-platform-8.8/test/unit/common/golden/secret-core.golden.yaml
charts/camunda-platform-8.8/test/unit/common/ingress_test.go
charts/camunda-platform-8.8/test/unit/connectors/configmap_test.go
charts/camunda-platform-8.8/test/unit/connectors/golden/configmap.golden.yaml
charts/camunda-platform-8.8/test/unit/console/golden/configmap.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-authorizations.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-unified.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/gateway-service.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/poddisruptionbudget.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/service.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/serviceaccount.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/statefulset.golden.yaml
charts/camunda-platform-8.8/test/unit/web-modeler/configmap_restapi_test.go
charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml

Part of: https://github.com/camunda/camunda-platform-helm/issues/4026
We use `zeebe` as a name for The Orchestration cluster, mainly for backward compatibility with the 8.7 setup.
However, it could be confusing to have it as `zeebe` for the StatefulSet and `orchestration` for other resources.
For consistency, we use `zeebe` as the name for everything on the manifests level (not the end user level).

refactor: revert to zeebe as name for orchestration cluster

---

test/integration/scenarios/chart-full-setup/Taskfile.yaml
test/integration/scenarios/lib/chart-upgrade-taskfile.yaml

Related to: https://github.com/camunda/camunda-platform-helm/pull/4120
Fix missing digest values file when it doesn't exist (which is true for the non-alpha versions).

ci: fix missing digest values file when doesn't exist

---

charts/camunda-platform-8.8/values-digest.yaml

values-digest.yaml needs to be updated to 8.8.0-alpha8.1

fix: console digest now points to 8.8.0-alpha8.1

---

charts/camunda-platform-8.8/templates/orchestration/configmap.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-authorizations.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap.golden.yaml

https://github.com/camunda/camunda/issues/32007, aligns the `opensearch.aws.enabled` config with usage of AWS credentials, meaning:
- if false, will never use AWS credentials even if they exist in the form of envs or `.aws` folder
- if true, will use AWS credentials if they are configured

feat: opensearch aws enabled config now affects usage of AWS credentials

---

charts/camunda-platform-8.8/templates/common/constraints.tpl

The Helm chart continues to enable Elasticsearch, even though the no-db flag `global.noSecondaryStorage=true` is set. Output:
```## Installed Services:
- Console:
- Enabled: false
- Orchestration:
- Enabled: true
- Docker Image used for Zeebe: camunda/camunda:8.8.0-alpha8
- Zeebe Cluster Name: "my-camunda-devel-zeebe"
- Prometheus ServiceMonitor Enabled: false
- Connectors:
- Enabled: true
- Docker Image used for Connectors: camunda/connectors-bundle:8.8.0-alpha8
- Identity:
- Enabled: false
- Web Modeler:
- Enabled: false
- Elasticsearch:
- Enabled: true
- Docker Image used for Elasticsearch: bitnamilegacy/elasticsearch:8.18.0
```
We still need to configure OIDC authentication with "no-secondary-storage" mode as Basic authentication is not supported.
There is some bad UX in the Helm …

fix: add constraints for ES and Basic auth in noSecondaryStorage mode

---

charts/camunda-platform-8.8/templates/optimize/configmap.yaml
charts/camunda-platform-8.8/templates/orchestration/files/_application-unified.yaml

This update fixes an issue with custom prefixes where the default index prefix used to export from zeebe was the default inside zeebe and the prefix index used for import in optimize was the elasticsearch default.
Longer term fix should be to remove all usage of the env variables and restructure the index prefixes under a simple value structure, much like the global identity settings. 

fix: add missing opensearch fields in templates

---

charts/camunda-platform-8.8/templates/orchestration/files/_application-unified.yaml
charts/camunda-platform-8.8/templates/orchestration/importer-configmap-env-vars.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-authorizations.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-log4j2.golden.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/configmap-unified.golden.yaml

OpenSearch Configuration Fix
Exporter Configuration Fix
- fix environment variables that were incorrectly using Elasticsearch helper functions and values for OpenSearch configurations
-  camundaPlatform.elasticsearchURL > camundaPlatform.opensearchURL
-  camundaPlatform.elasticsearchHost > camundaPlatform.opensearchHost
-  .Values.global.elasticsearch.* > .Values.global.opensearch.* 
-  quoting CAMUNDA_DATABASE_INDEX_NUMBER_OF_REPLICAS
- numberOfReplicas setting to the correct location under the index

fix: opensearch config and index replica placement

---

charts/camunda-platform-8.8/templates/orchestration/importer-deployment.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/importer-deployment.golden.yaml

The deployment was using to parts spec of a statefulset that caused problems deploying it.
The Helm chart upgrade or install may have hidden the problem. It's more visible when applying it directly via e.g. template.
```
Error from server (BadRequest): error when creating "charts/camunda-platform-8.8/test/unit/orchestration/golden/importer-deployment.golden.yaml": Deployment in version "v1" cannot be handled as a Deployment: strict decoding error: unknown field "spec.updateStrategy"
```
[Deployment docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy) vs [Statefulset](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies)
A quick fix to use the deployment compatible version of what was wanted.
Please make sure to follow …

fix: use correct upgrade strategy for importer deployment

---

charts/camunda-platform-8.8/templates/orchestration/migration-data-job.yaml
charts/camunda-platform-8.8/templates/orchestration/migration-identity-job.yaml

Allow `data-migration-job` and `identity-migration-job` to inherit `orchestration.env` pass variables. This is to make sure that any variable that affects the global state, in this case _SchemaManager_ config should be present in the deployments as well.
closes: #4226

fix: data and identity migraiton accept orchestration env

---

charts/camunda-platform-8.8/templates/orchestration/migration-identity-configmap.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/migration-identity-configmap.golden.yaml
charts/camunda-platform-8.8/values-digest.yaml

* The base URL used by the identity migration needs to point to the
management identity. Previously, it was using the redirectUrl going to localhost, which 
obviously failed the migration
* Instead of using identity snapshot, which will be the latest version, we have to use for 8.8 the 8.8-SNAPSHOT.
* Fix the above

fix: fix configurations of identity migration

---

charts/camunda-platform-8.8/templates/orchestration/importer-deployment.yaml
charts/camunda-platform-8.8/test/unit/orchestration/golden/importer-deployment.golden.yaml

Removes the importer deployment affinity as it actively overlaps with the zeebe-broker.
Depending on cluster size and broker count this can impact users to block the migration or delay it since no node may be available. This will be a temporary deployment and doesn't actually house data nor is it important for resilience or similar. Therefore, proposing to remove the affinity.
We don't have affinities in place either for the migration jobs of data / identity.
- Removal of affinity for the importer deployment

fix: remove importer affinity in 8.8

---

.github/workflows/test-local-template.yaml
.tool-versions
charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-upgrade-migration.yaml
charts/camunda-platform-8.8/test/ci-test-config.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-upgrade-migration.yaml
test/integration/scenarios/lib/chart-upgrade-taskfile.yaml

Task: https://github.com/camunda/camunda-platform-helm/issues/959
Add a scenario to upgrade with migration enabled (also keep when migration is disabled, which is the default).

ci: enable minor upgrade migration from 8.7 to 8.8

---

charts/camunda-platform-8.8/templates/identity/deployment.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-keycloak-mt.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-keycloak-rba.yaml
charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-keycloak.yaml

I found that the orchestration client secret was being used instead of the migration identity jobs dedicated client secret. This PR adds in autogeneration for the migration identity job's client secret, as well as corrects identity.
```diff
{{- include "camundaPlatform.emitEnvVarFromSecretConfig" (dict
"envName" "KEYCLOAK_CLIENTS_2_SECRET"
-                "config" .Values.orchestration.security.authentication.oidc
+                "config" .Values.orchestration.migration.identity
) | nindent 12 }}
```

fix: migration identity client secret gets set to migration secret instead of orchestration client secret
