camunda/camunda-platform-helm

charts/zeebe-cluster-helm/README.md, charts/zeebe-cluster-helm/templates/gateway-deployment.yaml, charts/zeebe-cluster-helm/templates/statefulset.yaml, charts/zeebe-cluster-helm/values.yaml
=> Add support for priorityClassName

charts/zeebe-cluster-helm/templates/gateway-deployment.yaml, charts/zeebe-cluster-helm/templates/statefulset.yaml
It should be under spec not containers 😅
=> Fix priorityClassName

charts/zeebe-cluster-helm/values.yaml
related to https://github.com/camunda-cloud/zeebe/pull/8446
=> bump elastic version to 7.16.2

charts/zeebe-cluster-helm/templates/gateway-deployment.yaml, charts/zeebe-cluster-helm/templates/statefulset.yaml, charts/zeebe-cluster-helm/values.yaml
=> Add support for imagePullSecrets

charts/ccsm-helm/Chart.yaml, charts/ccsm-helm/charts/operate/README.md, charts/ccsm-helm/charts/operate/templates/NOTES.txt, charts/ccsm-helm/charts/operate/templates/_helpers.tpl, charts/ccsm-helm/charts/operate/templates/configmap.yaml, charts/ccsm-helm/charts/operate/templates/deployment.yaml, charts/ccsm-helm/charts/operate/templates/ingress.yaml, charts/ccsm-helm/charts/operate/templates/service.yaml, charts/ccsm-helm/charts/operate/templates/serviceaccount.yaml, charts/ccsm-helm/charts/operate/templates/tests/test-connection.yaml, charts/ccsm-helm/charts/tasklist/.helmignore, charts/ccsm-helm/charts/tasklist/Chart.yaml, charts/ccsm-helm/charts/tasklist/README.md, charts/ccsm-helm/charts/tasklist/templates/NOTES.txt, charts/ccsm-helm/charts/tasklist/templates/_helpers.tpl, charts/ccsm-helm/charts/tasklist/templates/configmap.yaml, charts/ccsm-helm/charts/tasklist/templates/deployment.yaml, charts/ccsm-helm/charts/tasklist/templates/ingress.yaml, charts/ccsm-helm/charts/tasklist/templates/service.yaml, charts/ccsm-helm/charts/tasklist/templates/tests/test-connection.yaml, charts/ccsm-helm/charts/tasklist/values.yaml, charts/ccsm-helm/templates/NOTES.txt, charts/ccsm-helm/values.yaml
* Copies the zeebe-tasklist-helm chart into the ccsm-helm chart as tasklist sub chart
* Adjust property names, add missing values to values file
* Adjust parent values.yaml, enable tasklist per default
* Add notes to the parent NOTES files
Related to #124
=> Add tasklist sub chart

charts/ccsm-helm/Chart.yaml, charts/ccsm-helm/README.md, charts/ccsm-helm/templates/NOTES.txt, charts/ccsm-helm/values.yaml
Remove unused dependencies:
* prometheus stack
* kibana
Both can be installed separately by the user if really needed.
Extracted from #158
=> Remove CCSM dependencies

charts/ccsm-helm/test/golden/goldenfiles.go, charts/ccsm-helm/test/operate/goldenfiles_test.go, charts/ccsm-helm/test/tasklist/golden/configmap.golden.yaml, charts/ccsm-helm/test/tasklist/golden/deployment.golden.yaml, charts/ccsm-helm/test/tasklist/golden/service.golden.yaml, charts/ccsm-helm/test/tasklist/goldenfiles_test.go, charts/ccsm-helm/test/zeebe-gateway/golden/configmap.golden.yaml, charts/ccsm-helm/test/zeebe-gateway/golden/gateway-deployment.golden.yaml, charts/ccsm-helm/test/zeebe-gateway/golden/gateway-service.golden.yaml, charts/ccsm-helm/test/zeebe-gateway/golden/gateway-serviceaccount.golden.yaml, charts/ccsm-helm/test/zeebe-gateway/goldenfiles_test.go, charts/ccsm-helm/test/zeebe/golden/configmap.golden.yaml, charts/ccsm-helm/test/zeebe/golden/service.golden.yaml, charts/ccsm-helm/test/zeebe/golden/serviceaccount.golden.yaml, charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml, charts/ccsm-helm/test/zeebe/goldenfiles_test.go
Add for all remaining subcharts golden tests. Refactor the golden testing so it can easily being reused.
=> Add more golden tests

Makefile, charts/ccsm-helm/README.md, charts/ccsm-helm/charts/operate/templates/ingress.yaml, charts/ccsm-helm/charts/tasklist/templates/deployment.yaml, charts/ccsm-helm/charts/zeebe-gateway/templates/gateway-deployment.yaml, charts/ccsm-helm/charts/zeebe/templates/statefulset.yaml, charts/ccsm-helm/test/golden/goldenfiles.go, charts/ccsm-helm/test/operate/configmap_test.go, charts/ccsm-helm/test/operate/golden/configmap-elastic-url.golden.yaml, charts/ccsm-helm/test/operate/golden/ingress-all-enabled.golden.yaml, charts/ccsm-helm/test/operate/golden/ingress.golden.yaml, charts/ccsm-helm/test/operate/golden/serviceaccount.golden.yaml, charts/ccsm-helm/test/operate/goldenfiles_test.go, charts/ccsm-helm/test/operate/ingress_test.go, charts/ccsm-helm/test/tasklist/deployment_test.go, charts/ccsm-helm/test/tasklist/golden/deployment.golden.yaml, charts/ccsm-helm/test/tasklist/goldenfiles_test.go, charts/ccsm-helm/test/zeebe-gateway/golden/gateway-deployment.golden.yaml, charts/ccsm-helm/test/zeebe/golden/statefulset.golden.yaml, charts/ccsm-helm/values.yaml
Add more tests for operate and tasklist. Fix and refactor some issues on the way.
=> Add more template tests

charts/ccsm-helm/README.md, charts/ccsm-helm/charts/zeebe-gateway/templates/gateway-poddisruptionbudget.yaml, charts/ccsm-helm/charts/zeebe/templates/poddisruptionbudget.yaml, charts/ccsm-helm/test/zeebe-gateway/golden/poddisruptionbudget.golden.yaml, charts/ccsm-helm/test/zeebe-gateway/goldenfiles_test.go, charts/ccsm-helm/test/zeebe-gateway/poddisruptionbudget_test.go, charts/ccsm-helm/test/zeebe/golden/poddisruptionbudget.golden.yaml, charts/ccsm-helm/test/zeebe/poddisruptionbudget_test.go, charts/ccsm-helm/values.yaml
Make minAvailability mutual exclusive with maxUnavailabilty on PodDisrutptionBudget + add a test for it.
Nice what we find with writing these tests :D
=> Make minAvailability mutual exclusive

charts/ccsm-helm/templates/curator-cronjob.yaml
=> fix: use correct configMap name for curator

charts/ccsm-helm/charts/zeebe/templates/statefulset.yaml, charts/ccsm-helm/test/zeebe/golden/statefulset-containersecuritycontext.golden.yaml, charts/ccsm-helm/test/zeebe/statefulset_test.go
This fixes #199. I also added a test to verify that the output is correct now.
=> fix: correctly indent `containerSecurityContext`

charts/ccsm-helm/README.md, charts/ccsm-helm/charts/tasklist/templates/deployment.yaml, charts/ccsm-helm/charts/zeebe-gateway/templates/gateway-deployment.yaml, charts/ccsm-helm/test/tasklist/golden/deployment.golden.yaml, charts/ccsm-helm/test/zeebe-gateway/deployment_test.go, charts/ccsm-helm/test/zeebe-gateway/poddisruptionbudget_test.go, charts/ccsm-helm/test/zeebe/statefulset_test.go, charts/ccsm-helm/values.yaml
Document and test the command property on all sub charts, furthermore add the command to subcharts where it was missing.
=> feat: document and test command

CONTRIBUTING.md, charts/ccsm-helm/test/README.md
Extend the contribution guide and document what is expected for an PR and what kind of tests we have and what kind of tests we expect for a new contribution.
closes https://github.com/camunda/camunda-cloud-helm/issues/206
=> How to write tests

.github/workflows/go.yml, Makefile, charts/ccsm-helm/test/golden/goldenfiles.go, charts/ccsm-helm/test/operate/configmap_test.go, charts/ccsm-helm/test/operate/deployment_test.go, charts/ccsm-helm/test/operate/goldenfiles_test.go, charts/ccsm-helm/test/operate/ingress_test.go, charts/ccsm-helm/test/tasklist/deployment_test.go, charts/ccsm-helm/test/tasklist/goldenfiles_test.go, charts/ccsm-helm/test/zeebe-gateway/configmap_test.go, charts/ccsm-helm/test/zeebe-gateway/deployment_test.go, charts/ccsm-helm/test/zeebe-gateway/goldenfiles_test.go, charts/ccsm-helm/test/zeebe-gateway/poddisruptionbudget_test.go, charts/ccsm-helm/test/zeebe-gateway/service_test.go, charts/ccsm-helm/test/zeebe-gateway/serviceaccount_test.go, charts/ccsm-helm/test/zeebe/configmap_test.go, charts/ccsm-helm/test/zeebe/goldenfiles_test.go, charts/ccsm-helm/test/zeebe/poddisruptionbudget_test.go, charts/ccsm-helm/test/zeebe/service_test.go, charts/ccsm-helm/test/zeebe/statefulset_test.go
* [build: add license tooling](https://github.com/camunda/camunda-cloud-helm/commit/c6a3bd823853831e49bba20366730906a91753a2)
* [build: add license headers](https://github.com/camunda/camunda-cloud-helm/commit/fc14d13e12ea06e5097b06489ae18b4b39f1c53c)
* [ci: use make fmt](https://github.com/camunda/camunda-cloud-helm/commit/cd2c74aa99fc2404ad5b7922d4ffd120d83959c9)
* [ci: add license tooling to ci](https://github.com/camunda/camunda-cloud-helm/commit/693189294257479479868fc073c528725fa9b7f2)
closes #185
=> Add license headers

charts/ccsm-helm/test/integration/integration_test.go
> **Note:** Please be aware that it contains commits from #215, which should be merged first
blocked by #215 
Adds Tasklist to our integration test setup, which completes our current e2e tests.
```
TestIntegration/TestServicesEnd2End 2022-03-03T13:31:35+01:00 integration_test.go:350: Endpoint localhost:33825 is now forwarded
integration_test.go:138: Request successful, got as response '{
"data" : {
"tasks" : [ {
"name" : "It Test"
} ]
}
}'
integration_test.go:153: User Task 'It Test' successful queried from tasklist!
```
:tada: 
closes #214
=> Add Tasklist to IT

charts/ccsm-helm/README.md, charts/ccsm-helm/charts/zeebe/templates/service.yaml, charts/ccsm-helm/test/zeebe/service_test.go, charts/ccsm-helm/values.yaml
**What?**
This PR allows users to expose any ports they need
**Why?**
There can  be instances when one needs to export additional ports.  In my case it was due to installing an exporter.
=> feat: Adds extra services to zeebe broker

charts/camunda-platform/Chart.yaml, charts/camunda-platform/values.yaml
Removes the tag value from the values file and set the version in the chart yaml
closes #230
=> Update elasticsearch to 7.17.1

charts/camunda-platform/templates/NOTES.txt
* Add optimize to the service section
* Fix the image tag for all services
* Add more conditions for Zeebe, show right tag and whether it is enabled
closes #299
=> Update notes file

charts/camunda-platform/README.md, charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml, charts/camunda-platform/values.yaml
Set the default cpu and io threadcount to 3.
closes #226
=> Align thread count with partitioncount

charts/camunda-platform/README.md, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/test/tasklist/deployment_test.go, charts/camunda-platform/values.yaml
=> feat: extend tasklist configuration

charts/camunda-platform/test/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/optimize/golden/ingress-all-enabled.golden.yaml, charts/camunda-platform/test/optimize/golden/ingress.golden.yaml, charts/camunda-platform/test/optimize/golden/service.golden.yaml, charts/camunda-platform/test/optimize/golden/serviceaccount.golden.yaml, charts/camunda-platform/values.yaml
Preview releases are production ready, thus bumping to latest.
=> feat Optimize 3.9.0-preview2

README.md
**Description**
Helps users discover the OpenShift getting started from the main README.
=> Point the OpenShift profile directly from the main README

README.md, RELEASE.md, charts/camunda-platform/Chart.yaml, charts/camunda-platform/README.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
In this PR I just tidy up the chart like update the description, the icon, and added myself as a maintainer.
Related to: #371
=> chore: tidy up camunda-platform chart

charts/camunda-platform/README.md, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/test/tasklist/deployment_test.go, charts/camunda-platform/values.yaml
All other charts have it already.
=> Feat: Add extraVolumes and extraVolumeMounts to Tasklist chart

.github/ISSUE_TEMPLATE/bug_report_template.md, .github/ISSUE_TEMPLATE/enhancement_request_template.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
=> chore: added github templates for pr and issue

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.0.14

.github/workflows/chart-update-image-tag.yaml, Makefile, RELEASE.md, charts/camunda-platform/values.yaml
Fixes: #413
Provide a method to update Camunda Platform image tag in the values file.
That could be done manually in the UI or via `gh` CLI tool from another repo. 
=> feat(ci): add a workflow to change c8 image tag in values file

.github/workflows/chart-update-image-tag.yaml
=> chore(ci): tidy up update-image-tag workflow

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.0

README.md, charts/camunda-platform/README.md, charts/camunda-platform/charts/identity/README.md, charts/camunda-platform/charts/operate/README.md, charts/camunda-platform/charts/optimize/README.md, charts/camunda-platform/charts/tasklist/README.md, charts/camunda-platform/charts/zeebe-gateway/README.md, charts/camunda-platform/charts/zeebe/README.md, charts/camunda-platform/templates/NOTES.txt, openshift/README.md
There are some minor mistakes here and there, old links, and readability enhancements.
Misc fixes and tidies up for the in-repo docs.
=> docs: refine readme files after c8sm v8.1 release

.github/workflows/chart-validate.yaml, .github/workflows/go-it-os.yaml, .github/workflows/go-it.yaml, .github/workflows/go.yml
=> chore(ci): only run workflows on the relevant paths

charts/camunda-platform/README.md, charts/camunda-platform/charts/identity/templates/_helpers.tpl, charts/camunda-platform/charts/identity/templates/deployment.yaml, charts/camunda-platform/test/identity/deployment_test.go, charts/camunda-platform/values.yaml
Allow user to use custom key for keycloak existing secret.
=> feat: support using custom key for keycloak existing secret

.github/workflows/go-it-os.yaml, .github/workflows/go-it.yaml, Makefile, charts/camunda-platform/test/integration/setup.go
Integration tests sometimes are flaky, and it's hard to know if it's a factual error or it's just the pipeline.
So, for now, we need to have better visibility of the tests.
- Better names for the tests' namespaces.
- Each test will run in its own workflow job so it's easier to spot the issue and restart a single job if needed.  
=> feat(ci): improve integration tests visibility in ci pipelines

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml, charts/camunda-platform/test/ingress_test.go, charts/camunda-platform/values.yaml
=> Release Camunda Platform Helm Chart v8.1.1

charts/camunda-platform/test/identity/deployment_test.go, charts/camunda-platform/test/ingress_test.go, charts/camunda-platform/test/integration/integration_suite.go, charts/camunda-platform/test/operate/configmap_test.go, charts/camunda-platform/test/operate/deployment_test.go, charts/camunda-platform/test/optimize/deployment_test.go, charts/camunda-platform/test/tasklist/configmap_test.go, charts/camunda-platform/test/tasklist/deployment_test.go, charts/camunda-platform/test/zeebe-gateway/deployment_test.go, charts/camunda-platform/test/zeebe/statefulset_test.go
Rename unclear import name in tests.
=> chore(tests): fix unclear import name

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.2

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.3

.github/workflows/chart-release.yaml, .github/workflows/test-integration-openshift.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-unit.yml
Eliminate any unnecessary waiting by using the Go cache in the pipelines.
=> chore: setup go cache in the ci pipelines

charts/camunda-platform/README.md, charts/camunda-platform/charts/identity/templates/deployment.yaml, charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/optimize/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml, charts/camunda-platform/charts/zeebe/templates/statefulset.yaml, charts/camunda-platform/test/identity/deployment_test.go, charts/camunda-platform/test/operate/deployment_test.go, charts/camunda-platform/test/optimize/deployment_test.go, charts/camunda-platform/test/tasklist/deployment_test.go, charts/camunda-platform/test/zeebe-gateway/deployment_test.go, charts/camunda-platform/test/zeebe-gateway/golden/gateway-deployment.golden.yaml, charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml, charts/camunda-platform/test/zeebe/statefulset_test.go, charts/camunda-platform/values.yaml
=> feat: support startupProbe, readinessProbe, and livenessProbe

.gitignore, charts/camunda-platform/charts/tasklist/templates/configmap.yaml, charts/camunda-platform/test/tasklist/golden/configmap.golden.yaml
add loggers,usage-metrics,backup
according to https://github.com/camunda/tasklist/blob/708913dee39d4506d46d251e68888d1f2cd12dc3/webapp/src/main/java/io/camunda/tasklist/Application.java#L121-L121
=> Add default actuator endpoints - Tasklist

charts/camunda-platform/charts/operate/templates/configmap.yaml, charts/camunda-platform/test/operate/golden/configmap.golden.yaml
Which problem does the PR fix?
https://github.com/camunda/camunda-platform-helm/issues/469
What's in this PR?
add loggers,usage-metrics,backup
according to https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#monitoring-operate
=> Add default actuator endpoints - Operate

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.4

.github/workflows/chart-release.yaml, .github/workflows/test-integration-openshift.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-unit.yml, .tool-versions
=> chore: unify go setup

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/web-modeler/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.5

charts/camunda-platform/charts/zeebe/templates/statefulset.yaml, charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml
Fixes: #529
Set elasticsearch exporter prefix index config.
=> fix: set missing elasticsearch prefix env var

.github/actions/gke-login/action.yml, .github/actions/venom-deploy-testsuite/action.yml, .github/workflows/test-integration-kubernetes.yaml, test/integration/venom/base/config/venom-env-vars, test/integration/venom/base/job.yaml, test/integration/venom/base/kustomization.yaml, test/integration/venom/base/testsuites/00-info.yaml, test/integration/venom/core/kustomization.yaml, test/integration/venom/core/patches/job.yaml, test/integration/venom/core/testsuites/core.yaml, test/integration/venom/preflight/kustomization.yaml, test/integration/venom/preflight/testsuites/preflight.yaml
Fixes: #539
Use Venom for declarative integration tests and create its pipeline.
=> test: use venom for declarative integration tests

.github/workflows/test-integration-kubernetes.yaml, test/integration/fixtures/chart-identity-keycloak-v19.yaml, test/integration/fixtures/values-enable-readiness.yaml, test/integration/venom/preflight/testsuites/preflight.yaml
Enhance the stability of Venom integration tests.
=> chore(ci): enhance venom integration tests

.github/workflows/test-integration-kubernetes.yaml, .tool-versions, test/integration/scenarios/chart-with-default-values/Taskfile.yaml, test/integration/scenarios/chart-with-keycloak-v19/Taskfile.yaml, test/integration/scenarios/lib/testsuite-deploy-taskfile.yaml
Use [Task](https://github.com/go-task/task) as a task runner for the integration tests.
=> chore(ci): use task runner to run integration tests

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/web-modeler/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
- The pipeline of Keycloak v19 on OpenShift has an issue related to Docker rate limit not related to the release.
=> Release Camunda Platform Helm Chart v8.1.6

charts/camunda-platform/test/web-modeler/golden/configmap-shared.golden.yaml, charts/camunda-platform/test/web-modeler/golden/deployment-restapi.golden.yaml, charts/camunda-platform/test/web-modeler/golden/deployment-webapp.golden.yaml, charts/camunda-platform/test/web-modeler/golden/deployment-websockets.golden.yaml, charts/camunda-platform/test/web-modeler/golden/ingress-all-enabled.golden.yaml, charts/camunda-platform/test/web-modeler/golden/ingress.golden.yaml, charts/camunda-platform/test/web-modeler/golden/secret-shared.golden.yaml, charts/camunda-platform/test/web-modeler/golden/service-restapi.golden.yaml, charts/camunda-platform/test/web-modeler/golden/service-webapp.golden.yaml, charts/camunda-platform/test/web-modeler/golden/service-websockets.golden.yaml, charts/camunda-platform/test/web-modeler/golden/serviceaccount.golden.yaml, charts/camunda-platform/values.yaml
Updates the Web Modeler to the latest beta version.
Just a version update to `0.5.0-beta`.
=> chore(web-modeler): update to version 0.5.0-beta

charts/camunda-platform/test/web-modeler/golden/configmap-shared.golden.yaml, charts/camunda-platform/test/web-modeler/golden/deployment-restapi.golden.yaml, charts/camunda-platform/test/web-modeler/golden/deployment-webapp.golden.yaml, charts/camunda-platform/test/web-modeler/golden/deployment-websockets.golden.yaml, charts/camunda-platform/test/web-modeler/golden/ingress-all-enabled.golden.yaml, charts/camunda-platform/test/web-modeler/golden/ingress.golden.yaml, charts/camunda-platform/test/web-modeler/golden/secret-shared.golden.yaml, charts/camunda-platform/test/web-modeler/golden/service-restapi.golden.yaml, charts/camunda-platform/test/web-modeler/golden/service-webapp.golden.yaml, charts/camunda-platform/test/web-modeler/golden/service-websockets.golden.yaml, charts/camunda-platform/test/web-modeler/golden/serviceaccount.golden.yaml, charts/camunda-platform/values.yaml
Update Web Modeler to the latest beta version.
Web Modeler version update to `0.7.0-beta`.
=> chore(web-modeler): update to version 0.7.0-beta

charts/camunda-platform/README.md, charts/camunda-platform/templates/ingress.yaml, charts/camunda-platform/templates/web-modeler/_helpers.tpl, charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml, charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml, charts/camunda-platform/test/ingress_test.go, charts/camunda-platform/test/web-modeler/deployment_webapp_test.go, charts/camunda-platform/test/web-modeler/deployment_websockets_test.go, charts/camunda-platform/values.yaml
Closes https://github.com/camunda/web-modeler/issues/3179.
Add support for Web Modeler in the combined Ingress.
=> feat(web-modeler): add Web Modeler to combined Ingress

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.7

charts/camunda-platform/templates/connectors/deployment.yaml, charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml, charts/camunda-platform/values.yaml
=> refactor: enable connectors by default

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml, charts/camunda-platform/test/unit/web-modeler/golden/configmap-shared.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/ingress-all-enabled.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/ingress.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/secret-shared.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/service-restapi.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/service-webapp.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/service-websockets.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/serviceaccount.golden.yaml, charts/camunda-platform/values.yaml
=> Release Camunda Platform Helm Chart v8.2.0

charts/camunda-platform/templates/_helpers.tpl, charts/camunda-platform/templates/connectors/deployment.yaml, charts/camunda-platform/templates/ingress.yaml, charts/camunda-platform/test/unit/connectors/deployment_test.go
- Adds correct handling of context path
- Utility: adds connectors runtime URL that may be required in the future
Bugfix, see https://camunda.slack.com/archives/C02JLRNQQ05/p1682629277926949
=> fix(connectors): adds correct handling of context path

charts/camunda-platform/test/unit/web-modeler/golden/configmap-shared.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/ingress-all-enabled.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/ingress.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/secret-shared.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/service-restapi.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/service-webapp.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/service-websockets.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/serviceaccount.golden.yaml, charts/camunda-platform/values.yaml
Part of https://github.com/camunda/web-modeler/issues/4576.
Update Web Modeler to version 8.2.1.
=> chore(web-modeler): update to version 8.2.1

.github/workflows/chart-update-image-tag.yaml, charts/camunda-platform/values.yaml, scripts/update-values-file-image-tag.sh
Fixes: #627
Allow setting WebModeler and Connectors version via CI pipeline which is used in the release.
=> ci: support web-modeler and connectors in the update image pipeline

.github/workflows/test-integration-kubernetes.yaml, .github/workflows/test-integration-openshift.yaml, charts/camunda-platform/charts/identity/templates/_helpers.tpl, charts/camunda-platform/charts/identity/templates/deployment.yaml, charts/camunda-platform/charts/identity/templates/zeebe-secret.yaml, charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml, charts/camunda-platform/templates/_helpers.tpl, charts/camunda-platform/templates/connectors/deployment.yaml, charts/camunda-platform/test/integration/scenarios/chart-upgrade/Taskfile.yaml, charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml, charts/camunda-platform/test/integration/testsuites/base/job.yaml, charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml, charts/camunda-platform/values.yaml
Adds zeebe gateway authentication setup #608
Sets up zeebe gatwway authentication as well as a default client to be used by operate, tasklist & connectors.
=> feat: zeebe gateway authentication

charts/camunda-platform/charts/identity/templates/_helpers.tpl, charts/camunda-platform/values.yaml
=> chore: tidy up keycloak values

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.3

.github/workflows/test-regression.yaml, charts/camunda-platform/README.md, charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml, charts/camunda-platform/values.yaml, charts/camunda-platform/values/values-v8.0.yaml, charts/camunda-platform/values/values-v8.1.yaml
=> feat: values file level backporting per minor version

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/optimize/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.8

.github/renovate.json5, charts/camunda-platform/values.yaml, charts/camunda-platform/values/values-v8.0.yaml, charts/camunda-platform/values/values-v8.1.yaml, renovate.json
Configure Renovate Bot to update apps and tools automatically. So now all Camunda Platform 8 components and 3rd party components will get the latest updates for the corresponding version.
=> chore: Configure Renovate Bot to update apps and tools automatically

.github/workflows/renovate-config-check.yaml, .github/workflows/renovate-post-upgrade.yaml, .github/workflows/test-integration-kubernetes.yaml, .github/workflows/test-integration-openshift.yaml
=> ci: setup renovate workflows

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.4

.github/renovate.json5, charts/camunda-platform/values.yaml, charts/camunda-platform/values/values-v8.1.yaml
=> chore: use web-modeler version from docker instead of github-release

.github/renovate.json5, charts/camunda-platform/README.md, charts/camunda-platform/values.yaml, charts/camunda-platform/values/values-latest.yaml, charts/camunda-platform/values/values-v8.0.yaml
=> chore: minimal values file for apps latest tags

charts/camunda-platform/README.md, charts/camunda-platform/charts/zeebe/templates/configmap.yaml, charts/camunda-platform/test/unit/zeebe/golden/configmap-log4j2.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/configmap.golden.yaml, charts/camunda-platform/values.yaml
Fixes: #711
Print zeebe env vars in debug mode only.
=> refactor: print zeebe env vars in debug mode only

charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/optimize/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/values/values-v8.0.yaml, charts/camunda-platform/values/values-v8.1.yaml
operate, optimize, and tasklist
Fixes: #714
A workaround to fix the error `Invalid parameter: redirect_uri`, related to `CAMUNDA_*_IDENTITY_REDIRECT_ROOT_URL` vars in apps v8.2.5.
=> fix: invalid redirect uri in the apps

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.5

charts/camunda-platform/charts/identity/templates/deployment.yaml, charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/optimize/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml, charts/camunda-platform/charts/zeebe/templates/statefulset.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml, charts/camunda-platform/values.yaml
Fixes: #670
Add a check scheme to all probes in all components.
=> feat: add scheme to all probes

charts/camunda-platform/charts/identity/templates/deployment.yaml, charts/camunda-platform/charts/identity/templates/ingress.yaml, charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/operate/templates/ingress.yaml, charts/camunda-platform/charts/optimize/templates/deployment.yaml, charts/camunda-platform/charts/optimize/templates/ingress.yaml, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/ingress.yaml, charts/camunda-platform/charts/zeebe-gateway/templates/ingress.yaml, charts/camunda-platform/templates/connectors/ingress.yaml, charts/camunda-platform/templates/ingress.yaml, charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml, charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml, charts/camunda-platform/templates/web-modeler/ingress.yaml
Part of: distribution/issues/43
Support external url templating based on global ingress host to simplify the values changes.
=> feat: support external url templating based on global ingress host

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.6

README.md, charts/camunda-platform/README.md
Fixes: [distribution/issues/53](https://github.com/camunda/distribution/issues/53)
Add versions compatibility matrix between Camunda Platform 8 **Helm chart** and Camunda Platform 8 **applications**.
=> docs: add versions compatibility matrix

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
> *Note*
> This is a transit version to match the apps unified version. Starting from the next version, the chart version will be the same as the Camunda Platform unified version.
=> Release Camunda Platform Helm Chart v8.2.7

.github/workflows/release.yaml, charts/camunda-platform/Chart.yaml, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/optimize/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml, charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
jump from 8.0.10 to 8.0.18 to match the camunda platform  apps version
=> Release Camunda Platform Helm Chart v8.0.18

README.md, charts/camunda-platform/README.md
Part of: distribution/issues/65
Update the details about the new Helm chart versioning, which follows the same one in [Camunda Platform 8 applications](https://github.com/camunda/camunda-platform).
=> docs: update the versioning details

.github/workflows/chart-values-files.yaml, charts/camunda-platform/README.md
Copy values files to the gh-pages branch to have clean and shorter links like `https://helm.camunda.io/camunda-platform/values/values-latest.yaml`.
=> ci: copy values files to gh-pages branch

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.9

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v8.2.10

charts/camunda-platform/charts/operate/templates/configmap.yaml, charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
Since 8.2, backup was renamed in backups
=> fix: correct backups endpoint in operate

charts/camunda-platform/templates/NOTES.txt
#736
I added Ingress URLs for combined and separated Ingress to NOTES.txt
I used https://helm-playground.com to test the NOTES.txt against the values files mentioned here: [Combined and separated Ingress setup](https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/guides/ingress-setup)
=> feat: added ingress urls to the chart notes

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.11

charts/camunda-platform/Chart.yaml, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.0.19

.github/workflows/add-to-project.yml
adds gha to add issues to distribution team project board.
=> add gha add-to-project

.github/actions/pr-vars/action.yml, .github/workflows/test-integration-main.yaml, charts/camunda-platform/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
Part of: distribution/issues/91
Allow to use persistent names for deployment (e.g., namespace and ingress host) for development proposes).
=> ci: support persistent with pr labels

charts/camunda-platform/templates/NOTES.txt, charts/camunda-platform/templates/_helpers.tpl, charts/camunda-platform/templates/connectors/_helpers.tpl, charts/camunda-platform/templates/console/_helpers.tpl, charts/camunda-platform/templates/console/configmap.yaml, charts/camunda-platform/templates/console/deployment.yaml, charts/camunda-platform/templates/console/ingress.yaml, charts/camunda-platform/templates/console/service.yaml, charts/camunda-platform/templates/console/serviceaccount.yaml, charts/camunda-platform/templates/ingress.yaml, charts/camunda-platform/templates/release-configmap.yaml, charts/camunda-platform/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml, charts/camunda-platform/values.yaml
Part of: #834 
Add the initial chart files for Camunda Console Self-Managed.
=> feat: add console sm inital resources

charts/camunda-platform/README.md, charts/camunda-platform/charts/tasklist/templates/_helpers.tpl, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/serviceaccount.yaml, charts/camunda-platform/test/unit/tasklist/deployment_test.go, charts/camunda-platform/values.yaml
Fixes: #836
Set missing tasklist service account.
=> fix: set missing tasklist service account

.github/workflows/test-integration-main.yaml, charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.12

.github/workflows/test-integration-main.yaml
=> ci: pass extra values to integration test workflow

.github/renovate.json5
Fixes: #858
Enable auto-merge for Renovate bot PRs.
=> ci: auto-merge renovate bot prs

charts/camunda-platform/values.yaml
the text was generated using Banner and Banner3 from https://patorjk.com/software/taag/
=> chore: add visual comments in the values file

.github/renovate.json5, charts/camunda-platform/values/values-latest.yaml, charts/camunda-platform/values/values-v8.0.yaml, charts/camunda-platform/values/values-v8.1.yaml
=> ci: fix renovate es docker matching

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.13

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.16

charts/camunda-platform/Chart.yaml, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.0.20

charts/camunda-platform/test/unit/connectors/deployment_test.go, charts/camunda-platform/test/unit/global_deployment_test.go, charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml, charts/camunda-platform/test/unit/identity/deployment_test.go, charts/camunda-platform/test/unit/ingress_test.go, charts/camunda-platform/test/unit/operate/deployment_test.go, charts/camunda-platform/test/unit/optimize/deployment_test.go, charts/camunda-platform/test/unit/tasklist/deployment_test.go, charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go, charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go, charts/camunda-platform/test/unit/zeebe/statefulset_test.go
Fixes: #892
Removed the template key from helm.options
=> Refactor: Removed template from all helm.Options.ExtraArgs

charts/camunda-platform/README.md, charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml, charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go, charts/camunda-platform/values.yaml
Adding Zeebe configuration for Multi-tenancy 
Fixes:
- #782
- https://github.com/camunda/zeebe/issues/14307
- Updating Zeebe charts config and introducing the following new Zeebe configurations:
- `ZEEBE_GATEWAY_MULTITENANCY_ENABLED`
- `ZEEBE_BROKER_GATEWAY_MULTITENANCY_ENABLED`
=> feat: adding Zeebe configuration for Multi-tenancy

.github/workflows/test-unit.yml, Makefile, charts/camunda-platform/test/unit/identity/deployment_test.go, charts/camunda-platform/test/unit/operate/deployment_test.go, charts/camunda-platform/test/unit/tasklist/deployment_test.go, charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go, charts/camunda-platform/test/unit/zeebe/statefulset_test.go
Fixes: #901
Run charts unit tests as groups and a couple of tidy ups.
=> ci: run unit tests as groups

charts/camunda-platform/README.md, charts/camunda-platform/templates/web-modeler/_helpers.tpl, charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml, charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go, charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml, charts/camunda-platform/values.yaml
Uses the environment variables recommended by https://docs.camunda.io/docs/self-managed/modeler/web-modeler/configuration/#database for configuring database connectivity.
Relates to https://github.com/camunda/web-modeler/issues/4457
https://github.com/camunda/camunda-platform-docs/pull/2243 adjusts the documentation after this PR was merged
=> refactor: in web-modeler switch to spring env vars for db config

charts/camunda-platform/charts/operate/templates/deployment.yaml, charts/camunda-platform/charts/tasklist/templates/deployment.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> fix(operate,tasklist): readonly add zeebe cache path

.tool-versions, charts/camunda-platform/charts/identity/templates/_helpers.tpl, charts/camunda-platform/charts/identity/templates/deployment.yaml, charts/camunda-platform/templates/_helpers.tpl, charts/camunda-platform/templates/connectors/deployment.yaml, charts/camunda-platform/test/unit/connectors/deployment_test.go, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
A small clean-up after moving all components to the main chart except Identity.
=> refactor: update accessing keycloak url

.github/workflows/ossf-scorecard.yml
=> Adding OpenSSF to Github Actions workflows

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, scripts/verify-components-version.sh
=> Release Camunda Platform Helm Chart v8.3.1

docs/tests.md
=> docs for testing

.github/config/yamllint.yaml, charts/camunda-platform/templates/connectors/deployment.yaml, charts/camunda-platform/templates/tasklist/deployment.yaml, charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
Bug fix for: https://github.com/camunda/camunda-platform-helm/issues/415
I fixed the indentation error for the web-modeler and tasklist template. 
=> fix: resource indent error

.github/config/chart-testing.yaml, README.md, charts/camunda-platform/templates/zeebe/configmap.yaml, charts/camunda-platform/templates/zeebe/statefulset.yaml, charts/camunda-platform/test/unit/zeebe/golden/configmap-log4j2.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/configmap.golden.yaml, charts/camunda-platform/values.yaml
Continuing https://github.com/camunda/camunda-platform-helm/pull/1006   but directly inside this repo rather than fork.
=> feat(zeebe): multiregion

charts/camunda-platform/values.yaml
=> fix readme generator multiregion key

.github/workflows/test-integration-openshift.yaml, charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml, charts/camunda-platform/test/integration/it-keycloak-v19-values.yaml, test/integration/scenarios/chart-with-keycloak-v19/Taskfile.yaml, test/integration/scenarios/fixtures/values-integration-test.yaml
=> Release Camunda Platform Helm Chart v8.1.18

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.19

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
If the release is a minor version bump:
=> Release Camunda Platform Helm Chart v8.2.17

charts/camunda-platform/values.yaml
Issue: https://github.com/camunda/camunda-platform-helm/issues/977
=> chore(ES):validating if ElasticSearch configuration works correctly

charts/camunda-platform/templates/camunda/secret-optimize.yaml, charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
-
A typo in identity-optimize secret
=> fix: correct a typo in identity-optimize secret

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.20

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.18

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/camunda/golden/keycloak-statefulset.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/values.yaml
=> Release Camunda Platform Helm Chart v8.3.3

.github/workflows/chart-validate.yaml, .github/workflows/test-integration-template.yaml, .github/workflows/test-integration.yaml, docs/gha-workflows.md
=> ci: make a template from integration test workflow

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.21

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.19

charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/camunda/golden/keycloak-statefulset.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Issue: https://github.com/camunda/camunda-platform-helm/issues/1102
=> refactor: upgrade keycloak chart from 16.1.7 to 17.3.5

charts/camunda-platform/README.md
Unify Camunda Platform deployment name.
=> docs: rename example deployment name

charts/camunda-platform/charts/identity/templates/constraints.tpl, charts/camunda-platform/templates/camunda/constraints.tpl, charts/camunda-platform/test/unit/camunda/global_deployment_test.go
Fixes: https://github.com/camunda/camunda-platform-helm/issues/1151
Ensure that all Multi-Tenancy requirements are met.
=> refactor: fail if Multi-Tenancy requirements are not met

.github/renovate.json5, charts/camunda-platform/values.yaml, charts/camunda-platform/values/values-latest.yaml
Issue: https://github.com/camunda/distribution/issues/140
=> refactor: upgrade elasticsearch image from 8.8.2 to 8.9.2

.github/workflows/chart-update-readme.yaml
=> chore: fix chart-update-readme.yaml

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.22

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.20

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml
=> Release Camunda Platform Helm Chart v8.3.5

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.0.1

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.0.2

charts/camunda-platform/templates/camunda/_helpers.tpl, charts/camunda-platform/templates/camunda/configmap-release.yaml
=> chore: format release into as yaml

charts/camunda-platform/templates/camunda/configmap-release.yaml, charts/camunda-platform/templates/console/configmap.yaml, charts/camunda-platform/templates/console/deployment.yaml, charts/camunda-platform/values.yaml
=> refactor(console): pass config to console directly

.github/workflows/test-integration-template.yaml
Update OpenShift version to 4.14 and unify workflow var format.
=> ci: update openshift version and vars

.github/workflows/dispatch-integration-backport.yaml, .github/workflows/dispatch-integration.yaml
=> fix: fixed booleans in dispatch workflows

.github/workflows/dispatch-integration-backport.yaml, .github/workflows/dispatch-integration.yaml, .github/workflows/test-integration-openshift.yaml
=> Backport 8.1 fix openshift test

.github/workflows/dispatch-integration-backport.yaml, .github/workflows/dispatch-integration.yaml, .github/workflows/test-integration-template.yaml
=> Backport 8.3 fix openshift authentication in test

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.23

.github/workflows/chart-release.yaml
Use the env var `CHART_NAME_WITH_VERSION` to generate the correct name in the release notes.
=> ci: fix name in release notes

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v8.3.6

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v8.3.7

.github/workflows/chart-release.yaml, charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.1.1

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.1.2

charts/camunda-platform/test/unit/zeebe/configmap_test.go, charts/camunda-platform/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
Issue: https://github.com/camunda/distribution/issues/198
Added unit tests to verify the the zeebe configmap is changed based on the values in the multiregion section of the values.yaml
=> added configmap golden unit tests for multi-region

charts/camunda-platform/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
fixing the broken unit test in themain branch
=> update golden files

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.24

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.23

.github/workflows/chart-validate.yaml, charts/camunda-platform/templates/console/configmap.yaml, charts/camunda-platform/templates/console/deployment.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
=> test: fix yamllint errors

SECURITY.md
Related to https://github.com/camunda/distribution/issues/136
adding our SECURITY.md
=> fix: add security policy

charts/camunda-platform/values.yaml
related issue: https://github.com/camunda/distribution/issues/203
=> modified multiregion comment in values.yaml

.github/workflows/dispatch-integration.yaml, .github/workflows/test-integration-template.yaml, .github/workflows/test-integration.yaml
=> fix: resolves github deployment git ref when it differs from helm repo

.github/workflows/codeql.yml, .github/workflows/sec-codeql.yml
We had enabled CodeQL with a default configuration.
https://github.com/camunda/distribution/issues/207
Adding a customizable workflow. In this workflow CodeQL will only work on a nightly schedule. 
=> fix: Create codeql.yml with customized settings

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.1.25

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.24

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.1.3

charts/camunda-platform/README.md, charts/camunda-platform/templates/console/configmap.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/values.yaml
=> chore: tidy up console values

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.2.0

charts/camunda-platform/templates/NOTES.txt, charts/camunda-platform/templates/console/deployment.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
Part of: https://github.com/camunda/camunda-platform-helm/issues/1333
Set console internal auth var and port-forward.
=> chore: set console internal auth var and port-forward

charts/camunda-platform/templates/zeebe/configmap.yaml
fixes #1247
Backport of 
https://github.com/camunda/camunda-platform-helm/pull/1248
=> fix(multi-region failback): add missing newline in start script

charts/camunda-platform/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml, charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml, charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
=> chore: tidy up values keys for in the integration tests

charts/camunda-platform/templates/optimize/deployment.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/values.yaml
Allow defining resources and limits for all components https://github.com/camunda/camunda-platform-helm/issues/1224
adding resources and limits for any components that were missing in latest.
=> fix: defining resources and limits for optimize migration container

docs/architecture/multiregion.md
related to: https://github.com/camunda/distribution/issues/231
=> docs: multiregion architecture docs

charts/camunda-platform/README.md, charts/camunda-platform/templates/camunda/constraints.tpl, charts/camunda-platform/templates/operate/configmap.yaml, charts/camunda-platform/templates/tasklist/configmap.yaml, charts/camunda-platform/test/unit/tasklist/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/values.yaml
Closes #1513
As part of Zeebe Rest APIs, we need to configure Tasklist with Zeebe Rest Address.
=> refactor: adding zeebe rest config for Tasklist

.github/workflows/test-integration-template.yaml
Integration tests are failing due to permissions. We have created new vars to solve this issue. 
=> fix: updated GHA envs for our integration tests

.github/renovate.json5, .github/workflows/chart-release.yaml, .github/workflows/test-regression.yaml, charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml, charts/camunda-platform/values/values-v8.4.yaml
=> Release Camunda Platform Helm Chart v10.0.0

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
=> Release Camunda Platform Helm Chart v10.0.1

charts/camunda-platform/templates/zeebe-gateway/configmap.yaml, charts/camunda-platform/templates/zeebe-gateway/deployment.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/ingress-all-enabled.golden.yaml, charts/camunda-platform/test/unit/console/golden/ingress.golden.yaml, charts/camunda-platform/test/unit/console/golden/service.golden.yaml, charts/camunda-platform/test/unit/console/golden/serviceaccount.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, helm.yaml
related to: https://github.com/camunda/camunda-platform-helm/issues/1595
=> changed env vars

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/test/unit/camunda/golden/keycloak-statefulset.golden.yaml, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
=> Release Camunda Platform Helm Chart v10.0.2

charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
=> chore: use helm package for install and upgrade

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
=> Release Camunda Platform Helm Chart v10.0.3

charts/camunda-platform/templates/identity/configmap.yaml
=> fix: multitenancy should not always be true

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/VERSION-MATRIX.md, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
=> Release Camunda Platform Helm Chart v10.0.4

.github/workflows/test-integration-template.yaml, docs/gha-workflows.md
Part of a larger epic focusing on integration tests and improvements of integration tests, docs, etc.
Related to https://github.com/camunda/distribution/issues/241
Adding documentation on integration test inputs for teams trying to configure integration tests on their repositories. 
=> chore: added links to sections and workflow inputs documentation

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/charts/operate/Chart.yaml, charts/camunda-platform/charts/optimize/Chart.yaml, charts/camunda-platform/charts/tasklist/Chart.yaml, charts/camunda-platform/charts/zeebe-gateway/Chart.yaml, charts/camunda-platform/charts/zeebe/Chart.yaml
=> Release Camunda Platform Helm Chart v8.2.27

.github/workflows/chart-release.yaml, .tool-versions, charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml, charts/camunda-platform/version-matrix/README.md, charts/camunda-platform/version-matrix/camunda-8.2/README.md, charts/camunda-platform/version-matrix/camunda-8.3/README.md, charts/camunda-platform/version-matrix/camunda-8.4/README.md, charts/camunda-platform/version-matrix/camunda-8.5/README.md, charts/web-modeler-postgresql/Chart.yaml, charts/web-modeler-postgresql/RELEASE-NOTES.md
=> Release Camunda Platform Helm Chart v10.0.5

charts/camunda-platform/values.yaml
Related to: https://github.com/camunda/distribution/issues/242
I have deleted the comment in the values.yaml for the review of multiregion setup for customers.
=> fix: Delete multi-region review comment in values.yaml

charts/camunda-platform/test/unit/camunda/global_deployment_test.go, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml, charts/camunda-platform/values.yaml, charts/camunda-platform/values/values-latest.yaml
=> fix: operate should be 8.4.8 in helm 9.3.4

charts/camunda-platform/Chart.yaml, charts/camunda-platform/RELEASE-NOTES.md, charts/camunda-platform/charts/identity/Chart.yaml, charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml, charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml, charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
=> Release Camunda Platform Helm Chart v9.3.5

charts/camunda-platform/test/integration/testsuites/base/job.yaml, charts/camunda-platform/values.yaml
The repository camunda/zeebe will be renamed to camunda/camunda, this PR adjusts all references to this repository.
> **WHY**
> The name of this repository will be changed to align better with its new role as a monorepo containing multiple products of the stack.
> https://github.com/camunda/zeebe/issues/18206
related https://github.com/camunda/zeebe/issues/18206
I renamed all occurrences of github.com/camunda/zeebe. I didn't do this for camunda/zeebe as this will change occurrences for docker images (which we do not plan to change yet).
For posterity, the following script has been used.
```sh
#!/bin/bash
set -euox pipefail
path=$1
find "$path" -type f -exec sed -i -E 's|github.com/camunda/zeebe([/#])?|github.com/camunda/camunda\1|g' {} \;
count=$(git -C "$path" status | grep modified -c) …
```
=> refactor: rename camunda/zeebe repo

.github/workflows/chart-update-readme.yaml, .github/workflows/chart-validate.yaml, .github/workflows/test-integration.yaml
Related: https://github.com/camunda/distribution/issues/246
Removing all `pull_request_target` triggers
=> refactor: removing pull_request_target

.github/actions/workflow-vars/action.yml, .github/workflows/chart-release-snapshot.yaml, .github/workflows/test-unit.yml
Task: https://github.com/camunda/distribution/issues/265
Misc fixes.
=> chore(follow-up): use directory-based structure 

.github/actions/workflow-vars/action.yml, .github/workflows/test-alpha.yaml, .github/workflows/test-integration.yaml, charts/camunda-platform-alpha/test/unit/camunda/global_deployment_test.go
Task: https://github.com/camunda/distribution/issues/52
Enable alpha integration tests
=> chore: enable alpha tests

.github/workflows/chart-release-snapshot.yaml
=> chore: clean-up containers packages

charts/camunda-platform-latest/templates/operate/configmap.yaml, charts/camunda-platform-latest/templates/optimize/configmap.yaml, charts/camunda-platform-latest/templates/tasklist/configmap.yaml, charts/camunda-platform-latest/templates/zeebe-gateway/configmap.yaml, charts/camunda-platform-latest/test/unit/operate/golden/configmap.golden.yaml, charts/camunda-platform-latest/test/unit/tasklist/golden/configmap.golden.yaml, charts/camunda-platform-latest/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml, charts/camunda-platform-latest/test/unit/zeebe-gateway/golden/configmap.golden.yaml
closes #2027 
This PR add the identity baseUrl to all components that are missing it.
=> fix: identity base url not configured

.github/config/rosa-on-demand/test-integration-rosa-matrix.yaml
closes https://github.com/camunda/camunda-platform-helm/issues/2145
=> fix: upgrade rosa clusters

.github/actions/workflow-vars/action.yml, .github/workflows/test-alpha.yaml, .github/workflows/test-integration-template.yaml, charts/camunda-platform-alpha/test/unit/zeebe-gateway/ingress_test.go, charts/camunda-platform-latest/test/unit/zeebe-gateway/ingress_test.go, test/integration/scenarios/chart-full-setup/Taskfile.yaml, test/integration/scenarios/vars/common.env, test/integration/scenarios/vars/dynamic.env
Fixes: https://github.com/camunda/camunda-platform-helm/issues/2172
=> chore: fix alpha upgrade ci workflow

.github/workflows/examples/test-helm-chart.yaml, README.md, docs/gha-workflows.md
Task: https://github.com/camunda/distribution/issues/289
Added a step-by-step example to use the Distro GHA workflow to install and test the Helm chart.
=> chore: add steps to use helm chart gha workflow

.github/actions/test-type-vars/action.yml, .github/actions/workflow-vars/action.yml, .github/workflows/test-integration-template.yaml, charts/camunda-platform-8.2/test/integration/scenarios/infra/values-infra-preemptible.yaml, charts/camunda-platform-8.2/test/integration/scenarios/infra/values-infra-standard.yaml, charts/camunda-platform-8.3/test/integration/scenarios/infra/values-infra-preemptible.yaml, charts/camunda-platform-8.3/test/integration/scenarios/infra/values-infra-standard.yaml, charts/camunda-platform-8.4/test/integration/scenarios/infra/values-infra-preemptible.yaml, charts/camunda-platform-8.4/test/integration/scenarios/infra/values-infra-standard.yaml, charts/camunda-platform-alpha/test/integration/scenarios/infra/values-infra-preemptible.yaml, charts/camunda-platform-alpha/test/integration/scenarios/infra/values-infra-standard.yaml, charts/camunda-platform-latest/test/integration/scenarios/infra/values-infra-preemptible.yaml, charts/camunda-platform-latest/test/integration/scenarios/infra/values-infra-standard.yaml, docs/gha-workflows.md
=> ci: provide stable infrastructure via gha workflow

charts/camunda-platform-alpha/templates/identity/deployment.yaml, charts/camunda-platform-latest/templates/identity/deployment.yaml
Fixes: https://github.com/camunda/camunda-platform-helm/issues/2141
Fix a typo where Identity watched the wrong config.
=> fix: reload identity when its config changed

charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-latest/test/integration/testsuites/vars/files/testsuite-core.yaml, test/integration/scenarios/chart-full-setup/Taskfile.yaml, test/integration/testsuites/base/job.yaml, test/integration/testsuites/base/kustomization.yaml
Fixes: https://github.com/camunda/camunda-platform-helm/issues/2252
Fix Venom version and syntax, as the 1.2.0 version is case-sensitive by default.
=> chore: fix venom version and syntax

charts/camunda-platform-alpha/templates/web-modeler/deployment-webapp.yaml, charts/camunda-platform-alpha/test/unit/web-modeler/golden/deployment-webapp.golden.yaml, charts/camunda-platform-latest/templates/web-modeler/deployment-webapp.yaml, charts/camunda-platform-latest/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
closes: https://github.com/camunda/camunda-platform-helm/issues/2256
I have tested this configuration on GKE, and I can confirm that I see the `play` button on the webmodeler.
=> feat: adding play env var to web-modeler

charts/camunda-platform-alpha/templates/operate/configmap.yaml, charts/camunda-platform-alpha/templates/optimize/deployment.yaml, charts/camunda-platform-alpha/templates/tasklist/configmap.yaml, charts/camunda-platform-latest/templates/operate/configmap.yaml, charts/camunda-platform-latest/templates/optimize/deployment.yaml, charts/camunda-platform-latest/templates/tasklist/configmap.yaml
closes: https://github.com/camunda/camunda-platform-helm/issues/2215
I have added the AWS param for OpenSearch in the following app components:
- tasklist
- operate
- optimize
I have not tested this yet since the configs that I added are not yet existing in respective app components. I will wait until the linked issues are closed. Please see the issue linked to this PR for all the other related issues that need to be closed. 
=> feat: adding aws config in apps for OpenSearch

.github/workflows/test-integration-template.yaml
=> ci(repo): better format for the integration workflow inputs

README.md
Release-As: 11.0.0
Release please requires a commit on main to trigger a run / update the existing release-please PR.
A nothing whitespace commit with the Release-As field filled.
=> refactor: whitespace change to README.md for release-please

README.md
Release-As: 11.0.0
The previous whitespace change was a chore which release-please does not consider a "releasable unit"
=> fix: remove previously added whitespace

charts/camunda-platform-8.6/Chart.yaml
We want release-please to trigger.
=> feat: downgrade helm chart version for re-release

.github/config/release-please/.release-please-manifest.json
=> feat!: downgrade version once more

.github/config/release-please/.release-please-manifest.json, charts/camunda-platform-8.6/Chart.yaml
Release-As: 11.0.0
In this attempt we are trying with a -alpha chart version instead of trying to go from 10.4.0 to 11.0.0
=> chore: fix chart + release-please-manifest

.github/workflows/chart-release-candidate.yaml, .github/workflows/chart-release-snapshot.yaml, .github/workflows/chart-release-template.yaml
Related: https://github.com/camunda/camunda-platform-helm/issues/2404
Create release candidate workflow based on certain branches.
=> ci: create release candidate workflow

.github/workflows/chart-release-candidate.yaml, .github/workflows/chart-release-snapshot.yaml, .github/workflows/chart-release-template.yaml
Related: https://github.com/camunda/camunda-platform-helm/issues/2404
Update release candidate workflow
- update job name
- enable cosign verification
=> ci: update rc workflow

charts/camunda-platform-8.6/README.md
tbd
A documentation is added about how to configure client secrets
=> docs: added section about client secret handling

.github/config/external-secret/external-secret-credentials.yaml
=> fix: fixed typo in external-secret-credentials.yaml

charts/camunda-platform-alpha/test/integration/scenarios/common/values-integration-test.yaml
Task: https://github.com/camunda/camunda-platform-helm/issues/2525
Enable identity test client vars after the refactoring.
=> ci: enable identity test client vars

charts/camunda-platform-alpha/templates/camunda/_helpers.tpl, charts/camunda-platform-alpha/templates/connectors/_helpers.tpl, charts/camunda-platform-alpha/templates/connectors/configmap.yaml, charts/camunda-platform-alpha/templates/connectors/deployment.yaml, charts/camunda-platform-alpha/test/unit/connectors/deployment_test.go, charts/camunda-platform-alpha/test/unit/connectors/golden/configmap.golden.yaml, charts/camunda-platform-alpha/test/unit/connectors/golden/deployment.golden.yaml, charts/camunda-platform-alpha/test/unit/connectors/goldenfiles_test.go, charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml
Update Connectors config for 8.7 syntax.
=> refactor(alpha): update connectors config for 8.7

charts/camunda-platform-alpha/templates/core/configmap.yaml, charts/camunda-platform-alpha/test/unit/core/golden/configmap-authorizations.golden.yaml, charts/camunda-platform-alpha/test/unit/core/golden/configmap-log4j2.golden.yaml, charts/camunda-platform-alpha/test/unit/core/golden/configmap.golden.yaml
=> fix(core): Identity authorization request not found

.github/workflows/chart-release-candidate.yaml, .github/workflows/chart-release-pr.yml
Fixes: https://github.com/camunda/camunda-platform-helm/issues/2674
Release from the release-candidate branch, not the main branch, to avoid locking the main branch and ensure no PR merges affect the release.
=> ci: release from the release-candidate branch

version-matrix/camunda-8.2/README.md, version-matrix/camunda-8.3/README.md, version-matrix/camunda-8.4/README.md, version-matrix/camunda-8.5/README.md, version-matrix/camunda-8.6/README.md
#2679
This is a manual run of `make release.generate-version-matrix-released` because this CI pipeline did not work for the latest release.
In order to make this work, I had to modify the script `scripts/generate-version-matrix.sh`
```diff
diff --git a/scripts/generate-version-matrix.sh b/scripts/generate-version-matrix.sh
index a5a8a28e..075eeb55 100755
--- a/scripts/generate-version-matrix.sh
+++ b/scripts/generate-version-matrix.sh
@@ -43,10 +43,27 @@ get_versions_filtered () {
get_chart_images () {
chart_version="${1}"
test -d "${CHART_DIR}" || CHART_DIR="charts/camunda-platform-alpha"
+    if [[ "${chart_version}" == "8.3.22" ]]; then
+    helm template --skip-tests camunda "./charts/camunda-platform-8.3" \
+      --values "${CHART_DIR}/test/integration/scenarios/chart-full-setup/valu …
```
=> chore: updated version matrix

version-matrix/README.md
I forgot to update the index on helm.camunda.io
output of `make release.generate-version-matrix-index`
=> chore: update index

charts/camunda-platform-8.3/Chart.yaml
We need to re-release v8.3.22 due to a networking issue with `helm dependency update`. This does not require any code changes, just a re-release.  The goal of this PR is to downgrade the version of 8.3, so that I can follow up with a new branch that I will manually trigger the release process from. The plan is to: 
1. Merge this PR downgrading Chart.yaml to 8.3.21 (necessary for the Chart - Release GHA to determine that only the 8.3 chart changed.)
2. Cancel GHA jobs that might try to re-release or update state as result of this change.
3. delete github release for 8.3.22
4. delete github package 
5. create branch for re-release with updated version to 8.3.22
6. manually trigger release from branch with the trigger flag set.
7. merge branch updating the version to 8.3.22.
8. Cancel GHA …
=> chore: downgrade 8.3

.github/config/pr-labeler.yaml
Auto-label per version dir.
Also added `core` to the components, and CI area .
=> ci: auto-label per version dir

charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-preflight.yaml, charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-preflight.yaml, charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-preflight.yaml, charts/camunda-platform-8.5/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.5/test/integration/testsuites/vars/files/testsuite-preflight.yaml, charts/camunda-platform-8.6/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-8.6/test/integration/testsuites/vars/files/testsuite-preflight.yaml, charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-core.yaml, charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-preflight.yaml
I found a camelCase spelling error in the integration tests.
=> fix: fixing camelCase in integration tests

.github/config/release-please/.release-please-manifest.json, .github/config/release-please/release-please-config.json, .github/workflows/chart-release-chores.yml, .github/workflows/chart-release-pr.yml, .github/workflows/chart-release-update-config.yml, .github/workflows/repo-pr-conventions.yaml, charts/camunda-platform-alpha/Chart.yaml
Task: https://github.com/camunda/distribution/issues/378
Based on the team's past experience with consolidated PR for all Camunda Helm chart versions, we found it's better to split it into a PR per version.
=> cd: create a pr for each release version

charts/camunda-platform-alpha/Chart.yaml
adds a new line to trigger release-please again.
=> fix: add new line

charts/camunda-platform-8.6/Chart.yaml
add a new line to trigger the right release please PR.
=> fix: add new line to 8.6

charts/camunda-platform-alpha-8.8/templates/web-modeler/configmap-restapi.yaml, charts/camunda-platform-alpha-8.8/test/unit/web-modeler/configmap_restapi_test.go, charts/camunda-platform-alpha-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml, charts/camunda-platform-alpha-8.8/test/unit/web-modeler/types.go, charts/camunda-platform-alpha-8.8/values.schema.json, charts/camunda-platform-alpha-8.8/values.yaml, charts/camunda-platform-alpha/templates/web-modeler/configmap-restapi.yaml, charts/camunda-platform-alpha/test/unit/web-modeler/configmap_restapi_test.go, charts/camunda-platform-alpha/test/unit/web-modeler/golden/configmap-restapi.golden.yaml, charts/camunda-platform-alpha/test/unit/web-modeler/types.go, charts/camunda-platform-alpha/values.yaml
Follow-up for https://github.com/camunda/camunda-platform-helm/pull/2853
Removes another unnecessary configuration property which was missed before.
=> chore(web-modeler): remove unnecessary config property

.github/config/test-integration-matric.yaml, .github/config/test-integration-matrix.yaml
The file `test-integration-matrix.yaml` got accidentally deleted with https://github.com/camunda/camunda-platform-helm/pull/2986/files
--> Bringing back the file!
=> fix: bring back test-integration-matrix.yaml

.github/ISSUE_TEMPLATE/task_template.md
Replaces the gh tasklist notation with subtasks as deprecated.
=> docs: replace tasklist with sub-tasks

charts/camunda-platform-alpha/templates/camunda/_helpers.tpl, charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml
I backported the change in https://github.com/camunda/camunda-platform-helm/pull/2659 as 8.7 now has a different structure.
=> feat: added connectors to console config

.github/config/release-please/release-please-config.json
closes: https://github.com/camunda/distribution/issues/420
=> ci: add deps dependency to release please to trigger a PR

index.yaml
Reverts camunda/camunda-platform-helm#3048
=> fix: revert:  drop 8.2.34 once more

.github/actions/install-tool-versions/action.yml, .github/workflows/chart-chores.yaml, .github/workflows/chart-release-chores.yml, .github/workflows/chart-release-template.yaml, .github/workflows/chart-release.yaml, .github/workflows/chart-validate-template.yaml, .github/workflows/renovate-post-upgrade.yaml, .github/workflows/test-integration-template.yaml, .github/workflows/test-unit-template.yml
Task: https://github.com/camunda/distribution/issues/432
Unify asdf setup and select tools to install
=> ci: unify asdf setup and select tools to install

index.yaml
related to https://github.com/camunda/camunda-platform-helm/pull/3027
=> fix: update keywords in index.yaml

charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-core.yaml
This PR 
https://github.com/camunda/camunda-platform-helm/pull/3033
disables many components by default. To make this change consistent with our integration tests I disabled those parts of our integration tests.
disabled tests
=> test: disable tests for disabled components

charts/camunda-platform-alpha-8.8/test/integration/testsuites/vars/files/testsuite-preflight.yaml
=> test: disable more preflight tests  8.8

charts/camunda-platform-8.6/test/unit/identity/configmap_test.go, charts/camunda-platform-8.6/test/unit/identity/deployment_test.go, charts/camunda-platform-8.6/test/unit/identity/secret_test.go, charts/camunda-platform-8.6/test/unit/identity/service_test.go, charts/camunda-platform-8.6/test/unit/operate/configmap_test.go, charts/camunda-platform-8.6/test/unit/operate/deployment_test.go, charts/camunda-platform-8.6/test/unit/operate/service_test.go
This PR refactors the unit tests for identity and operate
=> fix: refactored unit tests for identity and operate in 8.6

charts/camunda-platform-8.6/test/unit/optimize/configmap_test.go, charts/camunda-platform-8.6/test/unit/optimize/deployment_test.go, charts/camunda-platform-8.6/test/unit/optimize/service_test.go
Refactoring for optimise in 8.6 unit tests to the new style
=> fix: refactored optimize unit tests to the new style for 8.6

charts/camunda-platform-8.8/templates/core/configmap.yaml, charts/camunda-platform-8.8/test/unit/core/golden/configmap-authorizations.golden.yaml, charts/camunda-platform-8.8/test/unit/core/golden/configmap-log4j2.golden.yaml, charts/camunda-platform-8.8/test/unit/core/golden/configmap.golden.yaml, charts/camunda-platform-8.8/values.schema.json
With the changes made in https://github.com/camunda/camunda/issues/28895, some parameters used by the schema manager were extracted out of the `CamundaExporter` configuration.
Updating the parameters in the core configMap:
- `zeebe.broker.exporters.CamundaExporter.args.history.retention.minimumAge` -> `camunda.database.retention.minimumAge`
- `zeebe.broker.exporters.CamundaExporter.args.history.retention. policyName ` -> `camunda.database.retention. policyName `
- `zeebe.broker.exporters.CamundaExporter.args.index.prefix` -> `zeebe.broker.exporters.CamundaExporter.args.connect.indexPrefix` (this is used by the exporter)
- `zeebe.broker.exporters.CamundaExporter.args.createSchema=true` => removed (the new parameter is `camunda.database.schema-manager.createSchema` and it already defaults …
=> refactor: update core configMap with retention parameters

charts/camunda-platform-8.7/test/unit/camunda/configmap_test.go, charts/camunda-platform-8.7/test/unit/camunda/constraints_test.go, charts/camunda-platform-8.7/test/unit/camunda/global_deployment_test.go, charts/camunda-platform-8.7/test/unit/camunda/identitykeycloak_constraints_test.go, charts/camunda-platform-8.7/test/unit/camunda/ingress_test.go, charts/camunda-platform-8.7/test/unit/camunda/secret_test.go, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go
- Refactor of unit tests in camunda 8.7 
=> fix: port of new style to camunda unit tests in 8.7

charts/camunda-platform-8.7/test/unit/console/deployment_test.go, charts/camunda-platform-8.7/test/unit/console/service_test.go, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go
- refactored unit tests in console of 8.7
=> fix: refactored console unit tests in 8.7

charts/camunda-platform-8.7/test/unit/identity/configmap_test.go, charts/camunda-platform-8.7/test/unit/identity/deployment_test.go, charts/camunda-platform-8.7/test/unit/identity/secret_test.go, charts/camunda-platform-8.7/test/unit/identity/service_test.go, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go
- Refactored identity to the new style in 8.7
=> fix: refactor of identity unit tests in 8.7

charts/camunda-platform-8.7/test/unit/optimize/configmap_test.go, charts/camunda-platform-8.7/test/unit/optimize/deployment_test.go, charts/camunda-platform-8.7/test/unit/optimize/service_test.go, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go
- refactored the optimize unit tests in 8.7
=> fix: refactored optimize unit tests to new style

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go, charts/camunda-platform-8.7/test/unit/web-modeler/configmap_restapi_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/configmap_shared_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/configmap_webapp_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/deployment_restapi_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/deployment_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/deployment_webapp_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/deployment_websockets_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/secret_restapi_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/secret_shared_test.go, charts/camunda-platform-8.7/test/unit/web-modeler/service_test.go
- web modeler unit tests refactored to the new style
=> fix: refactored web-modeler unit tests to new style

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.7/test/unit/tasklist/configmap_test.go, charts/camunda-platform-8.7/test/unit/tasklist/deployment_test.go, charts/camunda-platform-8.7/test/unit/tasklist/service_test.go, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go
- tasklist refactored to the new style in 8.7
=> fix: refactored tasklist unit tests to new style

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.5/test/unit/optimize/configmap_test.go, charts/camunda-platform-8.5/test/unit/optimize/deployment_test.go, charts/camunda-platform-8.5/test/unit/optimize/service_test.go
- refactored unit tests in optimize to the new style 
=> fix: refactored unit tests to new style in optimize on 8.5

charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go, charts/camunda-platform-8.7/test/unit/zeebe/poddisruptionbudget_test.go, charts/camunda-platform-8.7/test/unit/zeebe/statefulset_test.go
- zeebe unit tests refactored to the new style in 8.7
=> fix: refactored zeebe unit tests to new style in 8.7

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go, charts/camunda-platform-8.7/test/unit/zeebe-gateway/configmap_test.go, charts/camunda-platform-8.7/test/unit/zeebe-gateway/deployment_test.go, charts/camunda-platform-8.7/test/unit/zeebe-gateway/poddisruptionbudget_test.go, charts/camunda-platform-8.7/test/unit/zeebe-gateway/service_test.go
- refactoring of the unit test for 8.7 zeebe gateway
=> fix: refactored zeebe gateway unit tests to new style

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.5/test/unit/zeebe-gateway/configmap_test.go, charts/camunda-platform-8.5/test/unit/zeebe-gateway/deployment_test.go, charts/camunda-platform-8.5/test/unit/zeebe-gateway/poddisruptionbudget_test.go, charts/camunda-platform-8.5/test/unit/zeebe-gateway/service_test.go
- refactored zeebe-gateway unit tests in 8.5 to new style
=> fix: refactored unit tests to new style in zeebe-gateway 8.5

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.4/test/unit/optimize/deployment_test.go, charts/camunda-platform-8.4/test/unit/optimize/service_test.go
=> fix: refactor of optimize in 8.4

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.4/test/unit/operate/configmap_test.go, charts/camunda-platform-8.4/test/unit/operate/deployment_test.go, charts/camunda-platform-8.4/test/unit/operate/service_test.go
=> fix: refactor 8.4 unit test operate

charts/camunda-platform-8.4/test/unit/tasklist/configmap_test.go, charts/camunda-platform-8.4/test/unit/tasklist/deployment_test.go, charts/camunda-platform-8.4/test/unit/tasklist/service_test.go
=> fix: refactored unit tests in 8.4 to new style in tasklist

charts/camunda-platform-8.4/test/unit/zeebe/poddisruptionbudget_test.go, charts/camunda-platform-8.4/test/unit/zeebe/service_test.go, charts/camunda-platform-8.4/test/unit/zeebe/statefulset_test.go
=> fix: refactored unit tests in 8.4 to new style in zeebe

charts/camunda-platform-8.4/test/unit/zeebe-gateway/deployment_test.go, charts/camunda-platform-8.4/test/unit/zeebe-gateway/poddisruptionbudget_test.go, charts/camunda-platform-8.4/test/unit/zeebe-gateway/service_test.go
- refactor in 8.4 of zeebe-gateway
=> fix: refactored unit tests in 8.4 to new style in zeebe-gateway

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.4/test/unit/identity/configmap_test.go, charts/camunda-platform-8.4/test/unit/identity/deployment_test.go, charts/camunda-platform-8.4/test/unit/identity/secret_test.go, charts/camunda-platform-8.4/test/unit/identity/service_test.go
- Refactored unit tests to new style in identity 8.4
=> fix: refactor 8 4 unit test identity

.github/workflows/test-chart-version-template.yaml, .github/workflows/test-chart-version.yaml, charts/camunda-platform-8.4/test/unit/console/deployment_test.go, charts/camunda-platform-8.4/test/unit/console/service_test.go
- refactored console unit tests in 8.4 
=> fix: refactor 8.4 unit test console

charts/camunda-platform-8.4/test/unit/web-modeler/configmap_shared_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/deployment_restapi_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/deployment_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/deployment_webapp_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/deployment_websockets_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/secret_restapi_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/secret_shared_test.go, charts/camunda-platform-8.4/test/unit/web-modeler/service_test.go
- refactor in 8.4 of web modeler
=> fix: refactored unit tests in 8.4 to new style in web modeler

.github/workflows/test-integration-template.yaml
related: https://github.com/camunda/team-distribution/issues/390
This is a bug fix for the integration testing default scenario.
=> fix: scenario default type

README.md
This link is outdated since Zeebe 1.3!
broken link on Camunda Documentation
fixed link
=> Update README.md: fixed broken link

README.md, charts/README.md
Added Camunda and chart release cycle info.
=> docs: added release cycle info

charts/camunda-platform-8.8/templates/camunda/_helpers.tpl, charts/camunda-platform-8.8/templates/web-modeler/configmap-restapi.yaml, charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
Fixes: https://github.com/camunda/camunda-platform-helm/issues/3483
Update the Core URL.
=> fix: use correct core URL

charts/camunda-platform-8.5/Chart.yaml
linting errors in artifacthub were triggered. this should fix it. 
=> fix: description on chart.yaml for 8.5 

index.yaml
issues with artifacthub this will fix the linting error.
=> fix: update 8.5-10.7.2 description index.yaml

index.yaml
removing the `:` from the description in 8.5-10.7.1
=> fix: description for 8.5-10.7.1

index.yaml
updating timestamp so artifacthub accepts the changes.
=> Fix: update timestamp in index.yaml

charts/camunda-platform-8.8/templates/web-modeler/configmap-restapi.yaml, charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
Fixes https://github.com/camunda/camunda-platform-helm/issues/3648
Update the REST API endpoint in Web Modeler config in the 8.8 chart.
=> refactor: update rest api endpoint in web modeler config

charts/camunda-platform-8.7/templates/connectors/deployment.yaml, charts/camunda-platform-8.7/test/unit/connectors/deployment_test.go, charts/camunda-platform-8.7/test/unit/connectors/golden/deployment.golden.yaml
closes https://github.com/camunda/camunda-platform-helm/issues/3733
This PR replaces old properties with new ones.
=> fix: replaced old property with new one

charts/camunda-platform-8.7/test/integration/testsuites/package.json
Updates the e2e-test-suite package to latest (from `0.0.1` to `0.0.15`)
=> chore: update e2e-test-suite-package

.github/actions/workflow-vars/action.yml
Removes the URL shortener as a different workaround has been found
=> fix: remove random suffix generation from workflow vars action

charts/camunda-platform-8.8/templates/web-modeler/configmap-restapi.yaml, charts/camunda-platform-8.8/test/unit/web-modeler/configmap_restapi_test.go, charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml, charts/camunda-platform-8.8/test/unit/web-modeler/types.go
Closes https://github.com/camunda/web-modeler/issues/15743.
=> feat: set authorizations.enabled flag in Web Modeler cluster configuration

version-matrix/README.md, version-matrix/camunda-8.6/README.md
=> fix: version matrix for 8.6-11.8.0

charts/camunda-platform-8.8/templates/orchestration/configmap.yaml
relevant slack thread: https://camunda.slack.com/archives/C03RPUX701W/p1755096075139309
=> fix: malformed issuer-uri

.github/workflows/cleanup-namespace.yaml, .github/workflows/test-integration-runner.yaml, .github/workflows/test-integration-template.yaml, charts/camunda-platform-8.5/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-license.yaml, charts/camunda-platform-8.6/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-license.yaml, charts/camunda-platform-8.7/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-license.yaml, charts/camunda-platform-8.7/test/integration/scenarios/infra/values-infra-standard.yaml, charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-license.yaml, charts/camunda-platform-8.8/test/integration/scenarios/infra/values-infra-standard.yaml
=> ci: add license values to use helm repo

.github/config/external-secret/external-secret-8.5-integration-test-credentials.yaml
QA uses this secret value in their scenario files 
=> fix: add key to passwords secret

README.md
Trigger a new build to publish updated version for 12.5.0.
related to https://github.com/camunda/camunda-platform-helm/pull/4036
=> chore: remove whitespace

charts/camunda-platform-8.8/templates/orchestration/importer-configmap.yaml, charts/camunda-platform-8.8/templates/orchestration/migration-identity-job.yaml
Shoutout to @Szik for catching this.
related slack thread: https://camunda.slack.com/archives/C06BN4SRB6C/p1757097021292579
=> fix: helper function function and checksum correction in migraiton

charts/camunda-platform-8.8/templates/orchestration/migration-data-configmap.yaml
related issue: https://github.com/camunda/team-distribution/issues/415
=> fix: data migration configmap fix importer-finished-timeout

charts/camunda-platform-8.8/templates/orchestration/migration-data-configmap.yaml
Change the elasticsearch URL to opensearch URL
=> fix: opensearchURL for secondary storage

charts/camunda-platform-8.8/test/integration/scenarios/chart-full-setup/values-integration-test-ingress-qa-opensearch.yaml
=> fix: add the oidc group claim to opensearch

charts/camunda-platform-8.8/templates/orchestration/importer-deployment.yaml, charts/camunda-platform-8.8/templates/orchestration/migration-data-job.yaml, charts/camunda-platform-8.8/templates/orchestration/migration-identity-job.yaml, charts/camunda-platform-8.8/templates/orchestration/statefulset.yaml, charts/camunda-platform-8.8/test/unit/orchestration/golden/importer-deployment.golden.yaml, charts/camunda-platform-8.8/test/unit/orchestration/golden/migration-data-job.golden.yaml, charts/camunda-platform-8.8/test/unit/orchestration/golden/migration-identity-job.golden.yaml, charts/camunda-platform-8.8/test/unit/orchestration/golden/statefulset.golden.yaml
Add nodeSelector, affinity, and tolerations to orchestration extra resources like importer and migration.
=> refactor: add nodeSelector, affinity, and tolerations to orchestration extra resources

test/integration/scenarios/chart-full-setup/Taskfile.yaml, test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
@megglos found we are missing this.
=> fix: wait for jobs
